### ISSUE TITLE
Editor: Add the "Import Data Type" action/wizard to the Master view

### ISSUE THREAD

**Issue by EricWittmann** [Apicurio/apicurio-studio#1049]
Visual design found here:  https://marvelapp.com/dah6cba/screen/64972116

Users should be able to import data types from other API designs.  See the visual design linked above for details.

Note that it's unclear how this feature could work when the editor is embedded in another system besides Apicurio Studio.  We will likely need to design this so it can be disabled.  Consumers of the editor will need to be able to provide appropriate services (e.g. List APIs) to enable this functionality.

**Comment by Brijesh-briju** [comment]
im able to import datatype from another API but when i click Live documentation ..its throwing error
as given below------------------

Something went wrong...
Error downloading apicurio:2 Failed to fetch
Stack trace
Error: Error downloading apicurio:2 
Failed to fetch
    at https://cdn.jsdelivr.net/npm/redoc@next/bundles/redoc.standalone.js:63:6628
    at https://cdn.jsdelivr.net/npm/redoc@next/bundles/redoc.standalone.js:122:36080

TypeError: Failed to fetch
    at e.exports.f._onFinish (https://cdn.jsdelivr.net/npm/redoc@next/bundles/redoc.standalone.js:122:38159)
    at e.exports.<anonymous> (https://cdn.jsdelivr.net/npm/redoc@next/bundles/redoc.standalone.js:122:37076)
    at e.exports.s.emit (https://cdn.jsdelivr.net/npm/redoc@next/bundles/redoc.standalone.js:75:19861)
    at _ (https://cdn.jsdelivr.net/npm/redoc@next/bundles/redoc.standalone.js:75:26498)
    at https://cdn.jsdelivr.net/npm/redoc@next/bundles/redoc.standalone.js:75:29476
    at e.exports.v.end (https://cdn.jsdelivr.net/npm/redoc@next/bundles/redoc.standalone.js:75:29557)
    at e.exports.f.end (https://cdn.jsdelivr.net/npm/redoc@next/bundles/redoc.standalone.js:122:40131)
    at Object.l.get (https://cdn.jsdelivr.net/npm/redoc@next/bundles/redoc.standalone.js:63:71507)
    at https://cdn.jsdelivr.net/npm/redoc@next/bundles/redoc.standalone.js:122:35192
    at new Promise (<anonymous>)

ReDoc Version: 2.0.0-rc.26
Commit: 5bd2e62

**Comment by EricWittmann** [comment]
Hi @Brijesh-briju - thanks for reporting this bug.  I have opened a separate issue for this problem:

https://github.com/Apicurio/apicurio-studio/issues/1113
