### ISSUE TITLE
Importing data type results in bad YAML

### ISSUE THREAD

**Issue by jgindin-apptio** [Apicurio/apicurio-studio#1095]
THANK you for adding the explicit ability to import types from other API specs. This is GREAT!

When a type is imported, however, it is done with something like:
`$ref: 'apicurio:5#/components/schemas/Query'`

The problem here, is that when I download the YAML and run the codegen, it complains because there is no such thing as "apicurio:5". Instead of "apicurio:5" it should be, e.g., "QueryAPIv2.yaml" where "QueryAPIv2" is the name of the other API defined in Apicurio.

The current state means that after downloading the YAML, I have to manually edit the files before I can use them.

**Comment by EricWittmann** [comment]
Yes this support is a bit of a work in progress.  But here's what you can do for now.  When you download the YAML, choose the option to resolve all external references.  This will result in a downloaded document that has all of the external references "pulled in" to the file being downloaded, which will allow codegen and other tools to work properly.

In Apicurio Studio I'm referring to this option:

![image](https://user-images.githubusercontent.com/1890703/77100644-5fe0fc80-69ec-11ea-9638-ab3251cefb51.png)

**Comment by EricWittmann** [comment]
I think the various "view documentation" features in Apicurio Studio already do this dereferencing (I should double check that).

We have other plans/options in this area, including:

* Option to update the `$ref` to point to some canonical URL for the resource (this is difficult because there are potentially access restrictions to these resources in Apicurio Studio)
* Option to download the API **and** all dependencies as a e.g. .zip file

I'm open to other suggestions.

**Comment by jgindin** [comment]
I'll see if the dereference option works for me. (I was about to file a bug on this because last time I tried it I got a bunch of exceptions, but trying it right now worked!)

**Comment by EricWittmann** [comment]
OK cool.  Let me know if that's a reasonable workaround for now.  And please let me know if you can reproduce those exceptions you mentioned.

**Comment by jgindin** [comment]
For me, I think the best option would be instead of using "apicurio:5" to use the name of the API being referenced. This works for me, because I'm putting them all in the same directory on disk and running the codegen, which can pick them up without any issues.

One reason why the dereferencing may not work is because I only want 1 copy of the code generated. Otherwise, with Java, even though the output is exactly the same, they're different classes which are not considered to be "the same".

**Comment by jgindin** [comment]
Just got the exception. The downloaded YAML file simply contains:
`<html><head><title>Error</title></head><body>Internal Server Error</body></html>`

The exception is:
`apicurio-studio-api_1_af20b19ce20e | 2020-03-23 13:28:02,558 ERROR [io.undertow.request] (default task-45) UT005023: Exception handling request to /designs/5/content: org.jboss.resteasy.spi.UnhandledException: java.lang.IllegalArgumentException
apicurio-studio-api_1_af20b19ce20e | 	at org.jboss.resteasy.core.ExceptionHandler.handleApplicationException(ExceptionHandler.java:82)
apicurio-studio-api_1_af20b19ce20e | 	at org.jboss.resteasy.core.ExceptionHandler.handleException(ExceptionHandler.java:346)
apicurio-studio-api_1_af20b19ce20e | 	at org.jboss.resteasy.core.SynchronousDispatcher.writeException(SynchronousDispatcher.java:193)
apicurio-studio-api_1_af20b19ce20e | 	at org.jboss.resteasy.core.SynchronousDispatcher.invoke(SynchronousDispatcher.java:456)
apicurio-studio-api_1_af20b19ce20e | 	at org.jboss.resteasy.core.SynchronousDispatcher.lambda$invoke$4(SynchronousDispatcher.java:229)
apicurio-studio-api_1_af20b19ce20e | 	at org.jboss.resteasy.core.SynchronousDispatcher.lambda$preprocess$0(SynchronousDispatcher.java:135)
apicurio-studio-api_1_af20b19ce20e | 	at org.jboss.resteasy.core.interception.PreMatchContainerRequestContext.filter(PreMatchContainerRequestContext.java:356)
apicurio-studio-api_1_af20b19ce20e | 	at org.jboss.resteasy.core.SynchronousDispatcher.preprocess(SynchronousDispatcher.java:138)
apicurio-studio-api_1_af20b19ce20e | 	at org.jboss.resteasy.core.SynchronousDispatcher.invoke(SynchronousDispatcher.java:215)
apicurio-studio-api_1_af20b19ce20e | 	at org.jboss.resteasy.plugins.server.servlet.ServletContainerDispatcher.service(ServletContainerDispatcher.java:227)
apicurio-studio-api_1_af20b19ce20e | 	at org.jboss.resteasy.plugins.server.servlet.HttpServletDispatcher.service(HttpServletDispatcher.java:56)
apicurio-studio-api_1_af20b19ce20e | 	at org.jboss.resteasy.plugins.server.servlet.HttpServletDispatcher.service(HttpServletDispatcher.java:51)
apicurio-studio-api_1_af20b19ce20e | 	at javax.servlet.http.HttpServlet.service(HttpServlet.java:590)
apicurio-studio-api_1_af20b19ce20e | 	at io.undertow.servlet.handlers.ServletHandler.handleRequest(ServletHandler.java:74)
apicurio-studio-api_1_af20b19ce20e | 	at io.undertow.servlet.handlers.FilterHandler$FilterChainImpl.doFilter(FilterHandler.java:129)
apicurio-studio-api_1_af20b19ce20e | 	at io.apicurio.hub.api.security.KeycloakAuthenticationFilter.doFilter(KeycloakAuthenticationFilter.java:72)
apicurio-studio-api_1_af20b19ce20e | 	at io.undertow.servlet.core.ManagedFilter.doFilter(ManagedFilter.java:61)
apicurio-studio-api_1_af20b19ce20e | 	at io.undertow.servlet.handlers.FilterHandler$FilterChainImpl.doFilter(FilterHandler.java:131)
apicurio-studio-api_1_af20b19ce20e | 	at io.apicurio.hub.api.filters.DisableCachingFilter.doFilter(DisableCachingFilter.java:66)
apicurio-studio-api_1_af20b19ce20e | 	at io.undertow.servlet.core.ManagedFilter.doFilter(ManagedFilter.java:61)
apicurio-studio-api_1_af20b19ce20e | 	at io.undertow.servlet.handlers.FilterHandler$FilterChainImpl.doFilter(FilterHandler.java:131)
apicurio-studio-api_1_af20b19ce20e | 	at io.apicurio.hub.api.filters.CorsFilter.doFilter(CorsFilter.java:64)
apicurio-studio-api_1_af20b19ce20e | 	at io.undertow.servlet.core.ManagedFilter.doFilter(ManagedFilter.java:61)
apicurio-studio-api_1_af20b19ce20e | 	at io.undertow.servlet.handlers.FilterHandler$FilterChainImpl.doFilter(FilterHandler.java:131)
apicurio-studio-api_1_af20b19ce20e | 	at io.undertow.servlet.handlers.FilterHandler.handleRequest(FilterHandler.java:84)
apicurio-studio-api_1_af20b19ce20e | 	at io.undertow.servlet.handlers.security.ServletSecurityRoleHandler.handleRequest(ServletSecurityRoleHandler.java:62)
apicurio-studio-api_1_af20b19ce20e | 	at io.undertow.servlet.handlers.ServletChain$1.handleRequest(ServletChain.java:68)
apicurio-studio-api_1_af20b19ce20e | 	at io.undertow.servlet.handlers.ServletDispatchingHandler.handleRequest(ServletDispatchingHandler.java:36)
apicurio-studio-api_1_af20b19ce20e | 	at org.wildfly.extension.undertow.security.SecurityContextAssociationHandler.handleRequest(SecurityContextAssociationHandler.java:78)
apicurio-studio-api_1_af20b19ce20e | 	at io.undertow.server.handlers.PredicateHandler.handleRequest(PredicateHandler.java:43)
apicurio-studio-api_1_af20b19ce20e | 	at org.keycloak.adapters.undertow.UndertowAuthenticatedActionsHandler.handleRequest(UndertowAuthenticatedActionsHandler.java:66)
apicurio-studio-api_1_af20b19ce20e | 	at org.wildfly.swarm.keycloak.deployment.SecurityContextServletExtension.lambda$null$0(SecurityContextServletExtension.java:40)
apicurio-studio-api_1_af20b19ce20e | 	at org.wildfly.swarm.generated.FaviconErrorHandler.handleRequest(FaviconErrorHandler.java:61)
apicurio-studio-api_1_af20b19ce20e | 	at io.undertow.server.handlers.PathHandler.handleRequest(PathHandler.java:91)
apicurio-studio-api_1_af20b19ce20e | 	at io.undertow.servlet.handlers.RedirectDirHandler.handleRequest(RedirectDirHandler.java:68)
apicurio-studio-api_1_af20b19ce20e | 	at io.undertow.servlet.handlers.security.SSLInformationAssociationHandler.handleRequest(SSLInformationAssociationHandler.java:132)
apicurio-studio-api_1_af20b19ce20e | 	at io.undertow.servlet.handlers.security.ServletAuthenticationCallHandler.handleRequest(ServletAuthenticationCallHandler.java:57)
apicurio-studio-api_1_af20b19ce20e | 	at io.undertow.server.handlers.DisableCacheHandler.handleRequest(DisableCacheHandler.java:33)
apicurio-studio-api_1_af20b19ce20e | 	at io.undertow.server.handlers.PredicateHandler.handleRequest(PredicateHandler.java:43)
apicurio-studio-api_1_af20b19ce20e | 	at io.undertow.security.handlers.AuthenticationConstraintHandler.handleRequest(AuthenticationConstraintHandler.java:53)
apicurio-studio-api_1_af20b19ce20e | 	at io.undertow.security.handlers.AbstractConfidentialityHandler.handleRequest(AbstractConfidentialityHandler.java:46)
apicurio-studio-api_1_af20b19ce20e | 	at io.undertow.servlet.handlers.security.ServletConfidentialityConstraintHandler.handleRequest(ServletConfidentialityConstraintHandler.java:64)
apicurio-studio-api_1_af20b19ce20e | 	at io.undertow.servlet.handlers.security.ServletSecurityConstraintHandler.handleRequest(ServletSecurityConstraintHandler.java:59)
apicurio-studio-api_1_af20b19ce20e | 	at io.undertow.security.handlers.AuthenticationMechanismsHandler.handleRequest(AuthenticationMechanismsHandler.java:60)
apicurio-studio-api_1_af20b19ce20e | 	at io.undertow.servlet.handlers.security.CachedAuthenticatedSessionHandler.handleRequest(CachedAuthenticatedSessionHandler.java:77)
apicurio-studio-api_1_af20b19ce20e | 	at io.undertow.security.handlers.NotificationReceiverHandler.handleRequest(NotificationReceiverHandler.java:50)
apicurio-studio-api_1_af20b19ce20e | 	at io.undertow.security.handlers.AbstractSecurityContextAssociationHandler.handleRequest(AbstractSecurityContextAssociationHandler.java:43)
apicurio-studio-api_1_af20b19ce20e | 	at io.undertow.server.handlers.PredicateHandler.handleRequest(PredicateHandler.java:43)
apicurio-studio-api_1_af20b19ce20e | 	at org.wildfly.extension.undertow.security.jacc.JACCContextIdHandler.handleRequest(JACCContextIdHandler.java:61)
apicurio-studio-api_1_af20b19ce20e | 	at io.undertow.server.handlers.PredicateHandler.handleRequest(PredicateHandler.java:43)
apicurio-studio-api_1_af20b19ce20e | 	at org.wildfly.extension.undertow.deployment.GlobalRequestControllerHandler.handleRequest(GlobalRequestControllerHandler.java:68)
apicurio-studio-api_1_af20b19ce20e | 	at org.keycloak.adapters.undertow.ServletPreAuthActionsHandler.handleRequest(ServletPreAuthActionsHandler.java:69)
apicurio-studio-api_1_af20b19ce20e | 	at io.undertow.server.handlers.PredicateHandler.handleRequest(PredicateHandler.java:43)
apicurio-studio-api_1_af20b19ce20e | 	at io.undertow.servlet.handlers.ServletInitialHandler.handleFirstRequest(ServletInitialHandler.java:269)
apicurio-studio-api_1_af20b19ce20e | 	at io.undertow.servlet.handlers.ServletInitialHandler.access$100(ServletInitialHandler.java:78)
apicurio-studio-api_1_af20b19ce20e | 	at io.undertow.servlet.handlers.ServletInitialHandler$2.call(ServletInitialHandler.java:133)
apicurio-studio-api_1_af20b19ce20e | 	at io.undertow.servlet.handlers.ServletInitialHandler$2.call(ServletInitialHandler.java:130)
apicurio-studio-api_1_af20b19ce20e | 	at io.undertow.servlet.core.ServletRequestContextThreadSetupAction$1.call(ServletRequestContextThreadSetupAction.java:48)
apicurio-studio-api_1_af20b19ce20e | 	at io.undertow.servlet.core.ContextClassLoaderSetupAction$1.call(ContextClassLoaderSetupAction.java:43)
apicurio-studio-api_1_af20b19ce20e | 	at org.wildfly.extension.undertow.security.SecurityContextThreadSetupAction.lambda$create$0(SecurityContextThreadSetupAction.java:105)
apicurio-studio-api_1_af20b19ce20e | 	at org.wildfly.extension.undertow.deployment.UndertowDeploymentInfoService$UndertowThreadSetupAction.lambda$create$0(UndertowDeploymentInfoService.java:1504)
apicurio-studio-api_1_af20b19ce20e | 	at org.wildfly.extension.undertow.deployment.UndertowDeploymentInfoService$UndertowThreadSetupAction.lambda$create$0(UndertowDeploymentInfoService.java:1504)
apicurio-studio-api_1_af20b19ce20e | 	at org.wildfly.extension.undertow.deployment.UndertowDeploymentInfoService$UndertowThreadSetupAction.lambda$create$0(UndertowDeploymentInfoService.java:1504)
apicurio-studio-api_1_af20b19ce20e | 	at org.wildfly.extension.undertow.deployment.UndertowDeploymentInfoService$UndertowThreadSetupAction.lambda$create$0(UndertowDeploymentInfoService.java:1504)
apicurio-studio-api_1_af20b19ce20e | 	at org.wildfly.swarm.keycloak.deployment.KeycloakThreadSetupHandler.lambda$create$0(KeycloakThreadSetupHandler.java:35)
apicurio-studio-api_1_af20b19ce20e | 	at io.undertow.servlet.handlers.ServletInitialHandler.dispatchRequest(ServletInitialHandler.java:249)
apicurio-studio-api_1_af20b19ce20e | 	at io.undertow.servlet.handlers.ServletInitialHandler.access$000(ServletInitialHandler.java:78)
apicurio-studio-api_1_af20b19ce20e | 	at io.undertow.servlet.handlers.ServletInitialHandler$1.handleRequest(ServletInitialHandler.java:99)
apicurio-studio-api_1_af20b19ce20e | 	at io.undertow.server.Connectors.executeRootHandler(Connectors.java:376)
apicurio-studio-api_1_af20b19ce20e | 	at io.undertow.server.HttpServerExchange$1.run(HttpServerExchange.java:830)
apicurio-studio-api_1_af20b19ce20e | 	at org.jboss.threads.ContextClassLoaderSavingRunnable.run(ContextClassLoaderSavingRunnable.java:35)
apicurio-studio-api_1_af20b19ce20e | 	at org.jboss.threads.EnhancedQueueExecutor.safeRun(EnhancedQueueExecutor.java:1982)
apicurio-studio-api_1_af20b19ce20e | 	at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.doRunTask(EnhancedQueueExecutor.java:1486)
apicurio-studio-api_1_af20b19ce20e | 	at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1377)
apicurio-studio-api_1_af20b19ce20e | 	at java.lang.Thread.run(Thread.java:748)
apicurio-studio-api_1_af20b19ce20e | Caused by: java.lang.IllegalArgumentException
apicurio-studio-api_1_af20b19ce20e | 	at io.apicurio.datamodels.openapi.visitors.dereference.Reference.withAbsoluteFrom(Reference.java:74)
apicurio-studio-api_1_af20b19ce20e | 	at io.apicurio.datamodels.openapi.visitors.dereference.Dereferencer.dereference(Dereferencer.java:118)
apicurio-studio-api_1_af20b19ce20e | 	at io.apicurio.datamodels.Library.dereferenceDocument(Library.java:269)
apicurio-studio-api_1_af20b19ce20e | 	at io.apicurio.hub.api.content.ContentDereferencer.dereference(ContentDereferencer.java:57)
apicurio-studio-api_1_af20b19ce20e | 	at io.apicurio.hub.api.content.ContentDereferencer$Proxy$_$$_WeldClientProxy.dereference(Unknown Source)
apicurio-studio-api_1_af20b19ce20e | 	at io.apicurio.hub.api.rest.impl.DesignsResource.getContent(DesignsResource.java:609)
apicurio-studio-api_1_af20b19ce20e | 	at io.apicurio.hub.api.rest.impl.DesignsResource$Proxy$_$$_WeldClientProxy.getContent(Unknown Source)
apicurio-studio-api_1_af20b19ce20e | 	at sun.reflect.GeneratedMethodAccessor36.invoke(Unknown Source)
apicurio-studio-api_1_af20b19ce20e | 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
apicurio-studio-api_1_af20b19ce20e | 	at java.lang.reflect.Method.invoke(Method.java:498)
apicurio-studio-api_1_af20b19ce20e | 	at org.jboss.resteasy.core.MethodInjectorImpl.invoke(MethodInjectorImpl.java:138)
apicurio-studio-api_1_af20b19ce20e | 	at org.jboss.resteasy.core.ResourceMethodInvoker.internalInvokeOnTarget(ResourceMethodInvoker.java:517)
apicurio-studio-api_1_af20b19ce20e | 	at org.jboss.resteasy.core.ResourceMethodInvoker.invokeOnTargetAfterFilter(ResourceMethodInvoker.java:406)
apicurio-studio-api_1_af20b19ce20e | 	at org.jboss.resteasy.core.ResourceMethodInvoker.lambda$invokeOnTarget$0(ResourceMethodInvoker.java:370)
apicurio-studio-api_1_af20b19ce20e | 	at org.jboss.resteasy.core.interception.PreMatchContainerRequestContext.filter(PreMatchContainerRequestContext.java:356)
apicurio-studio-api_1_af20b19ce20e | 	at org.jboss.resteasy.core.ResourceMethodInvoker.invokeOnTarget(ResourceMethodInvoker.java:372)
apicurio-studio-api_1_af20b19ce20e | 	at org.jboss.resteasy.core.ResourceMethodInvoker.invoke(ResourceMethodInvoker.java:344)
apicurio-studio-api_1_af20b19ce20e | 	at org.jboss.resteasy.core.ResourceMethodInvoker.invoke(ResourceMethodInvoker.java:317)
apicurio-studio-api_1_af20b19ce20e | 	at org.jboss.resteasy.core.SynchronousDispatcher.invoke(SynchronousDispatcher.java:440)
apicurio-studio-api_1_af20b19ce20e | 	... 71 more
`

**Comment by jgindin** [comment]
OK...it looks like that exception happens when I have (yeah, this is not a good practice, but I'm trying to figure some things out):

- API spec A imports a type from API spec B
- API spec B imports a type from API spec A

If I make it that API spec B no longer imports from API spec A, then the download with resolution works.

The strange part about this is that if I import a type (say, foo) then wherever I have a reference to that type, it looks like:
`Foo:
      $ref: '#/components/schemas/Foo1'
` 

And the actual type is `Foo1`, whereas I would expect it to be `Foo`:
```
Foo1:
  properties:
    ...
```

**Comment by bodograumann** [comment]
This issue also applies to publishing APIs to git. Similarly to downloading there should be an option to simply dereference the imported types.
As a second option, the references should be transformed to include the file names of the other published APIs. This is slightly more fragile but prevents duplucation during code generation as already noted above.

**Comment by EricWittmann** [comment]
@bodograumann Good point, we should add the "dereference" option when publishing to Git.  Can you open up a separate GitHub issue for that change?

As for using names as references, I understand the need, but that would need to be a separate feature.  Apicurio Studio would not be able to reliably resolve another API definition by name, since names are not unique.  However, if we had a feature where you could download/publish an API definition and all its dependencies (e.g. as a ZIP) then we could be smarter about rewriting the references as local (named) files so they worked after downloading.

Thoughts @jsenko ?

**Comment by bodograumann** [comment]
We do actually publish all our definitions into a single repository.
I guess you are right that relying on the referenced APIs already being published and reachable in the target repo is quite specific though.

I like the idea of including dependencies when downloading or publishing. Maybe prefil their filenames by where they are published themselves?

```
[ ] Include dependencies in commit
    Dependent API │ File Name
    ──────────────┼────────────────────────
     Common Types │ [ common.openapi.yaml ]
```

What would be quite nice, is if there was some way to see, which changes are actually published. But that is another issue :-D (maybe https://github.com/Apicurio/apicurio-studio/issues/462)

**Comment by EricWittmann** [comment]
Good feedback.  I find the git based workflow in our Generate Project wizard better than the simple "publish to git" feature, because the Generate Project flow creates a pull request.  To emulate that with Publish, you would need to create a branch manually and then publish to that branch.  Not ideal.  Of course, pull requests aren't portable across git systems (GitLab has something... does Bitbucket?).

**Comment by bodograumann** [comment]
I hadn’t looked at the generate project feature before.
Now that I have, it feels like a different part of the process to me.
In my mental model, the API definitions in Apicurio are aways in flow and might contain incomplete changes.
Commiting them to Git creates a fixed point from which implementation can start.
Personally I do generate client code with openapi-generator, but others might prefer manual implementation, especially on the server side.
What do you use for code generaton in the projects feature? It seems currently only a small number of template options are supported.

**Comment by EricWittmann** [comment]
Sorry - I didn't mean to imply that you should use Generate Project for your use-case.  I was only commenting that the Git Flow found in that feature is superior (IMO) to the Git Flow found in the Publish feature.  The reason is that the former will create a pull request while the latter does not.

To answer your question, the Generate Project feature is currently home-grown, although we do use schema2pojo to generate java beans from the data types.  In the future, it would be good to have integration with the OpenAPI Tools code generator.

Also, if Bitbucket has pull requests now (maybe it always had them and I didn't know that) that's good info.
