### ISSUE TITLE
Inheritance (oneOf, AllOf, AnyOff) doen't show default data types

### ISSUE THREAD

**Issue by Stwissel** [Apicurio/apicurio-studio#1097]
I have a data type defined like this:
```yaml
oneOf:
    -
        type: string
    -
        type: number
    -
        $ref: '#/components/schemas/ISODate'
    -
        $ref: '#/components/schemas/RFC822Address'
description: 'Entry in a message list, can be String, email, Date or Number'
type: object
```
In the UI `string` and `number` don't show up as inherited type. Is that deliberate, according to spec, or an item that needs attention?

also: Doesn't show add button until first type is added via source tab (separate issue?)

**Comment by EricWittmann** [comment]
We'll have to work on this a bit more.  I see what you mean about both of these issues.  The inheritance support in the editor needs some more work.

However, when you say this:

> In the UI string and number don't show up as inherited type.

What do you mean, specifically?  Which part of the UI?  In the editor or in ReDoc?

**Comment by EricWittmann** [comment]
Nevermind, I see reproduced it and understand now.  The editor currently doesn't support non-referenced schemas in the inheritance stuff.  What you can do is create simple Data Types for the first two (the string and the number) and then add those as Inherited Schemas.

**Comment by Stwissel** [comment]
I changed the datatype to a a referenced schema, it shows in the UI now, but ReDoc barfs on it:

```
Incompatible types in allOf at "#/components/schemas/MessageListItem/oneOf/0"
Stack trace
Error: Incompatible types in allOf at "#/components/schemas/MessageListItem/oneOf/0"
    at e.mergeAllOf (https://cdn.jsdelivr.net/npm/redoc@next/bundles/redoc.standalone.js:130:47704)
    at new e (https://cdn.jsdelivr.net/npm/redoc@next/bundles/redoc.standalone.js:130:50932)
    at https://cdn.jsdelivr.net/npm/redoc@next/bundles/redoc.standalone.js:130:54835
    at Array.map (<anonymous>)
    at e.initOneOf (https://cdn.jsdelivr.net/npm/redoc@next/bundles/redoc.standalone.js:130:54706)
    at e.init (https://cdn.jsdelivr.net/npm/redoc@next/bundles/redoc.standalone.js:130:52914)
    at new e (https://cdn.jsdelivr.net/npm/redoc@next/bundles/redoc.standalone.js:130:50979)
    at e.init (https://cdn.jsdelivr.net/npm/redoc@next/bundles/redoc.standalone.js:130:54084)
    at new e (https://cdn.jsdelivr.net/npm/redoc@next/bundles/redoc.standalone.js:130:50979)
    at new e (https://cdn.jsdelivr.net/npm/redoc@next/bundles/redoc.standalone.js:130:56700)

ReDoc Version: 2.0.0-rc.26
Commit: 5bd2e62
```

with my definition for `MessageListItem`:

```
{
    "oneOf": [
        {
            "$ref": "#/components/schemas/ISODate"
        },
        {
            "$ref": "#/components/schemas/RFC822Address"
        },
        {
            "$ref": "#/components/schemas/MessageListString"
        },
        {
            "$ref": "#/components/schemas/MessageListNumber"
        }
    ],
    "description": "Entry in a message list, can be String, eMail, Date or Number"
}
```

and e.g. `RFC822Address`

```
{
    "description": "Internet format for eMail addresses, specified here: https://www.w3.org/Protocols/rfc822/",
    "type": "string",
    "example": "\"peter.pan@disney.com\"\n\"john.doe@unknown.org (John Doe)\"\n\"\\\"Jane Doe\\\" <jane@tarzan.org>\""
}
```

**Comment by EricWittmann** [comment]
That's a weird error in Redoc - esp. because the error says "allOf" but you're using a "oneOf".  Perhaps a bug in ReDoc?

**Comment by Stwissel** [comment]
seems like. Where to report?

**Comment by EricWittmann** [comment]
If you can confirm that it's a bug in ReDoc (for example by trying it here:  http://redocly.github.io/redoc/ ) then I think you should report that as an issue here:  https://github.com/Redocly/redoc/issues

**Comment by dougbreaux** [comment]
> also: Doesn't show add button until first type is added via source tab (separate issue?)

This has bitten me several times.

**Comment by EricWittmann** [comment]
I appreciate the +1 on this issue.  Thanks. :)
