### ISSUE TITLE
Error during startup when `$ mvn quarkus:dev`

### ISSUE THREAD

**Issue by turutosiya** [Apicurio/apicurio-studio#1396]
Hi, 

I'm trying to develop api with quarkus's hot reloading feature.
But when I run `mvn quarkus:dev` it seems it does not work.

Here is the log around stacktrace:

```
$ cd platforms/quarkus/api
$ mvn quarkus:dev

...

2021-01-29 09:47:46,265 DEBUG [io.net.uti.int.PlatformDependent] (Quarkus Main Thread) org.jctools-core.MpscChunkedArrayQueue: available
2021-01-29 09:47:46,276 DEBUG [io.qua.ver.cor.run.VertxCoreRecorder] (Quarkus Main Thread) Vertx has Native Transport Enabled: false
2021-01-29 09:47:46,321 DEBUG [io.net.buf.PooledByteBufAllocator] (vert.x-eventloop-thread-2) -Dio.netty.allocator.numHeapArenas: 16
2021-01-29 09:47:46,321 DEBUG [io.net.buf.PooledByteBufAllocator] (vert.x-eventloop-thread-2) -Dio.netty.allocator.numDirectArenas: 16
2021-01-29 09:47:46,321 DEBUG [io.net.buf.PooledByteBufAllocator] (vert.x-eventloop-thread-2) -Dio.netty.allocator.pageSize: 8192
2021-01-29 09:47:46,321 DEBUG [io.net.buf.PooledByteBufAllocator] (vert.x-eventloop-thread-2) -Dio.netty.allocator.maxOrder: 1
2021-01-29 09:47:46,321 DEBUG [io.net.buf.PooledByteBufAllocator] (vert.x-eventloop-thread-2) -Dio.netty.allocator.chunkSize: 16384
2021-01-29 09:47:46,321 DEBUG [io.net.buf.PooledByteBufAllocator] (vert.x-eventloop-thread-2) -Dio.netty.allocator.tinyCacheSize: 512
2021-01-29 09:47:46,321 DEBUG [io.net.buf.PooledByteBufAllocator] (vert.x-eventloop-thread-2) -Dio.netty.allocator.smallCacheSize: 256
2021-01-29 09:47:46,321 DEBUG [io.net.buf.PooledByteBufAllocator] (vert.x-eventloop-thread-2) -Dio.netty.allocator.normalCacheSize: 64
2021-01-29 09:47:46,321 DEBUG [io.net.buf.PooledByteBufAllocator] (vert.x-eventloop-thread-2) -Dio.netty.allocator.maxCachedBufferCapacity: 32768
2021-01-29 09:47:46,321 DEBUG [io.net.buf.PooledByteBufAllocator] (vert.x-eventloop-thread-2) -Dio.netty.allocator.cacheTrimInterval: 8192
2021-01-29 09:47:46,321 DEBUG [io.net.buf.PooledByteBufAllocator] (vert.x-eventloop-thread-2) -Dio.netty.allocator.cacheTrimIntervalMillis: 0
2021-01-29 09:47:46,321 DEBUG [io.net.buf.PooledByteBufAllocator] (vert.x-eventloop-thread-2) -Dio.netty.allocator.useCacheForAllThreads: true
2021-01-29 09:47:46,321 DEBUG [io.net.buf.PooledByteBufAllocator] (vert.x-eventloop-thread-2) -Dio.netty.allocator.maxCachedByteBuffersPerChunk: 1023
2021-01-29 09:47:46,352 DEBUG [io.net.buf.ByteBufUtil] (vert.x-eventloop-thread-2) -Dio.netty.allocator.type: pooled
2021-01-29 09:47:46,352 DEBUG [io.net.buf.ByteBufUtil] (vert.x-eventloop-thread-2) -Dio.netty.threadLocalDirectBufferSize: 0
2021-01-29 09:47:46,352 DEBUG [io.net.buf.ByteBufUtil] (vert.x-eventloop-thread-2) -Dio.netty.maxThreadLocalCharBufferSize: 16384
2021-01-29 09:47:46,386 DEBUG [io.qua.arc.impl] (Quarkus Main Thread) ArC DI container shut down
2021-01-29 09:47:46,387 ERROR [io.qua.run.Application] (Quarkus Main Thread) Failed to start application (with profile dev): java.net.ConnectException: Connection refused
	at sun.nio.ch.SocketChannelImpl.checkConnect(Native Method)
	at sun.nio.ch.SocketChannelImpl.finishConnect(SocketChannelImpl.java:715)
	at io.netty.channel.socket.nio.NioSocketChannel.doFinishConnect(NioSocketChannel.java:330)
	at io.netty.channel.nio.AbstractNioChannel$AbstractNioUnsafe.finishConnect(AbstractNioChannel.java:334)
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:702)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:650)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:576)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:493)
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989)
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.lang.Thread.run(Thread.java:748)

Quarkus application exited with code 1
Press Enter to restart or Ctrl + C to quit
2021-01-29 09:47:46,389 INFO  [io.qua.dep.dev.IsolatedDevModeMain] (main) Attempting to start hot replacement endpoint to recover from previous Quarkus startup failure
2021-01-29 09:47:46,420 DEBUG [io.net.uti.NetUtil] (vert.x-eventloop-thread-12) -Djava.net.preferIPv4Stack: false
2021-01-29 09:47:46,420 DEBUG [io.net.uti.NetUtil] (vert.x-eventloop-thread-12) -Djava.net.preferIPv6Addresses: false
2021-01-29 09:47:46,421 DEBUG [io.net.uti.NetUtil] (vert.x-eventloop-thread-12) Loopback interface: lo0 (lo0, 0:0:0:0:0:0:0:1%lo0)
2021-01-29 09:47:46,422 DEBUG [io.net.uti.NetUtil] (vert.x-eventloop-thread-12) Failed to get SOMAXCONN from sysctl and file /proc/sys/net/core/somaxconn. Default: 128
2021-01-29 09:47:50,657 FINE  [org.apa.htt.imp.con.PoolingHttpClientConnectionManager] (Thread-37) Closing expired connections
2021-01-29 09:47:50,658 FINE  [org.apa.htt.imp.con.PoolingHttpClientConnectionManager] (Thread-37) Closing connections idle longer than 30 SECONDS
2021-01-29 09:47:50,689 FINE  [org.apa.htt.imp.con.PoolingHttpClientConnectionManager] (Thread-39) Closing expired connections

...

```

Also I get error when I access via browser:

<img width="1145" alt="Screen Shot 2021-01-29 at 9 57 08" src="https://user-images.githubusercontent.com/17807/106217498-b62be800-6218-11eb-8d00-0612e58c48ad.png">

Do I need additional config or something when I run api with quarkus?

**Comment by carlesarnal** [comment]
Hi @turutosiya, yes, you also need an OIDC server up & running. If you need more information regarding the configuration see [this](https://github.com/Apicurio/apicurio-studio/blob/master/platforms/quarkus/api/README.md).

**Comment by turutosiya** [comment]
@carlesarnal Thanks. I understood. let me try!

**Comment by turutosiya** [comment]
@carlesarnal thanks. quarkus distro seems nice!
I can not find the docker container: `carnalca/apicurio-setup-image`, is the name correct?

**Comment by carlesarnal** [comment]
Hi @turutosiya, replace that image with this one -> chriske/apicurio-setup-image.

**Comment by turutosiya** [comment]
@carlesarnal Thanks! Finally, it worked!
