### ISSUE TITLE
Yarn install issue

### ISSUE THREAD

**Issue by vikashkumar122** [Apicurio/apicurio-studio#1452]
/apicurio-studio/front-end/studio
$ yarn install
yarn install v1.22.4
[1/4] Resolving packages...
[2/4] Fetching packages...
info fsevents@1.2.7: The platform "win32" is incompatible with this module.
info "fsevents@1.2.7" is an optional dependency and failed compatibility check.
Excluding it from installation.
[3/4] Linking dependencies...
warning " > tsickle@0.34.3" has incorrect peer dependency "typescript@~3.3.1".
[4/4] Building fresh packages...
[-/3] ⠂ waiting...
[2/3] ⠄ node-sass
error D:\vikash-code\api-curio\apicurio-studio\front-end\studio\node_modules\nod
e-sass: Command failed.
Exit code: 1
Command: node scripts/build.js
Arguments:
Directory: D:\vikash-code\api-curio\apicurio-studio\front-end\studio\node_module
s\node-sass
Output:
Building: C:\Program Files\nodejs\node.exe D:\vikash-code\api-curio\apicurio-stu
dio\front-end\studio\node_modules\node-gyp\bin\node-gyp.js rebuild --verbose --l
ibsass_ext= --libsass_cflags= --libsass_ldflags= --libsass_library=
gyp info it worked if it ends with ok
gyp verb cli [
gyp verb cli   'C:\\Program Files\\nodejs\\node.exe',
gyp verb cli   'D:\\vikash-code\\api-curio\\apicurio-studio\\front-end\\studio\\
node_modules\\node-gyp\\bin\\node-gyp.js',
gyp verb cli   'rebuild',
gyp verb cli   '--verbose',
gyp verb cli   '--libsass_ext=',
gyp verb cli   '--libsass_cflags=',
gyp verb cli   '--libsass_ldflags=',
gyp verb cli   '--libsass_library='
gyp verb cli ]
gyp info using node-gyp@3.8.0
gyp info using node@14.16.0 | win32 | x64
gyp verb command rebuild []
gyp verb command clean []
gyp verb clean removing "build" directory
gyp verb command configure []
gyp verb check python checking for Python executable "python2" in the PATH
gyp verb `which` failed Error: not found: python2
gyp verb `which` failed     at getNotFoundError (D:\vikash-code\api-curio\apicur
io-studio\front-end\studio\node_modules\which\which.js:13:12)
gyp verb `which` failed     at F (D:\vikash-code\api-curio\apicurio-studio\front
-end\studio\node_modules\which\which.js:68:19)
gyp verb `which` failed     at E (D:\vikash-code\api-curio\apicurio-studio\front
-end\studio\node_modules\which\which.js:80:29)
gyp verb `which` failed     at D:\vikash-code\api-curio\apicurio-studio\front-en
d\studio\node_modules\which\which.js:89:16
gyp verb `which` failed     at D:\vikash-code\api-curio\apicurio-studio\front-en
d\studio\node_modules\isexe\index.js:42:5
gyp verb `which` failed     at D:\vikash-code\api-curio\apicurio-studio\front-en
d\studio\node_modules\isexe\windows.js:36:5
gyp verb `which` failed     at FSReqCallback.oncomplete (fs.js:183:21)
gyp verb `which` failed  python2 Error: not found: python2
gyp verb `which` failed     at getNotFoundError (D:\vikash-code\api-curio\apicur
io-studio\front-end\studio\node_modules\which\which.js:13:12)
gyp verb `which` failed     at F (D:\vikash-code\api-curio\apicurio-studio\front
-end\studio\node_modules\which\which.js:68:19)
gyp verb `which` failed     at E (D:\vikash-code\api-curio\apicurio-studio\front
-end\studio\node_modules\which\which.js:80:29)
gyp verb `which` failed     at D:\vikash-code\api-curio\apicurio-studio\front-en
d\studio\node_modules\which\which.js:89:16
gyp verb `which` failed     at D:\vikash-code\api-curio\apicurio-studio\front-en
d\studio\node_modules\isexe\index.js:42:5
gyp verb `which` failed     at D:\vikash-code\api-curio\apicurio-studio\front-en
d\studio\node_modules\isexe\windows.js:36:5
gyp verb `which` failed     at FSReqCallback.oncomplete (fs.js:183:21) {
gyp verb `which` failed   code: 'ENOENT'
gyp verb `which` failed }
gyp verb check python checking for Python executable "python" in the PATH
gyp verb `which` succeeded python C:\Program Files\Python38\python.EXE
gyp ERR! configure error
gyp ERR! stack Error: Command failed: C:\Program Files\Python38\python.EXE -c im
port sys; print "%s.%s.%s" % sys.version_info[:3];
gyp ERR! stack   File "<string>", line 1
gyp ERR! stack     import sys; print "%s.%s.%s" % sys.version_info[:3];
gyp ERR! stack                       ^
gyp ERR! stack SyntaxError: invalid syntax
gyp ERR! stack
gyp ERR! stack     at ChildProcess.exithandler (child_process.js:308:12)
gyp ERR! stack     at ChildProcess.emit (events.js:315:20)
gyp ERR! stack     at maybeClose (internal/child_process.js:1048:16)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_proces
s.js:288:5)
gyp ERR! System Windows_NT 10.0.19042
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "D:\\vikash-code\\api-cur
io\\apicurio-studio\\front-end\\studio\\node_modules\\node-gyp\\bin\\node-gyp.js
" "rebuild" "--verbose" "--libsass_ext=" "--libsass_cflags=" "--libsass_ldflags=
" "--libsass_library="
gyp ERR! cwd D:\vikash-code\api-curio\apicurio-studio\front-end\studio\node_modu
les\node-sass
gyp ERR! node -v v14.16.0
gyp ERR! node-gyp -v v3.8.0
gyp ERR! not ok
Build failed with error code: 1

**Comment by EricWittmann** [comment]
So it looks like Windows NT OS with node version 14.16.0.  That's a much newer version of node than we use.  Mostly because the Studio UI was built a couple years ago and we haven't been keeping it updated with the latest versions of everything.

You may have to revert to an older node version.  You can see the versions the maven build script uses here:

https://github.com/Apicurio/apicurio-studio/blob/master/front-end/studio/pom.xml#L52-L61

Shockingly old, I know.  I would try dropping back a major version in node until it works.  If you get to 8 and it still doesn't work, then we have a problem.

Another thing you could try is to install python2, which is what it seems node-sass prefers.
