### ISSUE TITLE
Error starting docker-compose under Windows

### ISSUE THREAD

**Issue by tillias** [Apicurio/apicurio-studio#1586]
Hello folks, 
I'm trying to start studio under Windows 10:

```
C:\Development\Tools>git clone https://github.com/Apicurio/apicurio-studio.git
Cloning into 'apicurio-studio'...
remote: Enumerating objects: 38051, done.
remote: Counting objects: 100% (1764/1764), done.
remote: Compressing objects: 100% (728/728), done.
Receiving objects: 100% (38051/38051), 11.68 MiB | 5.05 MiB/s, done.d 36287 eceiving objects: 100% (38051/38051), 10.08 MiB | 5.03 MiB/s
Resolving deltas: 100% (22474/22474), done.

C:\Development\Tools\apicurio-studio\distro\docker-compose>docker run -v ${PWD}:/apicurio chriske/apicurio-setup-image:latest bash /apicurio/setup.sh 127.0.0.1 postgres
Unable to find image 'chriske/apicurio-setup-image:latest' locally
latest: Pulling from chriske/apicurio-setup-image
050382585609: Pull complete
9a15a844917b: Pull complete
Digest: sha256:318063cf8030658dc2985e146d26b9ceeef3c2dbdd6595e646e76fac0bee2f54
Status: Downloaded newer image for chriske/apicurio-setup-image:latest
docker: Error response from daemon: create ${PWD}: "${PWD}" includes invalid characters for a local volume name, 
             only "[a-zA-Z0-9][a-zA-Z0-9_.-]" are allowed. If you intended to pass a host directory, use absolute path.
See 'docker run --help'.        
```

Can you please advise what is wrong with local volume names?

**Comment by EricWittmann** [comment]
@tillias I think the issue here is that ${PWD} probably assumes a replacement that doesn't happen in Windows.  What shell are you using to try and start this?  Are you using `cmd` or powershell?

Let me try using the docker-compose on my Windows 10 box and see what I can find out. :)

**Comment by EricWittmann** [comment]
So I was able to get the docker compose working with some tweaking.  I'll update the Readme to reflect this, but I'll explain it here.  First, you need to be running from Powershell.  I suspect you were not and that is why the PWD bit didn't work for you.  But even if you switch to Powershell, things might fail due to Windows line endings vs. Unix line endings.  Whether this is a problem or not will depend on how you have git configured, but let's assume you have the default config where git automatically converts line endings for you.  In that case, the shell scripts in the docker compose will have windows line endings, and will thus fail when you try to run the docker image for configuration.

To fix this, we can tweak that command to use dos2unix to convert the file.  So I was able to get the config to work using this:

`docker run -v ${PWD}:/apicurio chriske/apicurio-setup-image:latest /bin/bash -c "cp /apicurio/setup.sh /tmp/apicurio-setup.sh ; dos2unix /tmp/apicurio-setup.sh ; bash /tmp/apicurio-setup.sh 192.168.1.198 mysql"`

Here is my output:

```
PS C:\Users\ewittman\git\apicurio\apicurio-studio\distro\docker-compose> docker run -v ${PWD}:/apicurio chriske/apicurio-setup-image:latest /bin/bash -c "cp /apicurio/setup.sh /tmp/apicurio-setup.sh ; dos2unix /tmp/apicurio-setup.sh ; bash /tmp/apicurio-setup.sh 192.168.1.198 mysql"
Keycloak username: admin
Keycloak password: 0LnYl9

Keycloak URL: 192.168.1.198:8090
Apicurio URL: 192.168.1.198:8093
Microcks URL: 192.168.1.198:8900
PS C:\Users\ewittman\git\apicurio\apicurio-studio\distro\docker-compose>
```

After that I was able to use the manual docker-compose commands to get everything up and running.

**Comment by tillias** [comment]
Do you use mysql or postgres?

I have issued
```
docker-compose -f docker-compose.keycloak-postgresql.yml build
docker-compose -f docker-compose.keycloak-postgresql.yml -f docker-compose.microcks.yml -f docker-compose.apicurio.yml -f docker-compose-as-postgre.yml up
```
and have:
```
jboss-keycloak_1             | Caused by: javax.resource.ResourceException: IJ031084: Unable to create connection
jboss-keycloak_1             |  at org.jboss.jca.adapters.jdbc.local.LocalManagedConnectionFactory.createLocalManagedConnection(LocalManagedConnectionFactory.java:345)
jboss-keycloak_1             |  at org.jboss.jca.adapters.jdbc.local.LocalManagedConnectionFactory.getLocalManagedConnection(LocalManagedConnectionFactory.java:352)
jboss-keycloak_1             |  at org.jboss.jca.adapters.jdbc.local.LocalManagedConnectionFactory.createManagedConnection(LocalManagedConnectionFactory.java:287)
jboss-keycloak_1             |  at org.jboss.jca.core.connectionmanager.pool.mcp.SemaphoreConcurrentLinkedDequeManagedConnectionPool.createConnectionEventListener(SemaphoreConcurrentLinkedDequeManagedConnectionPool.java:1325)
jboss-keycloak_1             |  at org.jboss.jca.core.connectionmanager.pool.mcp.SemaphoreConcurrentLinkedDequeManagedConnectionPool.getConnection(SemaphoreConcurrentLinkedDequeManagedConnectionPool.java:499)
jboss-keycloak_1             |  at org.jboss.jca.core.connectionmanager.pool.AbstractPool.getSimpleConnection(AbstractPool.java:632)
jboss-keycloak_1             |  at org.jboss.jca.core.connectionmanager.pool.AbstractPool.getConnection(AbstractPool.java:604)
jboss-keycloak_1             |  at org.jboss.jca.core.connectionmanager.AbstractConnectionManager.getManagedConnection(AbstractConnectionManager.java:624)
jboss-keycloak_1             |  ... 48 more
jboss-keycloak_1             | Caused by: com.mysql.jdbc.exceptions.jdbc4.CommunicationsException: Communications link failure
jboss-keycloak_1             |
jboss-keycloak_1             | The last packet sent successfully to the server was 0 milliseconds ago. The driver has not received any packets from the server.
jboss-keycloak_1             |  at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
jboss-keycloak_1             |  at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
jboss-keycloak_1             |  at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
jboss-keycloak_1             |  at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
jboss-keycloak_1             |  at com.mysql.jdbc.Util.handleNewInstance(Util.java:425)
jboss-keycloak_1             |  at com.mysql.jdbc.SQLError.createCommunicationsException(SQLError.java:990)
jboss-keycloak_1             |  at com.mysql.jdbc.MysqlIO.<init>(MysqlIO.java:342)
jboss-keycloak_1             |  at com.mysql.jdbc.ConnectionImpl.coreConnect(ConnectionImpl.java:2188)
jboss-keycloak_1             |  at com.mysql.jdbc.ConnectionImpl.connectOneTryOnly(ConnectionImpl.java:2221)
jboss-keycloak_1             |  at com.mysql.jdbc.ConnectionImpl.createNewIO(ConnectionImpl.java:2016)
jboss-keycloak_1             |  at com.mysql.jdbc.ConnectionImpl.<init>(ConnectionImpl.java:776)
jboss-keycloak_1             |  at com.mysql.jdbc.JDBC4Connection.<init>(JDBC4Connection.java:47)
jboss-keycloak_1             |  at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
jboss-keycloak_1             |  at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
jboss-keycloak_1             |  at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
jboss-keycloak_1             |  at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
jboss-keycloak_1             |  at com.mysql.jdbc.Util.handleNewInstance(Util.java:425)
jboss-keycloak_1             |  at com.mysql.jdbc.ConnectionImpl.getInstance(ConnectionImpl.java:386)
jboss-keycloak_1             |  at com.mysql.jdbc.NonRegisteringDriver.connect(NonRegisteringDriver.java:330)
jboss-keycloak_1             |  at org.jboss.jca.adapters.jdbc.local.LocalManagedConnectionFactory.createLocalManagedConnection(LocalManagedConnectionFactory.java:321)
jboss-keycloak_1             |  ... 55 more
jboss-keycloak_1             | Caused by: java.net.UnknownHostException: jboss-keycloak-mysql: Name or service not known
jboss-keycloak_1             |  at java.net.Inet4AddressImpl.lookupAllHostAddr(Native Method)
jboss-keycloak_1             |  at java.net.InetAddress$2.lookupAllHostAddr(InetAddress.java:929)
jboss-keycloak_1             |  at java.net.InetAddress.getAddressesFromNameService(InetAddress.java:1324)
jboss-keycloak_1             |  at java.net.InetAddress.getAllByName0(InetAddress.java:1277)
jboss-keycloak_1             |  at java.net.InetAddress.getAllByName(InetAddress.java:1193)
jboss-keycloak_1             |  at java.net.InetAddress.getAllByName(InetAddress.java:1127)
jboss-keycloak_1             |  at com.mysql.jdbc.StandardSocketFactory.connect(StandardSocketFactory.java:188)
jboss-keycloak_1             |  at com.mysql.jdbc.MysqlIO.<init>(MysqlIO.java:301)
jboss-keycloak_1             |  ... 68 more
jboss-keycloak_1             |
jboss-keycloak_1             | 15:30:33,333 INFO  [org.jboss.as.connector.subsystems.datasources] (MSC service thread 1-5) WFLYJCA0010: Unbound data source [java:jboss/datasources/KeycloakDS]
```

**Comment by EricWittmann** [comment]
I used mysql and was able to register a new user and then login without any problems.  I don't think you should need to configure anything extra in KC.  PG may be buggy I didn't try it.  I'll add that to the list of things to try later.

@tillias Do you have any errors on startup of the applications?  Did Keycloak start up?  Can you access it?

@carlesarnal any ideas?

**Comment by carlesarnal** [comment]
I've tried the Postgres distribution and is working fine for me in two steps:

- Execute setup script indicating postgresql as the database. `./setup.sh {IP_ADDRESS} postgresql`
- Execute start postgresql environment script. `./start-postgresql-environment.sh`

Note that the second step can be replaced by the docker-compose commands inside it. Also, note that if you have used the distro in the past you will need to execute the `reset_env.sh` script. Removing existing docker volumes is also highly recommended, `docker system prune --volumes`.

From what I see in the logs, it seems to me that you've used the distro in the past with MySQL and now you're trying to use the PostgreSQL distro without a proper reset. Let me know if that helps or if you need any guidance using it.

Thanks!

**Comment by tillias** [comment]
I have tried with mysql and it starts fine. So it was definitely keykloak-postgres related stuff.

Now after I open localhost:8093 to access studio-ui there is following:
2021-07-12 15:39:26,761 WARN [org.keycloak.adapters.KeycloakDeployment] (default task-1) Failed to load URLs from http://127.0.0.1:8090/auth/realms/apicurio/.well-known/openid-configuration: java.net.ConnectException: Connection refused (Connection refused)

Not sure if I need to populate some roles into keycloak or change some clientId?

**Comment by EricWittmann** [comment]
We're in the process of release Studio 0.2.49.Final (just done) and upgrading Keycloak to 14.  Give us a few days to get things stable and we'll try this again.  Tuesday of next week is when we're upgrading to KC 14.

**Comment by fari-99** [comment]
and i am here get an error:

![Screenshot 2021-12-15 092812](https://user-images.githubusercontent.com/8443932/146111882-1d9ec5d9-b305-41d0-8550-1fdc4f5452a2.jpg)

i am using WSL 2 (Ubuntu-20.04)

**Comment by EricWittmann** [comment]
Blast from the past!  Now that 0.2.51.Final is out, where do we stand with this?  Should we just close it?

**Comment by tillias** [comment]
Let's close it for now. We can reopen it if needed later 👍
