### ISSUE TITLE
Enable making Account Linking  IDENTITY_PROVIDER_LOGIN_ERROR

### ISSUE THREAD

**Issue by Aiden-zht** [Apicurio/apicurio-studio#1664]
According to the tutorial I https://www.apicur.io/studio/docs/setting-up-keycloak-for-use-with-apicurio 
7.1 Enable making Account Linking
But my report was wrong

09:27:33,088 WARN  [org.keycloak.events] (default task-2) type=IDENTITY_PROVIDER_LOGIN_ERROR, realmId=apicurio, clientId=null, userId=null, ipAddress=10.16.30.12, error=invalid_code

<img width="779" alt="image" src="https://user-images.githubusercontent.com/64518464/133884533-3185b99a-128f-4dcf-baed-f0433196435f.png">

I deployed through K8S

**Comment by EricWittmann** [comment]
It's possible that the instructions are stale.  There's not much info here to go on, and configuring account linking is a bit tricky (any typo or mis-configuration will definitely result in failure).  Perhaps also seek out Keycloak documentation on this, since their docs may be more useful and accurate.

If you want to try providing screenshots of your configs (both in Keycloak and in Github) maybe we could spot something...

**Comment by Aiden-zht** [comment]
> It's possible that the instructions are stale. There's not much info here to go on, and configuring account linking is a bit tricky (any typo or mis-configuration will definitely result in failure). Perhaps also seek out Keycloak documentation on this, since their docs may be more useful and accurate.
> 
> If you want to try providing screenshots of your configs (both in Keycloak and in Github) maybe we could spot something...

**Comment by Aiden-zht** [comment]
> It's possible that the instructions are stale. There's not much info here to go on, and configuring account linking is a bit tricky (any typo or mis-configuration will definitely result in failure). Perhaps also seek out Keycloak documentation on this, since their docs may be more useful and accurate.
> 
> If you want to try providing screenshots of your configs (both in Keycloak and in Github) maybe we could spot something...

**Comment by Aiden-zht** [comment]
> > 说明可能已经过时。这里没有太多信息可以继续，配置帐户链接有点棘手（任何错字或错误配置肯定会导致失败）。也许还可以查找有关此的 Keycloak 文档，因为他们的文档可能更有用和准确。
> > 如果你想尝试提供你的配置截图（在 Keycloak 和 Github 中）也许我们可以发现一些东西......

Thanks for your reply
this is keycloak config

apiVersion: v1
kind: Service
metadata:
  name: keycloak
  labels:
    app: keycloak
spec:
  ports:
  - name: http
    port: 8080
    targetPort: 8080
  selector:
    app: keycloak
  type: NodePort
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: keycloak
  labels:
    app: keycloak
spec:
  replicas: 1
  selector:
    matchLabels:
      app: keycloak
  template:
    metadata:
      labels:
        app: keycloak
    spec:
      containers:
      - name: keycloak
        #image: quay.io/keycloak/keycloak:14.0.0
        #image: aidenzht/keycloak:v1
        image: quay.io/keycloak/keycloak:15.0.2
        #image: quay.io/keycloak/keycloak:7.0.0
        env:
        - name: KEYCLOAK_USER
          value: "admin"
        - name: KEYCLOAK_PASSWORD
          value: "admin"
        - name: PROXY_ADDRESS_FORWARDING
          value: "true"
        - name: DB_VENDOR
          value: mariadb
        - name: DB_ADDR
          value: "mariadb"
        - name: DB_PORT
          value: "3306"
        - name: DB_DATABASE
          value: keycloak
          #value: key01
        - name: DB_USER
          value: "k8s_test"
        - name: DB_PASSWORD
          value: "Ab1234562021."
        #- name: KEYCLOAK_IMPORT
        #  value: "/tmp/realm.json -Dkeycloak.profile.feature.upload_scripts=enabled"
        ports:
        - name: http
          containerPort: 8080
        - name: https
          containerPort: 8443
        readinessProbe:
          httpGet:
            path: /auth/realms/master
            port: 8080

**Comment by Aiden-zht** [comment]
> > 说明可能已经过时。这里没有太多信息可以继续，配置帐户链接有点棘手（任何错字或错误配置肯定会导致失败）。也许还可以查找有关此的 Keycloak 文档，因为他们的文档可能更有用和准确。
> > 如果你想尝试提供你的配置截图（在 Keycloak 和 Github 中）也许我们可以发现一些东西......

But I still think there is something wrong with the apicurio because KeyCloak behaves normally

**Comment by EricWittmann** [comment]
Oh sorry, what I meant was the configuration of the IDP in Keycloak and in GitHub.  I'm sure the Keycloak deployment itself is configured fine (connected to a DB and all that).  But it's easy to get the configuration of the Identity Provider wrong in the Keycloak UI (and GitHub UI).

**Comment by Aiden-zht** [comment]
<img width="1018" alt="wecom-temp-72c47f810d955b2d69a2e15363f29a27" src="https://user-images.githubusercontent.com/64518464/134480309-91b2a2b8-7e57-412c-b9bc-1513047d23be.png">
I successfully logged in apicurio with github account, but the API window inside could not load
<img width="839" alt="wecom-temp-60a56e876f25a3f2bf0005645678d7bd" src="https://user-images.githubusercontent.com/64518464/134480431-a50b4d56-5ebe-44b4-8a93-d295ad41718b.png">
![image](https://user-images.githubusercontent.com/64518464/134480541-3320c3ee-a534-44e3-be37-f21d51fe1197.png)
I also found at https://github.com/Apicurio/apicurio-studio/blob/master/distro/kubernetes/apicurio-studio-api-deployment.yaml The service name in the last line is wrong
![image](https://user-images.githubusercontent.com/64518464/134480809-8c2c843a-9d70-4379-a2c5-07a9f1d15aa9.png)

**Comment by Aiden-zht** [comment]
this is api pod log 

2021-09-23 09:22:09,128 INFO  [org.jboss.weld.Bootstrap] (Weld Thread Pool -- 10) WELD-000119: Not generating any bean definitions from io.apicurio.hub.core.editing.distributed.JMSSessionFactory because of underlying class loading error: Type javax.jms.Destination from [Module "deployment.apicurio-studio-api.war" from Service Module Loader] not found.  If this is unexpected, enable DEBUG logging to see the full error.
2021-09-23 09:22:09,128 DEBUG [org.jboss.weld.Bootstrap] (Weld Thread Pool -- 10) Catching: org.jboss.weld.resources.spi.ResourceLoadingException: Error while loading class io.apicurio.hub.core.editing.distributed.JMSSessionFactory
	at org.jboss.weld.core@3.1.2.Final//org.jboss.weld.resources.ClassTransformer.getBackedAnnotatedType(ClassTransformer.java:186)
	at org.jboss.weld.core@3.1.2.Final//org.jboss.weld.resources.ClassTransformer.getBackedAnnotatedType(ClassTransformer.java:194)
	at org.jboss.weld.core@3.1.2.Final//org.jboss.weld.bootstrap.FastAnnotatedTypeLoader.loadSlimAnnotatedType(FastAnnotatedTypeLoader.java:124)
	at org.jboss.weld.core@3.1.2.Final//org.jboss.weld.bootstrap.FastAnnotatedTypeLoader.createContext(FastAnnotatedTypeLoader.java:114)
	at org.jboss.weld.core@3.1.2.Final//org.jboss.weld.bootstrap.FastAnnotatedTypeLoader.loadAnnotatedType(FastAnnotatedTypeLoader.java:103)
	at org.jboss.weld.core@3.1.2.Final//org.jboss.weld.bootstrap.BeanDeployer.addClass(BeanDeployer.java:87)
	at org.jboss.weld.core@3.1.2.Final//org.jboss.weld.bootstrap.ConcurrentBeanDeployer$1.doWork(ConcurrentBeanDeployer.java:55)
	at org.jboss.weld.core@3.1.2.Final//org.jboss.weld.bootstrap.ConcurrentBeanDeployer$1.doWork(ConcurrentBeanDeployer.java:52)
	at org.jboss.weld.core@3.1.2.Final//org.jboss.weld.executor.IterativeWorkerTaskFactory$1.call(IterativeWorkerTaskFactory.java:62)
	at org.jboss.weld.core@3.1.2.Final//org.jboss.weld.executor.IterativeWorkerTaskFactory$1.call(IterativeWorkerTaskFactory.java:55)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:829)
	at org.jboss.threads@2.3.3.Final//org.jboss.threads.JBossThread.run(JBossThread.java:485)
Caused by: java.lang.NoClassDefFoundError: javax/jms/Destination
	at java.base/java.lang.Class.getDeclaredConstructors0(Native Method)
	at java.base/java.lang.Class.privateGetDeclaredConstructors(Class.java:3137)
	at java.base/java.lang.Class.getDeclaredConstructors(Class.java:2357)
	at org.jboss.weld.core@3.1.2.Final//org.jboss.weld.annotated.slim.backed.SecurityActions.getDeclaredConstructors(SecurityActions.java:57)
	at org.jboss.weld.core@3.1.2.Final//org.jboss.weld.annotated.slim.backed.BackedAnnotatedType$BackedAnnotatedConstructors.computeValue(BackedAnnotatedType.java:166)
	at org.jboss.weld.core@3.1.2.Final//org.jboss.weld.annotated.slim.backed.BackedAnnotatedType$BackedAnnotatedConstructors.computeValue(BackedAnnotatedType.java:163)
	at org.jboss.weld.core@3.1.2.Final//org.jboss.weld.util.LazyValueHolder.get(LazyValueHolder.java:46)
	at org.jboss.weld.core@3.1.2.Final//org.jboss.weld.annotated.slim.backed.BackedAnnotatedType$EagerlyInitializedLazyValueHolder.<init>(BackedAnnotatedType.java:159)
	at org.jboss.weld.core@3.1.2.Final//org.jboss.weld.annotated.slim.backed.BackedAnnotatedType$BackedAnnotatedConstructors.<init>(BackedAnnotatedType.java:163)
	at org.jboss.weld.core@3.1.2.Final//org.jboss.weld.annotated.slim.backed.BackedAnnotatedType$BackedAnnotatedConstructors.<init>(BackedAnnotatedType.java:163)
	at org.jboss.weld.core@3.1.2.Final//org.jboss.weld.annotated.slim.backed.BackedAnnotatedType.<init>(BackedAnnotatedType.java:64)
	at org.jboss.weld.core@3.1.2.Final//org.jboss.weld.annotated.slim.backed.BackedAnnotatedType.of(BackedAnnotatedType.java:47)
	at org.jboss.weld.core@3.1.2.Final//org.jboss.weld.resources.ClassTransformer$TransformClassToBackedAnnotatedType.apply(ClassTransformer.java:84)
	at org.jboss.weld.core@3.1.2.Final//org.jboss.weld.resources.ClassTransformer$TransformClassToBackedAnnotatedType.apply(ClassTransformer.java:79)
	at org.jboss.weld.core@3.1.2.Final//org.jboss.weld.util.cache.ReentrantMapBackedComputingCache.lambda$null$0(ReentrantMapBackedComputingCache.java:55)
	at org.jboss.weld.core@3.1.2.Final//org.jboss.weld.util.WeakLazyValueHolder$1.computeValue(WeakLazyValueHolder.java:35)
	at org.jboss.weld.core@3.1.2.Final//org.jboss.weld.util.WeakLazyValueHolder.get(WeakLazyValueHolder.java:53)
	at org.jboss.weld.core@3.1.2.Final//org.jboss.weld.util.cache.ReentrantMapBackedComputingCache.getValue(ReentrantMapBackedComputingCache.java:72)
	at org.jboss.weld.core@3.1.2.Final//org.jboss.weld.util.cache.ReentrantMapBackedComputingCache.getCastValue(ReentrantMapBackedComputingCache.java:78)
	at org.jboss.weld.core@3.1.2.Final//org.jboss.weld.resources.ClassTransformer.getBackedAnnotatedType(ClassTransformer.java:177)
	... 14 more
Caused by: java.lang.ClassNotFoundException: javax.jms.Destination from [Module "deployment.apicurio-studio-api.war" from Service Module Loader]
	at org.jboss.modules.ModuleClassLoader.findClass(ModuleClassLoader.java:255)
	at org.jboss.modules.ConcurrentClassLoader.performLoadClassUnchecked(ConcurrentClassLoader.java:410)
	at org.jboss.modules.ConcurrentClassLoader.performLoadClass(ConcurrentClassLoader.java:398)
	at org.jboss.modules.ConcurrentClassLoader.loadClass(ConcurrentClassLoader.java:116)
	... 34 more

**Comment by Aiden-zht** [comment]
I upload all the api-pod log https://github.com/Aiden-zht/first/blob/master/log.txt

**Comment by EricWittmann** [comment]
OK so with your latest information it sounds like the authentication is working fine, but the problem is that the UI is failing to communicate with the back-end API.  To figure out what's going on there, you'll need to consult the browser devtools - either the console or the network tab.  That will tell you what API calls are being made and what the result is.  Is it making calls you expect?  What is the HTTP response?  Etc etc.

For example:

![image](https://user-images.githubusercontent.com/1890703/134709973-14e77e1a-97da-497a-ba9b-88803ecd8b8e.png)

![image](https://user-images.githubusercontent.com/1890703/134710107-557d6481-d581-4b74-9243-eabacc112525.png)

What do you see in yours?

**Comment by Aiden-zht** [comment]
look this 
![image](https://user-images.githubusercontent.com/64518464/134855296-66ce29d8-f0b9-4284-9593-5dc683b55baf.png)

My api-pod log didn't report an error but didn't provide service. I made sure that all urls were configured correctly and that the final error occurred within the API component。
