### ISSUE TITLE
Can't parse regex docker-compose

### ISSUE THREAD

**Issue by fari-99** [Apicurio/apicurio-studio#1749]
Using WSL version 2 (Ubuntu 20.04)

Procedure

1. Clone repo
2. Navigate to repo/distro/docker-compose
3. run `./setup.sh 197.168.1.169 mysql`
4. run `./start-mysql-environment.sh`

Error:
![Screenshot 2021-12-15 092812](https://user-images.githubusercontent.com/8443932/146116559-e9ce32d4-1318-4ea6-aa2b-70013b581cd3.jpg)

**Comment by EricWittmann** [comment]
I have Windows with WSL 2 available I can test this on.  I'll need to give it a try.

**Comment by fari-99** [comment]
@EricWittmann thank you for your time.

it also in my attention that it looks like someone forgot to delete this [line](https://github.com/Apicurio/apicurio-studio/blob/0ec81edec2f11a934a1244a22747049c8c43251e/distro/docker-compose/docker-compose.apicurio.yml#L5).

because of that it will throw error when you try to docker-compose up them.

**Comment by EricWittmann** [comment]
Unfortunately I am unable to get very far in my testing of docker compose within Ubuntu 20 on WSL 2.  Here is what I get:

```
ewittman@falcon:~/tmp/apicurio-studio/distro/docker-compose$ ./start-mysql-environment.sh
WARNING: Python-dotenv could not parse statement starting at line 68
Traceback (most recent call last):
  File "urllib3/connectionpool.py", line 677, in urlopen
  File "urllib3/connectionpool.py", line 392, in _make_request
  File "http/client.py", line 1277, in request
  File "http/client.py", line 1323, in _send_request
  File "http/client.py", line 1272, in endheaders
  File "http/client.py", line 1032, in _send_output
  File "http/client.py", line 972, in send
  File "docker/transport/unixconn.py", line 43, in connect
FileNotFoundError: [Errno 2] No such file or directory

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "requests/adapters.py", line 449, in send
  File "urllib3/connectionpool.py", line 727, in urlopen
  File "urllib3/util/retry.py", line 410, in increment
  File "urllib3/packages/six.py", line 734, in reraise
  File "urllib3/connectionpool.py", line 677, in urlopen
  File "urllib3/connectionpool.py", line 392, in _make_request
  File "http/client.py", line 1277, in request
  File "http/client.py", line 1323, in _send_request
  File "http/client.py", line 1272, in endheaders
  File "http/client.py", line 1032, in _send_output
  File "http/client.py", line 972, in send
  File "docker/transport/unixconn.py", line 43, in connect
urllib3.exceptions.ProtocolError: ('Connection aborted.', FileNotFoundError(2, 'No such file or directory'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "docker/api/client.py", line 214, in _retrieve_server_version
  File "docker/api/daemon.py", line 181, in version
  File "docker/utils/decorators.py", line 46, in inner
  File "docker/api/client.py", line 237, in _get
  File "requests/sessions.py", line 543, in get
  File "requests/sessions.py", line 530, in request
  File "requests/sessions.py", line 643, in send
  File "requests/adapters.py", line 498, in send
requests.exceptions.ConnectionError: ('Connection aborted.', FileNotFoundError(2, 'No such file or directory'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "docker-compose", line 3, in <module>
  File "compose/cli/main.py", line 81, in main
  File "compose/cli/main.py", line 200, in perform_command
  File "compose/cli/command.py", line 70, in project_from_options
  File "compose/cli/command.py", line 153, in get_project
  File "compose/cli/docker_client.py", line 43, in get_client
  File "compose/cli/docker_client.py", line 170, in docker_client
  File "docker/api/client.py", line 197, in __init__
  File "docker/api/client.py", line 222, in _retrieve_server_version
docker.errors.DockerException: Error while fetching server API version: ('Connection aborted.', FileNotFoundError(2, 'No such file or directory'))
[3952] Failed to execute script docker-compose
WARNING: Python-dotenv could not parse statement starting at line 68
WARNING: The APICURIO_UI_VALIDATION_CHANNELNAME_REGEXP variable is not set. Defaulting to a blank string.
Traceback (most recent call last):
  File "urllib3/connectionpool.py", line 677, in urlopen
  File "urllib3/connectionpool.py", line 392, in _make_request
  File "http/client.py", line 1277, in request
  File "http/client.py", line 1323, in _send_request
  File "http/client.py", line 1272, in endheaders
  File "http/client.py", line 1032, in _send_output
  File "http/client.py", line 972, in send
  File "docker/transport/unixconn.py", line 43, in connect
FileNotFoundError: [Errno 2] No such file or directory

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "requests/adapters.py", line 449, in send
  File "urllib3/connectionpool.py", line 727, in urlopen
  File "urllib3/util/retry.py", line 410, in increment
  File "urllib3/packages/six.py", line 734, in reraise
  File "urllib3/connectionpool.py", line 677, in urlopen
  File "urllib3/connectionpool.py", line 392, in _make_request
  File "http/client.py", line 1277, in request
  File "http/client.py", line 1323, in _send_request
  File "http/client.py", line 1272, in endheaders
  File "http/client.py", line 1032, in _send_output
  File "http/client.py", line 972, in send
  File "docker/transport/unixconn.py", line 43, in connect
urllib3.exceptions.ProtocolError: ('Connection aborted.', FileNotFoundError(2, 'No such file or directory'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "docker/api/client.py", line 214, in _retrieve_server_version
  File "docker/api/daemon.py", line 181, in version
  File "docker/utils/decorators.py", line 46, in inner
  File "docker/api/client.py", line 237, in _get
  File "requests/sessions.py", line 543, in get
  File "requests/sessions.py", line 530, in request
  File "requests/sessions.py", line 643, in send
  File "requests/adapters.py", line 498, in send
requests.exceptions.ConnectionError: ('Connection aborted.', FileNotFoundError(2, 'No such file or directory'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "docker-compose", line 3, in <module>
  File "compose/cli/main.py", line 81, in main
  File "compose/cli/main.py", line 200, in perform_command
  File "compose/cli/command.py", line 70, in project_from_options
  File "compose/cli/command.py", line 153, in get_project
  File "compose/cli/docker_client.py", line 43, in get_client
  File "compose/cli/docker_client.py", line 170, in docker_client
  File "docker/api/client.py", line 197, in __init__
  File "docker/api/client.py", line 222, in _retrieve_server_version
docker.errors.DockerException: Error while fetching server API version: ('Connection aborted.', FileNotFoundError(2, 'No such file or directory'))
[3956] Failed to execute script docker-compose
```

@carlesarnal When you have a moment could you test Studio with the latest docker compose configs?  I know you aren't using Windows + WSL but we can at least make sure this works in other environments.

**Comment by EricWittmann** [comment]
Note that the first part `WARNING: Python-dotenv could not parse statement starting at line 68` indicates an inability to parse the last variable in the `.env` file.  I just set the value to `''` and that warning cleared up.  @fari-99 if you manually edit the `.env` file and do the same (i.e. set the `APICURIO_UI_VALIDATION_CHANNELNAME_REGEXP` variable to empty value) then things might work OK.

**Comment by fari-99** [comment]
@EricWittmann , thanks i thought the `APICURIO_UI_VALIDATION_CHANNELNAME_REGEXP` are pretty important, mainly because i don't know anything about regex.

the work around, i change the .env.template `APICURIO_UI_VALIDATION_CHANNELNAME_REGEXP` to '*', empty value not worked.

btw the error you get on WSL, you need to close the terminal you use, and open new terminal session.

thanks for your help! i will close this ticket.

**Comment by EricWittmann** [comment]
Thanks @fari-99 

FWIW that regexp is only used in the UI in the AsyncAPI editor (IIRC) to validate user input in the modal used to create a channel.  It's pretty narrowly focused (was contributed by the community).  So something like `.*` would probably be a nice fallback.
