### ISSUE TITLE
ArrayIndexOutOfBoundsException after upgraded to v0.2.52.Final

### ISSUE THREAD

**Issue by mecseid** [Apicurio/apicurio-studio#1853]
After upgraded to 0.2.52.Final from 0.2.51.Final, I got the following stacktrace from api and ws component too:
```java
Picked up JAVA_TOOL_OPTIONS: -Djava.net.preferIPv4Stack=true
java.lang.reflect.InvocationTargetException
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:566)
at org.wildfly.swarm.bootstrap.MainInvoker.invoke(MainInvoker.java:57)
at org.wildfly.swarm.bootstrap.Main.run(Main.java:134)
at org.wildfly.swarm.bootstrap.Main.main(Main.java:87)
Caused by: java.lang.RuntimeException: java.lang.ArrayIndexOutOfBoundsException: Index 0 out of bounds for length 0
at org.wildfly.swarm.container:api@2.7.0.Final//org.wildfly.swarm.Swarm.initializeConfigView(Swarm.java:638)
at org.wildfly.swarm.container:api@2.7.0.Final//org.wildfly.swarm.Swarm.<init>(Swarm.java:257)
at org.wildfly.swarm.container:api@2.7.0.Final//org.wildfly.swarm.Swarm.<init>(Swarm.java:194)
at org.wildfly.swarm.container:api@2.7.0.Final//org.wildfly.swarm.Swarm.<init>(Swarm.java:181)
at org.wildfly.swarm.container:api@2.7.0.Final//org.wildfly.swarm.Swarm.main(Swarm.java:742)
... 7 more
Caused by: java.lang.ArrayIndexOutOfBoundsException: Index 0 out of bounds for length 0
at org.jboss.jandex@2.1.2.Final//org.jboss.jandex.Indexer.updateTypeTarget(Indexer.java:840)
at org.jboss.jandex@2.1.2.Final//org.jboss.jandex.Indexer.updateTypeTargets(Indexer.java:624)
at org.jboss.jandex@2.1.2.Final//org.jboss.jandex.Indexer.index(Indexer.java:1603)
at org.wildfly.swarm.container:api@2.7.0.Final//org.wildfly.swarm.Swarm.initializeConfigFiltersFatJar(Swarm.java:660)
at org.wildfly.swarm.container:api@2.7.0.Final//org.wildfly.swarm.Swarm.initializeConfigFilters(Swarm.java:644)
at org.wildfly.swarm.container:api@2.7.0.Final//org.wildfly.swarm.Swarm.initializeConfigView(Swarm.java:635)
... 11 more
Exception in thread "main" java.lang.reflect.InvocationTargetException
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:566)
at org.wildfly.swarm.bootstrap.MainInvoker.invoke(MainInvoker.java:57)
at org.wildfly.swarm.bootstrap.Main.run(Main.java:134)
at org.wildfly.swarm.bootstrap.Main.main(Main.java:87)
Caused by: java.lang.RuntimeException: java.lang.ArrayIndexOutOfBoundsException: Index 0 out of bounds for length 0
at org.wildfly.swarm.container:api@2.7.0.Final//org.wildfly.swarm.Swarm.initializeConfigView(Swarm.java:638)
at org.wildfly.swarm.container:api@2.7.0.Final//org.wildfly.swarm.Swarm.<init>(Swarm.java:257)
at org.wildfly.swarm.container:api@2.7.0.Final//org.wildfly.swarm.Swarm.<init>(Swarm.java:194)
at org.wildfly.swarm.container:api@2.7.0.Final//org.wildfly.swarm.Swarm.<init>(Swarm.java:181)
at org.wildfly.swarm.container:api@2.7.0.Final//org.wildfly.swarm.Swarm.main(Swarm.java:742)
... 7 more
Caused by: java.lang.ArrayIndexOutOfBoundsException: Index 0 out of bounds for length 0
at org.jboss.jandex@2.1.2.Final//org.jboss.jandex.Indexer.updateTypeTarget(Indexer.java:840)
at org.jboss.jandex@2.1.2.Final//org.jboss.jandex.Indexer.updateTypeTargets(Indexer.java:624)
at org.jboss.jandex@2.1.2.Final//org.jboss.jandex.Indexer.index(Indexer.java:1603)
at org.wildfly.swarm.container:api@2.7.0.Final//org.wildfly.swarm.Swarm.initializeConfigFiltersFatJar(Swarm.java:660)
at org.wildfly.swarm.container:api@2.7.0.Final//org.wildfly.swarm.Swarm.initializeConfigFilters(Swarm.java:644)
at org.wildfly.swarm.container:api@2.7.0.Final//org.wildfly.swarm.Swarm.initializeConfigView(Swarm.java:635)
... 11 more
```

**Comment by EricWittmann** [comment]
Yes unfortunately 0.2.52.Final is busted.  :( :( 

I think we've reached the end of life for Thorntail.  This should be the kick in the pants we needed to officially migrate to Quarkus.

**Comment by mecseid** [comment]
Sounds like a plan. :)
Do you have any roadmap/release date about it?

We use a lot Apicurio, and the latest release looks pretty good (by the release notes, because we can't try it :) ).

**Comment by EricWittmann** [comment]
We're going to discuss it this morning and see how close we already are to Quarkus.  We'll get it turned around as fast as we can.
