### ISSUE TITLE
Exception while loading TemplatesResource: NoClassDefFoundError

### ISSUE THREAD

**Issue by lbroudoux** [Apicurio/apicurio-studio#1894]
> Working on `master`branch and using `quarkus` flavor (but should be the same in traditional wildfly deployment)

When creating a new API, it appears that templates are no longer loaded. When looking the stack trace of API module, we can see following stuff:

```
2022-04-26 14:45:01,822 ERROR [io.und.req.io] (executor-thread-2) Exception handling request 3622debf-1830-4fe8-a8fd-9c006a7d94c9-2 to /templates: java.lang.NoClassDefFoundError: Could not initialize class io.apicurio.hub.api.rest.impl.TemplatesResource
	at io.apicurio.hub.api.rest.impl.TemplatesResource_Bean.create(Unknown Source)
	at io.apicurio.hub.api.rest.impl.TemplatesResource_Bean.create(Unknown Source)
	at io.quarkus.arc.impl.AbstractSharedContext.createInstanceHandle(AbstractSharedContext.java:101)
	at io.quarkus.arc.impl.AbstractSharedContext$1.get(AbstractSharedContext.java:29)
	at io.quarkus.arc.impl.AbstractSharedContext$1.get(AbstractSharedContext.java:26)
	at io.quarkus.arc.impl.LazyValue.get(LazyValue.java:26)
	at io.quarkus.arc.impl.ComputingCache.computeIfAbsent(ComputingCache.java:69)
	at io.quarkus.arc.impl.AbstractSharedContext.get(AbstractSharedContext.java:26)
	at io.apicurio.hub.api.rest.impl.TemplatesResource_Bean.get(Unknown Source)
[...]
```

Then, we have these following lines:

```
2022-04-26 14:45:01,822 ERROR [io.und.req.io] (executor-thread-1) Exception handling request 3622debf-1830-4fe8-a8fd-9c006a7d94c9-1 to /templates: java.util.ServiceConfigurationError: com.fasterxml.jackson.databind.Module: com.fasterxml.jackson.module.jaxb.JaxbAnnotationModule Unable to get public no-arg constructor
	at java.base/java.util.ServiceLoader.fail(ServiceLoader.java:582)
	at java.base/java.util.ServiceLoader.getConstructor(ServiceLoader.java:673)
	at java.base/java.util.ServiceLoader$LazyClassPathLookupIterator.hasNextService(ServiceLoader.java:1233)
	at java.base/java.util.ServiceLoader$LazyClassPathLookupIterator.hasNext(ServiceLoader.java:1265)
	at java.base/java.util.ServiceLoader$2.hasNext(ServiceLoader.java:1300)
	at java.base/java.util.ServiceLoader$3.hasNext(ServiceLoader.java:1385)
	at com.fasterxml.jackson.databind.ObjectMapper.findModules(ObjectMapper.java:1081)
	at com.fasterxml.jackson.databind.ObjectMapper.findModules(ObjectMapper.java:1065)
	at com.fasterxml.jackson.databind.ObjectMapper.findAndRegisterModules(ObjectMapper.java:1115)
	at io.apicurio.hub.api.rest.impl.TemplatesResource.<clinit>(TemplatesResource.java:68)
	at io.apicurio.hub.api.rest.impl.TemplatesResource_Bean.create(Unknown Source)
[...]
Caused by: java.lang.NoClassDefFoundError: com/fasterxml/jackson/databind/AnnotationIntrospector$XmlExtensions
[...]
Caused by: java.lang.ClassNotFoundException: com.fasterxml.jackson.databind.AnnotationIntrospector$XmlExtensions
```

It appears that `com.fasterxml.jackson.databind.AnnotationIntrospector$XmlExtensions` was introduced with `jackson-databind` 2.13 and Apicurio pom is referencing `2.12.5`... Gonna try to update the dependency to check.

**Comment by EricWittmann** [comment]
Fixed in https://github.com/Apicurio/apicurio-studio/commit/77761097cecc057809bd8d478abdfa3f61c15c73
