### ISSUE TITLE
java.lang.NoClassDefFoundError: java/security/acl/Group following Quickstart directions

### ISSUE THREAD

**Issue by jeremyrdavis** [Apicurio/apicurio-studio#1918]
**Issue**

I get an error when installing and starting WildFly as per the instructions here: https://www.apicur.io/studio/download/

_Installation_
mkdir ~/apicurio-studio-0.2.54.Final
cd ~/apicurio-studio-0.2.54.Final
curl -L https://github.com/Apicurio/apicurio-studio/releases/download/0.2.54.Final/apicurio-studio-0.2.54.Final-quickstart.zip -o apicurio-studio-0.2.54.Final-quickstart.zip
unzip apicurio-studio-0.2.54.Final-quickstart.zip
cd apicurio-studio-0.2.54.Final
./bin/standalone.sh -c standalone-apicurio.xml

_Error_
"java.lang.NoClassDefFoundError: java/security/acl/Group
	at org.keycloak.keycloak-wildfly-adapter@17.0.1//org.keycloak.adapters.wildfly.WildflyAuthenticationMechanism.createRequestAuthenticator(WildflyAuthenticationMechanism.java:49)
	at org.keycloak.keycloak-wildfly-adapter@17.0.1//org.keycloak.adapters.wildfly.WildflyAuthenticationMechanism.createRequestAuthenticator(WildflyAuthenticationMechanism.java:36)
	at org.keycloak.keycloak-undertow-adapter@17.0.1//org.keycloak.adapters.undertow.ServletKeycloakAuthMech.authenticate(ServletKeycloakAuthMech.java:90)
	at io.undertow.core@2.0.21.Final//io.undertow.security.impl.SecurityContextImpl$AuthAttempter.transition(SecurityContextImpl.java:245)
	at io.undertow.core@2.0.21.Final//io.undertow.security.impl.SecurityContextImpl$AuthAttempter.transition(SecurityContextImpl.java:268)
	at io.undertow.core@2.0.21.Final//io.undertow.security.impl.SecurityContextImpl$AuthAttempter.access$100(SecurityContextImpl.java:231)
	at io.undertow.core@2.0.21.Final//io.undertow.security.impl.SecurityContextImpl.attemptAuthentication(SecurityContextImpl.java:125)
	at io.undertow.core@2.0.21.Final//io.undertow.security.impl.SecurityContextImpl.authTransition(SecurityContextImpl.java:99)
	at io.undertow.core@2.0.21.Final//io.undertow.security.impl.SecurityContextImpl.authenticate(SecurityContextImpl.java:92)
	at io.undertow.servlet@2.0.21.Final//io.undertow.servlet.handlers.security.ServletAuthenticationCallHandler.handleRequest(ServletAuthenticationCallHandler.java:55)
	at io.undertow.core@2.0.21.Final//io.undertow.server.handlers.DisableCacheHandler.handleRequest(DisableCacheHandler.java:33)
	at io.undertow.core@2.0.21.Final//io.undertow.server.handlers.PredicateHandler.handleRequest(PredicateHandler.java:43)
	at io.undertow.core@2.0.21.Final//io.undertow.security.handlers.AuthenticationConstraintHandler.handleRequest(AuthenticationConstraintHandler.java:53)
	at io.undertow.core@2.0.21.Final//io.undertow.security.handlers.AbstractConfidentialityHandler.handleRequest(AbstractConfidentialityHandler.java:46)
	at io.undertow.servlet@2.0.21.Final//io.undertow.servlet.handlers.security.ServletConfidentialityConstraintHandler.handleRequest(ServletConfidentialityConstraintHandler.java:64)
	at io.undertow.servlet@2.0.21.Final//io.undertow.servlet.handlers.security.ServletSecurityConstraintHandler.handleRequest(ServletSecurityConstraintHandler.java:59)
	at io.undertow.core@2.0.21.Final//io.undertow.security.handlers.AuthenticationMechanismsHandler.handleRequest(AuthenticationMechanismsHandler.java:60)
	at io.undertow.servlet@2.0.21.Final//io.undertow.servlet.handlers.security.CachedAuthenticatedSessionHandler.handleRequest(CachedAuthenticatedSessionHandler.java:77)
	at io.undertow.core@2.0.21.Final//io.undertow.security.handlers.NotificationReceiverHandler.handleRequest(NotificationReceiverHandler.java:50)
	at io.undertow.core@2.0.21.Final//io.undertow.security.handlers.AbstractSecurityContextAssociationHandler.handleRequest(AbstractSecurityContextAssociationHandler.java:43)
	at io.undertow.core@2.0.21.Final//io.undertow.server.handlers.PredicateHandler.handleRequest(PredicateHandler.java:43)
	at org.wildfly.extension.undertow@17.0.1.Final//org.wildfly.extension.undertow.security.jacc.JACCContextIdHandler.handleRequest(JACCContextIdHandler.java:61)
	at io.undertow.core@2.0.21.Final//io.undertow.server.handlers.PredicateHandler.handleRequest(PredicateHandler.java:43)
	at org.wildfly.extension.undertow@17.0.1.Final//org.wildfly.extension.undertow.deployment.GlobalRequestControllerHandler.handleRequest(GlobalRequestControllerHandler.java:68)
	at org.keycloak.keycloak-undertow-adapter@17.0.1//org.keycloak.adapters.undertow.ServletPreAuthActionsHandler.handleRequest(ServletPreAuthActionsHandler.java:69)
	at io.undertow.core@2.0.21.Final//io.undertow.server.handlers.PredicateHandler.handleRequest(PredicateHandler.java:43)
	at io.undertow.servlet@2.0.21.Final//io.undertow.servlet.handlers.ServletInitialHandler.handleFirstRequest(ServletInitialHandler.java:292)
	at io.undertow.servlet@2.0.21.Final//io.undertow.servlet.handlers.ServletInitialHandler.access$100(ServletInitialHandler.java:81)
	at io.undertow.servlet@2.0.21.Final//io.undertow.servlet.handlers.ServletInitialHandler$2.call(ServletInitialHandler.java:138)
	at io.undertow.servlet@2.0.21.Final//io.undertow.servlet.handlers.ServletInitialHandler$2.call(ServletInitialHandler.java:135)
	at io.undertow.servlet@2.0.21.Final//io.undertow.servlet.core.ServletRequestContextThreadSetupAction$1.call(ServletRequestContextThreadSetupAction.java:48)
	at io.undertow.servlet@2.0.21.Final//io.undertow.servlet.core.ContextClassLoaderSetupAction$1.call(ContextClassLoaderSetupAction.java:43)
	at org.wildfly.extension.undertow@17.0.1.Final//org.wildfly.extension.undertow.security.SecurityContextThreadSetupAction.lambda$create$0(SecurityContextThreadSetupAction.java:105)
	at org.wildfly.extension.undertow@17.0.1.Final//org.wildfly.extension.undertow.deployment.UndertowDeploymentInfoService$UndertowThreadSetupAction.lambda$create$0(UndertowDeploymentInfoService.java:1502)
	at org.wildfly.extension.undertow@17.0.1.Final//org.wildfly.extension.undertow.deployment.UndertowDeploymentInfoService$UndertowThreadSetupAction.lambda$create$0(UndertowDeploymentInfoService.java:1502)
	at org.wildfly.extension.undertow@17.0.1.Final//org.wildfly.extension.undertow.deployment.UndertowDeploymentInfoService$UndertowThreadSetupAction.lambda$create$0(UndertowDeploymentInfoService.java:1502)
	at org.wildfly.extension.undertow@17.0.1.Final//org.wildfly.extension.undertow.deployment.UndertowDeploymentInfoService$UndertowThreadSetupAction.lambda$create$0(UndertowDeploymentInfoService.java:1502)
	at io.undertow.servlet@2.0.21.Final//io.undertow.servlet.handlers.ServletInitialHandler.dispatchRequest(ServletInitialHandler.java:272)
	at io.undertow.servlet@2.0.21.Final//io.undertow.servlet.handlers.ServletInitialHandler.access$000(ServletInitialHandler.java:81)
	at io.undertow.servlet@2.0.21.Final//io.undertow.servlet.handlers.ServletInitialHandler$1.handleRequest(ServletInitialHandler.java:104)
	at io.undertow.core@2.0.21.Final//io.undertow.server.Connectors.executeRootHandler(Connectors.java:364)
	at io.undertow.core@2.0.21.Final//io.undertow.server.HttpServerExchange$1.run(HttpServerExchange.java:830)
	at org.jboss.threads@2.3.3.Final//org.jboss.threads.ContextClassLoaderSavingRunnable.run(ContextClassLoaderSavingRunnable.java:35)
	at org.jboss.threads@2.3.3.Final//org.jboss.threads.EnhancedQueueExecutor.safeRun(EnhancedQueueExecutor.java:1982)
	at org.jboss.threads@2.3.3.Final//org.jboss.threads.EnhancedQueueExecutor$ThreadBody.doRunTask(EnhancedQueueExecutor.java:1486)
	at org.jboss.threads@2.3.3.Final//org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1377)
	at java.base/java.lang.Thread.run(Thread.java:833)
Caused by: java.lang.ClassNotFoundException: java.security.acl.Group from [Module "org.keycloak.keycloak-wildfly-adapter" version 17.0.1 from local module loader @31ff43be (finder: local module finder @5b6ec132 (roots: /Users/jeremydavis/Workspace/conferencr/apicurio-studio-0.2.54.Final/apicurio-studio-0.2.54.Final/modules,/Users/jeremydavis/Workspace/conferencr/apicurio-studio-0.2.54.Final/apicurio-studio-0.2.54.Final/modules/system/layers/base,/Users/jeremydavis/Workspace/conferencr/apicurio-studio-0.2.54.Final/apicurio-studio-0.2.54.Final/modules/system/add-ons/keycloak))]
	at org.jboss.modules.ModuleClassLoader.findClass(ModuleClassLoader.java:255)
	at org.jboss.modules.ConcurrentClassLoader.performLoadClassUnchecked(ConcurrentClassLoader.java:410)
	at org.jboss.modules.ConcurrentClassLoader.performLoadClass(ConcurrentClassLoader.java:398)
	at org.jboss.modules.ConcurrentClassLoader.loadClass(ConcurrentClassLoader.java:116)
	... 47 more"

**Environment**
MacBook Pro M1
OSX 12.3.1
OpenJDK Runtime Environment (build 17.0.2+8-86)

**Comment by DavidRodriguezOzaeta** [comment]
> **Issue**
> 
> I get an error when installing and starting WildFly as per the instructions here: https://www.apicur.io/studio/download/
> 
> _Installation_ mkdir ~/apicurio-studio-0.2.54.Final cd ~/apicurio-studio-0.2.54.Final curl -L https://github.com/Apicurio/apicurio-studio/releases/download/0.2.54.Final/apicurio-studio-0.2.54.Final-quickstart.zip -o apicurio-studio-0.2.54.Final-quickstart.zip unzip apicurio-studio-0.2.54.Final-quickstart.zip cd apicurio-studio-0.2.54.Final ./bin/standalone.sh -c standalone-apicurio.xml
> 
> _Error_ "java.lang.NoClassDefFoundError: java/security/acl/Group at org.keycloak.keycloak-wildfly-adapter@17.0.1//org.keycloak.adapters.wildfly.WildflyAuthenticationMechanism.createRequestAuthenticator(WildflyAuthenticationMechanism.java:49) at org.keycloak.keycloak-wildfly-adapter@17.0.1//org.keycloak.adapters.wildfly.WildflyAuthenticationMechanism.createRequestAuthenticator(WildflyAuthenticationMechanism.java:36) at org.keycloak.keycloak-undertow-adapter@17.0.1//org.keycloak.adapters.undertow.ServletKeycloakAuthMech.authenticate(ServletKeycloakAuthMech.java:90) at [io.undertow.core@2.0.21.Final](mailto:io.undertow.core@2.0.21.Final)//io.undertow.security.impl.SecurityContextImpl$AuthAttempter.transition(SecurityContextImpl.java:245) at [io.undertow.core@2.0.21.Final](mailto:io.undertow.core@2.0.21.Final)//io.undertow.security.impl.SecurityContextImpl$AuthAttempter.transition(SecurityContextImpl.java:268) at [io.undertow.core@2.0.21.Final](mailto:io.undertow.core@2.0.21.Final)//io.undertow.security.impl.SecurityContextImpl$AuthAttempter.access$100(SecurityContextImpl.java:231) at [io.undertow.core@2.0.21.Final](mailto:io.undertow.core@2.0.21.Final)//io.undertow.security.impl.SecurityContextImpl.attemptAuthentication(SecurityContextImpl.java:125) at [io.undertow.core@2.0.21.Final](mailto:io.undertow.core@2.0.21.Final)//io.undertow.security.impl.SecurityContextImpl.authTransition(SecurityContextImpl.java:99) at [io.undertow.core@2.0.21.Final](mailto:io.undertow.core@2.0.21.Final)//io.undertow.security.impl.SecurityContextImpl.authenticate(SecurityContextImpl.java:92) at [io.undertow.servlet@2.0.21.Final](mailto:io.undertow.servlet@2.0.21.Final)//io.undertow.servlet.handlers.security.ServletAuthenticationCallHandler.handleRequest(ServletAuthenticationCallHandler.java:55) at [io.undertow.core@2.0.21.Final](mailto:io.undertow.core@2.0.21.Final)//io.undertow.server.handlers.DisableCacheHandler.handleRequest(DisableCacheHandler.java:33) at [io.undertow.core@2.0.21.Final](mailto:io.undertow.core@2.0.21.Final)//io.undertow.server.handlers.PredicateHandler.handleRequest(PredicateHandler.java:43) at [io.undertow.core@2.0.21.Final](mailto:io.undertow.core@2.0.21.Final)//io.undertow.security.handlers.AuthenticationConstraintHandler.handleRequest(AuthenticationConstraintHandler.java:53) at [io.undertow.core@2.0.21.Final](mailto:io.undertow.core@2.0.21.Final)//io.undertow.security.handlers.AbstractConfidentialityHandler.handleRequest(AbstractConfidentialityHandler.java:46) at [io.undertow.servlet@2.0.21.Final](mailto:io.undertow.servlet@2.0.21.Final)//io.undertow.servlet.handlers.security.ServletConfidentialityConstraintHandler.handleRequest(ServletConfidentialityConstraintHandler.java:64) at [io.undertow.servlet@2.0.21.Final](mailto:io.undertow.servlet@2.0.21.Final)//io.undertow.servlet.handlers.security.ServletSecurityConstraintHandler.handleRequest(ServletSecurityConstraintHandler.java:59) at [io.undertow.core@2.0.21.Final](mailto:io.undertow.core@2.0.21.Final)//io.undertow.security.handlers.AuthenticationMechanismsHandler.handleRequest(AuthenticationMechanismsHandler.java:60) at [io.undertow.servlet@2.0.21.Final](mailto:io.undertow.servlet@2.0.21.Final)//io.undertow.servlet.handlers.security.CachedAuthenticatedSessionHandler.handleRequest(CachedAuthenticatedSessionHandler.java:77) at [io.undertow.core@2.0.21.Final](mailto:io.undertow.core@2.0.21.Final)//io.undertow.security.handlers.NotificationReceiverHandler.handleRequest(NotificationReceiverHandler.java:50) at [io.undertow.core@2.0.21.Final](mailto:io.undertow.core@2.0.21.Final)//io.undertow.security.handlers.AbstractSecurityContextAssociationHandler.handleRequest(AbstractSecurityContextAssociationHandler.java:43) at [io.undertow.core@2.0.21.Final](mailto:io.undertow.core@2.0.21.Final)//io.undertow.server.handlers.PredicateHandler.handleRequest(PredicateHandler.java:43) at [org.wildfly.extension.undertow@17.0.1.Final](mailto:org.wildfly.extension.undertow@17.0.1.Final)//org.wildfly.extension.undertow.security.jacc.JACCContextIdHandler.handleRequest(JACCContextIdHandler.java:61) at [io.undertow.core@2.0.21.Final](mailto:io.undertow.core@2.0.21.Final)//io.undertow.server.handlers.PredicateHandler.handleRequest(PredicateHandler.java:43) at [org.wildfly.extension.undertow@17.0.1.Final](mailto:org.wildfly.extension.undertow@17.0.1.Final)//org.wildfly.extension.undertow.deployment.GlobalRequestControllerHandler.handleRequest(GlobalRequestControllerHandler.java:68) at org.keycloak.keycloak-undertow-adapter@17.0.1//org.keycloak.adapters.undertow.ServletPreAuthActionsHandler.handleRequest(ServletPreAuthActionsHandler.java:69) at [io.undertow.core@2.0.21.Final](mailto:io.undertow.core@2.0.21.Final)//io.undertow.server.handlers.PredicateHandler.handleRequest(PredicateHandler.java:43) at [io.undertow.servlet@2.0.21.Final](mailto:io.undertow.servlet@2.0.21.Final)//io.undertow.servlet.handlers.ServletInitialHandler.handleFirstRequest(ServletInitialHandler.java:292) at [io.undertow.servlet@2.0.21.Final](mailto:io.undertow.servlet@2.0.21.Final)//io.undertow.servlet.handlers.ServletInitialHandler.access$100(ServletInitialHandler.java:81) at [io.undertow.servlet@2.0.21.Final](mailto:io.undertow.servlet@2.0.21.Final)//io.undertow.servlet.handlers.ServletInitialHandler$2.call(ServletInitialHandler.java:138) at [io.undertow.servlet@2.0.21.Final](mailto:io.undertow.servlet@2.0.21.Final)//io.undertow.servlet.handlers.ServletInitialHandler$2.call(ServletInitialHandler.java:135) at [io.undertow.servlet@2.0.21.Final](mailto:io.undertow.servlet@2.0.21.Final)//io.undertow.servlet.core.ServletRequestContextThreadSetupAction$1.call(ServletRequestContextThreadSetupAction.java:48) at [io.undertow.servlet@2.0.21.Final](mailto:io.undertow.servlet@2.0.21.Final)//io.undertow.servlet.core.ContextClassLoaderSetupAction$1.call(ContextClassLoaderSetupAction.java:43) at [org.wildfly.extension.undertow@17.0.1.Final](mailto:org.wildfly.extension.undertow@17.0.1.Final)//org.wildfly.extension.undertow.security.SecurityContextThreadSetupAction.lambda$create$0(SecurityContextThreadSetupAction.java:105) at [org.wildfly.extension.undertow@17.0.1.Final](mailto:org.wildfly.extension.undertow@17.0.1.Final)//org.wildfly.extension.undertow.deployment.UndertowDeploymentInfoService$UndertowThreadSetupAction.lambda$create$0(UndertowDeploymentInfoService.java:1502) at [org.wildfly.extension.undertow@17.0.1.Final](mailto:org.wildfly.extension.undertow@17.0.1.Final)//org.wildfly.extension.undertow.deployment.UndertowDeploymentInfoService$UndertowThreadSetupAction.lambda$create$0(UndertowDeploymentInfoService.java:1502) at [org.wildfly.extension.undertow@17.0.1.Final](mailto:org.wildfly.extension.undertow@17.0.1.Final)//org.wildfly.extension.undertow.deployment.UndertowDeploymentInfoService$UndertowThreadSetupAction.lambda$create$0(UndertowDeploymentInfoService.java:1502) at [org.wildfly.extension.undertow@17.0.1.Final](mailto:org.wildfly.extension.undertow@17.0.1.Final)//org.wildfly.extension.undertow.deployment.UndertowDeploymentInfoService$UndertowThreadSetupAction.lambda$create$0(UndertowDeploymentInfoService.java:1502) at [io.undertow.servlet@2.0.21.Final](mailto:io.undertow.servlet@2.0.21.Final)//io.undertow.servlet.handlers.ServletInitialHandler.dispatchRequest(ServletInitialHandler.java:272) at [io.undertow.servlet@2.0.21.Final](mailto:io.undertow.servlet@2.0.21.Final)//io.undertow.servlet.handlers.ServletInitialHandler.access$000(ServletInitialHandler.java:81) at [io.undertow.servlet@2.0.21.Final](mailto:io.undertow.servlet@2.0.21.Final)//io.undertow.servlet.handlers.ServletInitialHandler$1.handleRequest(ServletInitialHandler.java:104) at [io.undertow.core@2.0.21.Final](mailto:io.undertow.core@2.0.21.Final)//io.undertow.server.Connectors.executeRootHandler(Connectors.java:364) at [io.undertow.core@2.0.21.Final](mailto:io.undertow.core@2.0.21.Final)//io.undertow.server.HttpServerExchange$1.run(HttpServerExchange.java:830) at [org.jboss.threads@2.3.3.Final](mailto:org.jboss.threads@2.3.3.Final)//org.jboss.threads.ContextClassLoaderSavingRunnable.run(ContextClassLoaderSavingRunnable.java:35) at [org.jboss.threads@2.3.3.Final](mailto:org.jboss.threads@2.3.3.Final)//org.jboss.threads.EnhancedQueueExecutor.safeRun(EnhancedQueueExecutor.java:1982) at [org.jboss.threads@2.3.3.Final](mailto:org.jboss.threads@2.3.3.Final)//org.jboss.threads.EnhancedQueueExecutor$ThreadBody.doRunTask(EnhancedQueueExecutor.java:1486) at [org.jboss.threads@2.3.3.Final](mailto:org.jboss.threads@2.3.3.Final)//org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1377) at java.base/java.lang.Thread.run(Thread.java:833) Caused by: java.lang.ClassNotFoundException: java.security.acl.Group from [Module "org.keycloak.keycloak-wildfly-adapter" version 17.0.1 from local module loader @31ff43be (finder: local module finder @5b6ec132 (roots: /Users/jeremydavis/Workspace/conferencr/apicurio-studio-0.2.54.Final/apicurio-studio-0.2.54.Final/modules,/Users/jeremydavis/Workspace/conferencr/apicurio-studio-0.2.54.Final/apicurio-studio-0.2.54.Final/modules/system/layers/base,/Users/jeremydavis/Workspace/conferencr/apicurio-studio-0.2.54.Final/apicurio-studio-0.2.54.Final/modules/system/add-ons/keycloak))] at org.jboss.modules.ModuleClassLoader.findClass(ModuleClassLoader.java:255) at org.jboss.modules.ConcurrentClassLoader.performLoadClassUnchecked(ConcurrentClassLoader.java:410) at org.jboss.modules.ConcurrentClassLoader.performLoadClass(ConcurrentClassLoader.java:398) at org.jboss.modules.ConcurrentClassLoader.loadClass(ConcurrentClassLoader.java:116) ... 47 more"
> 
> **Environment** MacBook Pro M1 OSX 12.3.1 OpenJDK Runtime Environment (build 17.0.2+8-86)

I replied to you, check and try :P
