### ISSUE TITLE
[docker-compose] Failed to load URLs

### ISSUE THREAD

**Issue by joyearnaud** [Apicurio/apicurio-studio#1960]
Hello,

Environment:

Windows 11 pro / WSL2 Ubuntu,  Docker version 20.10.17, build 100c701 / Version 103.0.5060.114 (Build officiel) (64 bits)
ApiCurio release - latest on Master branch at this time

Issue description:

We have been trying to test ApiCurio on our local Docker compose to evaluate it, but we are having difficult time setting it up using its Docker Compose distro ...

- [docker-compose distro](https://github.com/Apicurio/apicurio-studio/tree/master/distro/docker-compose) is not running correctly
- [docke-compose quarkus distro](https://github.com/Apicurio/apicurio-studio/tree/master/distro/quarkus/docker-compose) is not running correctly

- What (seems to) work:
  - keycloak
  - apicurio-studio-api
  - apicurio-studio-ws
  - mirocks

- problem
  - starting `./start-xxx-environment.sh` give have a problem with the default `APICURIO_UI_VALIDATION_CHANNELNAME_REGEXP`
    - unexpected character "\\" in variable name near "\\''%<>\\\\^`{|}]|%[0-9A-Fa-f]{2}|\\{[+#./;?&=,!@|]?((\\w|%[0-9A-Fa-f]{2})(\\.?(\\w|%[0-9A-Fa-f]{2}))*(:[1-9]\\d{0,3}|\\*)?)(,((\\w|%[0-9A-Fa-f]{2})(\\.?(\\w|%[0-9A-Fa-f]{2}))*(:[1-9]\\d{0,3}|\\*)?))*\\})*'\n\n\nAPICURIO_SHARE_FOR_EVERYONE=false\nAPICURIO_UI_FEATURE_SHARE_WITH_EVERYONE=false\n"
    - can be corrected (or passed?) by using `'*'` value
  - Access `docker-compose-apicurio-studio-ui-1` on asked url with default port 8093 give an error in logs : `Failed to load URLs from http://127.0.0.1:8090/realms/apicurio/.well-known/openid-configuration` (complete stack trace at the end)
    - can be corrected by 
      - adding `/auth` to `APICURIO_KC_AUTH_URL`; (http://127.0.0.1:8090`/auth`/realms/apicurio/.well-known/openid-configuration can be accessed by my browser) ===> same error but this /auth path ...
      - changing the port to internal docker's Keykloak one ???  ===> no more stacktrace but nothing happen browsing 127.0.0.1:8093
      
I definitively can't pass the step `Failed to load URLs`. If someone could give me an answer or have a look to this, it would be great.

---
The complete stack trace
```java
docker-compose-apicurio-studio-ui-1    | 2022-07-25 12:35:01,590 WARN  [org.keycloak.adapters.KeycloakDeployment] (default task-1) Failed to load URLs from http://127.0.0.1:8090/realms/apicurio/.well-known/openid-configuration: java.net.ConnectException: Connection refused (Connection refused)
docker-compose-apicurio-studio-ui-1    |        at java.base/java.net.PlainSocketImpl.socketConnect(Native Method)
docker-compose-apicurio-studio-ui-1    |        at java.base/java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:412)
docker-compose-apicurio-studio-ui-1    |        at java.base/java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:255)
docker-compose-apicurio-studio-ui-1    |        at java.base/java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:237)
docker-compose-apicurio-studio-ui-1    |        at java.base/java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
docker-compose-apicurio-studio-ui-1    |        at java.base/java.net.Socket.connect(Socket.java:609)
docker-compose-apicurio-studio-ui-1    |        at org.apache.httpcomponents.core//org.apache.http.conn.scheme.PlainSocketFactory.connectSocket(PlainSocketFactory.java:121)
docker-compose-apicurio-studio-ui-1    |        at org.apache.httpcomponents.core//org.apache.http.impl.conn.DefaultClientConnectionOperator.openConnection(DefaultClientConnectionOperator.java:180)
docker-compose-apicurio-studio-ui-1    |        at org.apache.httpcomponents.core//org.apache.http.impl.conn.AbstractPoolEntry.open(AbstractPoolEntry.java:144)
docker-compose-apicurio-studio-ui-1    |        at org.apache.httpcomponents.core//org.apache.http.impl.conn.AbstractPooledConnAdapter.open(AbstractPooledConnAdapter.java:134)
docker-compose-apicurio-studio-ui-1    |        at org.apache.httpcomponents.core//org.apache.http.impl.client.DefaultRequestDirector.tryConnect(DefaultRequestDirector.java:610)
docker-compose-apicurio-studio-ui-1    |        at org.apache.httpcomponents.core//org.apache.http.impl.client.DefaultRequestDirector.execute(DefaultRequestDirector.java:445)
docker-compose-apicurio-studio-ui-1    |        at org.apache.httpcomponents.core//org.apache.http.impl.client.AbstractHttpClient.doExecute(AbstractHttpClient.java:835)
docker-compose-apicurio-studio-ui-1    |        at org.apache.httpcomponents.core//org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:83)
docker-compose-apicurio-studio-ui-1    |        at org.apache.httpcomponents.core//org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:108)
docker-compose-apicurio-studio-ui-1    |        at org.apache.httpcomponents.core//org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:56)
docker-compose-apicurio-studio-ui-1    |        at org.keycloak.keycloak-adapter-core@9.0.3//org.keycloak.adapters.KeycloakDeployment.getOidcConfiguration(KeycloakDeployment.java:219)
docker-compose-apicurio-studio-ui-1    |        at org.keycloak.keycloak-adapter-core@9.0.3//org.keycloak.adapters.KeycloakDeployment.resolveUrls(KeycloakDeployment.java:178)
docker-compose-apicurio-studio-ui-1    |        at org.keycloak.keycloak-adapter-core@9.0.3//org.keycloak.adapters.KeycloakDeployment.getAuthUrl(KeycloakDeployment.java:237)
docker-compose-apicurio-studio-ui-1    |        at org.keycloak.keycloak-adapter-core@9.0.3//org.keycloak.adapters.OAuthRequestAuthenticator.getRedirectUri(OAuthRequestAuthenticator.java:175)
docker-compose-apicurio-studio-ui-1    |        at org.keycloak.keycloak-adapter-core@9.0.3//org.keycloak.adapters.OAuthRequestAuthenticator.loginRedirect(OAuthRequestAuthenticator.java:213)
docker-compose-apicurio-studio-ui-1    |        at org.keycloak.keycloak-adapter-core@9.0.3//org.keycloak.adapters.OAuthRequestAuthenticator.authenticate(OAuthRequestAuthenticator.java:275)
docker-compose-apicurio-studio-ui-1    |        at org.keycloak.keycloak-adapter-core@9.0.3//org.keycloak.adapters.RequestAuthenticator.authenticate(RequestAuthenticator.java:138)
docker-compose-apicurio-studio-ui-1    |        at org.keycloak.keycloak-undertow-adapter@9.0.3//org.keycloak.adapters.undertow.AbstractUndertowKeycloakAuthMech.keycloakAuthenticate(AbstractUndertowKeycloakAuthMech.java:110)
docker-compose-apicurio-studio-ui-1    |        at org.keycloak.keycloak-undertow-adapter@9.0.3//org.keycloak.adapters.undertow.ServletKeycloakAuthMech.authenticate(ServletKeycloakAuthMech.java:92)
docker-compose-apicurio-studio-ui-1    |        at io.undertow.core@2.1.3.Final//io.undertow.security.impl.SecurityContextImpl$AuthAttempter.transition(SecurityContextImpl.java:245)
docker-compose-apicurio-studio-ui-1    |        at io.undertow.core@2.1.3.Final//io.undertow.security.impl.SecurityContextImpl$AuthAttempter.transition(SecurityContextImpl.java:268)
docker-compose-apicurio-studio-ui-1    |        at io.undertow.core@2.1.3.Final//io.undertow.security.impl.SecurityContextImpl$AuthAttempter.access$100(SecurityContextImpl.java:231)
docker-compose-apicurio-studio-ui-1    |        at io.undertow.core@2.1.3.Final//io.undertow.security.impl.SecurityContextImpl.attemptAuthentication(SecurityContextImpl.java:125)
docker-compose-apicurio-studio-ui-1    |        at io.undertow.core@2.1.3.Final//io.undertow.security.impl.SecurityContextImpl.authTransition(SecurityContextImpl.java:99)
docker-compose-apicurio-studio-ui-1    |        at io.undertow.core@2.1.3.Final//io.undertow.security.impl.SecurityContextImpl.authenticate(SecurityContextImpl.java:92)
docker-compose-apicurio-studio-ui-1    |        at io.undertow.servlet@2.1.3.Final//io.undertow.servlet.handlers.security.ServletAuthenticationCallHandler.handleRequest(ServletAuthenticationCallHandler.java:55)
docker-compose-apicurio-studio-ui-1    |        at io.undertow.core@2.1.3.Final//io.undertow.server.handlers.PredicateHandler.handleRequest(PredicateHandler.java:43)
docker-compose-apicurio-studio-ui-1    |        at io.undertow.core@2.1.3.Final//io.undertow.security.handlers.AuthenticationConstraintHandler.handleRequest(AuthenticationConstraintHandler.java:53)
docker-compose-apicurio-studio-ui-1    |        at io.undertow.core@2.1.3.Final//io.undertow.security.handlers.AbstractConfidentialityHandler.handleRequest(AbstractConfidentialityHandler.java:46)
docker-compose-apicurio-studio-ui-1    |        at io.undertow.servlet@2.1.3.Final//io.undertow.servlet.handlers.security.ServletConfidentialityConstraintHandler.handleRequest(ServletConfidentialityConstraintHandler.java:64)
docker-compose-apicurio-studio-ui-1    |        at io.undertow.servlet@2.1.3.Final//io.undertow.servlet.handlers.security.ServletSecurityConstraintHandler.handleRequest(ServletSecurityConstraintHandler.java:59)
docker-compose-apicurio-studio-ui-1    |        at io.undertow.core@2.1.3.Final//io.undertow.security.handlers.AuthenticationMechanismsHandler.handleRequest(AuthenticationMechanismsHandler.java:60)
docker-compose-apicurio-studio-ui-1    |        at io.undertow.servlet@2.1.3.Final//io.undertow.servlet.handlers.security.CachedAuthenticatedSessionHandler.handleRequest(CachedAuthenticatedSessionHandler.java:77)
docker-compose-apicurio-studio-ui-1    |        at io.undertow.core@2.1.3.Final//io.undertow.security.handlers.NotificationReceiverHandler.handleRequest(NotificationReceiverHandler.java:50)
docker-compose-apicurio-studio-ui-1    |        at io.undertow.core@2.1.3.Final//io.undertow.security.handlers.AbstractSecurityContextAssociationHandler.handleRequest(AbstractSecurityContextAssociationHandler.java:43)
docker-compose-apicurio-studio-ui-1    |        at io.undertow.core@2.1.3.Final//io.undertow.server.handlers.PredicateHandler.handleRequest(PredicateHandler.java:43)
docker-compose-apicurio-studio-ui-1    |        at org.wildfly.extension.undertow@18.0.1.Final//org.wildfly.extension.undertow.security.jacc.JACCContextIdHandler.handleRequest(JACCContextIdHandler.java:61)
docker-compose-apicurio-studio-ui-1    |        at io.undertow.core@2.1.3.Final//io.undertow.server.handlers.PredicateHandler.handleRequest(PredicateHandler.java:43)
docker-compose-apicurio-studio-ui-1    |        at org.wildfly.extension.undertow@18.0.1.Final//org.wildfly.extension.undertow.deployment.GlobalRequestControllerHandler.handleRequest(GlobalRequestControllerHandler.java:68)
docker-compose-apicurio-studio-ui-1    |        at org.keycloak.keycloak-undertow-adapter@9.0.3//org.keycloak.adapters.undertow.ServletPreAuthActionsHandler.handleRequest(ServletPreAuthActionsHandler.java:69)
docker-compose-apicurio-studio-ui-1    |        at io.undertow.core@2.1.3.Final//io.undertow.server.handlers.PredicateHandler.handleRequest(PredicateHandler.java:43)
docker-compose-apicurio-studio-ui-1    |        at io.undertow.servlet@2.1.3.Final//io.undertow.servlet.handlers.ServletInitialHandler.handleFirstRequest(ServletInitialHandler.java:269)
docker-compose-apicurio-studio-ui-1    |        at io.undertow.servlet@2.1.3.Final//io.undertow.servlet.handlers.ServletInitialHandler.access$100(ServletInitialHandler.java:78)
docker-compose-apicurio-studio-ui-1    |        at io.undertow.servlet@2.1.3.Final//io.undertow.servlet.handlers.ServletInitialHandler$2.call(ServletInitialHandler.java:133)
docker-compose-apicurio-studio-ui-1    |        at io.undertow.servlet@2.1.3.Final//io.undertow.servlet.handlers.ServletInitialHandler$2.call(ServletInitialHandler.java:130)
docker-compose-apicurio-studio-ui-1    |        at io.undertow.servlet@2.1.3.Final//io.undertow.servlet.core.ServletRequestContextThreadSetupAction$1.call(ServletRequestContextThreadSetupAction.java:48)
docker-compose-apicurio-studio-ui-1    |        at io.undertow.servlet@2.1.3.Final//io.undertow.servlet.core.ContextClassLoaderSetupAction$1.call(ContextClassLoaderSetupAction.java:43)
docker-compose-apicurio-studio-ui-1    |        at org.wildfly.extension.undertow@18.0.1.Final//org.wildfly.extension.undertow.security.SecurityContextThreadSetupAction.lambda$create$0(SecurityContextThreadSetupAction.java:105)
docker-compose-apicurio-studio-ui-1    |        at org.wildfly.extension.undertow@18.0.1.Final//org.wildfly.extension.undertow.deployment.UndertowDeploymentInfoService$UndertowThreadSetupAction.lambda$create$0(UndertowDeploymentInfoService.java:1504)
docker-compose-apicurio-studio-ui-1    |        at org.wildfly.extension.undertow@18.0.1.Final//org.wildfly.extension.undertow.deployment.UndertowDeploymentInfoService$UndertowThreadSetupAction.lambda$create$0(UndertowDeploymentInfoService.java:1504)
docker-compose-apicurio-studio-ui-1    |        at org.wildfly.extension.undertow@18.0.1.Final//org.wildfly.extension.undertow.deployment.UndertowDeploymentInfoService$UndertowThreadSetupAction.lambda$create$0(UndertowDeploymentInfoService.java:1504)
docker-compose-apicurio-studio-ui-1    |        at org.wildfly.swarm.keycloak:deployment@2.7.0.Final//org.wildfly.swarm.keycloak.deployment.KeycloakThreadSetupHandler.lambda$create$0(KeycloakThreadSetupHandler.java:35)
docker-compose-apicurio-studio-ui-1    |        at io.undertow.servlet@2.1.3.Final//io.undertow.servlet.handlers.ServletInitialHandler.dispatchRequest(ServletInitialHandler.java:249)
docker-compose-apicurio-studio-ui-1    |        at io.undertow.servlet@2.1.3.Final//io.undertow.servlet.handlers.ServletInitialHandler.access$000(ServletInitialHandler.java:78)
docker-compose-apicurio-studio-ui-1    |        at io.undertow.servlet@2.1.3.Final//io.undertow.servlet.handlers.ServletInitialHandler$1.handleRequest(ServletInitialHandler.java:99)
docker-compose-apicurio-studio-ui-1    |        at io.undertow.core@2.1.3.Final//io.undertow.server.Connectors.executeRootHandler(Connectors.java:370)
docker-compose-apicurio-studio-ui-1    |        at io.undertow.core@2.1.3.Final//io.undertow.server.HttpServerExchange$1.run(HttpServerExchange.java:830)
docker-compose-apicurio-studio-ui-1    |        at org.jboss.threads@2.3.3.Final//org.jboss.threads.ContextClassLoaderSavingRunnable.run(ContextClassLoaderSavingRunnable.java:35)
docker-compose-apicurio-studio-ui-1    |        at org.jboss.threads@2.3.3.Final//org.jboss.threads.EnhancedQueueExecutor.safeRun(EnhancedQueueExecutor.java:1982)
docker-compose-apicurio-studio-ui-1    |        at org.jboss.threads@2.3.3.Final//org.jboss.threads.EnhancedQueueExecutor$ThreadBody.doRunTask(EnhancedQueueExecutor.java:1486)
docker-compose-apicurio-studio-ui-1    |        at org.jboss.threads@2.3.3.Final//org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1377)
docker-compose-apicurio-studio-ui-1    |        at java.base/java.lang.Thread.run(Thread.java:829)
docker-compose-apicurio-studio-ui-1    | 
docker-compose-apicurio-studio-ui-1    | 2022-07-25 12:35:01,592 ERROR [io.undertow.request] (default task-1) UT005023: Exception handling request to /favicon.ico: java.lang.NullPointerException
docker-compose-apicurio-studio-ui-1    |        at org.keycloak.keycloak-adapter-core@9.0.3//org.keycloak.adapters.OAuthRequestAuthenticator.getRedirectUri(OAuthRequestAuthenticator.java:175)
docker-compose-apicurio-studio-ui-1    |        at org.keycloak.keycloak-adapter-core@9.0.3//org.keycloak.adapters.OAuthRequestAuthenticator.loginRedirect(OAuthRequestAuthenticator.java:213)
docker-compose-apicurio-studio-ui-1    |        at org.keycloak.keycloak-adapter-core@9.0.3//org.keycloak.adapters.OAuthRequestAuthenticator.authenticate(OAuthRequestAuthenticator.java:275)
docker-compose-apicurio-studio-ui-1    |        at org.keycloak.keycloak-adapter-core@9.0.3//org.keycloak.adapters.RequestAuthenticator.authenticate(RequestAuthenticator.java:138)
docker-compose-apicurio-studio-ui-1    |        at org.keycloak.keycloak-undertow-adapter@9.0.3//org.keycloak.adapters.undertow.AbstractUndertowKeycloakAuthMech.keycloakAuthenticate(AbstractUndertowKeycloakAuthMech.java:110)
docker-compose-apicurio-studio-ui-1    |        at org.keycloak.keycloak-undertow-adapter@9.0.3//org.keycloak.adapters.undertow.ServletKeycloakAuthMech.authenticate(ServletKeycloakAuthMech.java:92)
docker-compose-apicurio-studio-ui-1    |        at io.undertow.core@2.1.3.Final//io.undertow.security.impl.SecurityContextImpl$AuthAttempter.transition(SecurityContextImpl.java:245)
docker-compose-apicurio-studio-ui-1    |        at io.undertow.core@2.1.3.Final//io.undertow.security.impl.SecurityContextImpl$AuthAttempter.transition(SecurityContextImpl.java:268)
docker-compose-apicurio-studio-ui-1    |        at io.undertow.core@2.1.3.Final//io.undertow.security.impl.SecurityContextImpl$AuthAttempter.access$100(SecurityContextImpl.java:231)
docker-compose-apicurio-studio-ui-1    |        at io.undertow.core@2.1.3.Final//io.undertow.security.impl.SecurityContextImpl.attemptAuthentication(SecurityContextImpl.java:125)
docker-compose-apicurio-studio-ui-1    |        at io.undertow.core@2.1.3.Final//io.undertow.security.impl.SecurityContextImpl.authTransition(SecurityContextImpl.java:99)
docker-compose-apicurio-studio-ui-1    |        at io.undertow.core@2.1.3.Final//io.undertow.security.impl.SecurityContextImpl.authenticate(SecurityContextImpl.java:92)
docker-compose-apicurio-studio-ui-1    |        at io.undertow.servlet@2.1.3.Final//io.undertow.servlet.handlers.security.ServletAuthenticationCallHandler.handleRequest(ServletAuthenticationCallHandler.java:55)
docker-compose-apicurio-studio-ui-1    |        at io.undertow.core@2.1.3.Final//io.undertow.server.handlers.PredicateHandler.handleRequest(PredicateHandler.java:43)
docker-compose-apicurio-studio-ui-1    |        at io.undertow.core@2.1.3.Final//io.undertow.security.handlers.AuthenticationConstraintHandler.handleRequest(AuthenticationConstraintHandler.java:53)
docker-compose-apicurio-studio-ui-1    |        at io.undertow.core@2.1.3.Final//io.undertow.security.handlers.AbstractConfidentialityHandler.handleRequest(AbstractConfidentialityHandler.java:46)
docker-compose-apicurio-studio-ui-1    |        at io.undertow.servlet@2.1.3.Final//io.undertow.servlet.handlers.security.ServletConfidentialityConstraintHandler.handleRequest(ServletConfidentialityConstraintHandler.java:64)
docker-compose-apicurio-studio-ui-1    |        at io.undertow.servlet@2.1.3.Final//io.undertow.servlet.handlers.security.ServletSecurityConstraintHandler.handleRequest(ServletSecurityConstraintHandler.java:59)
docker-compose-apicurio-studio-ui-1    |        at io.undertow.core@2.1.3.Final//io.undertow.security.handlers.AuthenticationMechanismsHandler.handleRequest(AuthenticationMechanismsHandler.java:60)
docker-compose-apicurio-studio-ui-1    |        at io.undertow.servlet@2.1.3.Final//io.undertow.servlet.handlers.security.CachedAuthenticatedSessionHandler.handleRequest(CachedAuthenticatedSessionHandler.java:77)
docker-compose-apicurio-studio-ui-1    |        at io.undertow.core@2.1.3.Final//io.undertow.security.handlers.NotificationReceiverHandler.handleRequest(NotificationReceiverHandler.java:50)
docker-compose-apicurio-studio-ui-1    |        at io.undertow.core@2.1.3.Final//io.undertow.security.handlers.AbstractSecurityContextAssociationHandler.handleRequest(AbstractSecurityContextAssociationHandler.java:43)
docker-compose-apicurio-studio-ui-1    |        at io.undertow.core@2.1.3.Final//io.undertow.server.handlers.PredicateHandler.handleRequest(PredicateHandler.java:43)
docker-compose-apicurio-studio-ui-1    |        at org.wildfly.extension.undertow@18.0.1.Final//org.wildfly.extension.undertow.security.jacc.JACCContextIdHandler.handleRequest(JACCContextIdHandler.java:61)
docker-compose-apicurio-studio-ui-1    |        at io.undertow.core@2.1.3.Final//io.undertow.server.handlers.PredicateHandler.handleRequest(PredicateHandler.java:43)
docker-compose-apicurio-studio-ui-1    |        at org.wildfly.extension.undertow@18.0.1.Final//org.wildfly.extension.undertow.deployment.GlobalRequestControllerHandler.handleRequest(GlobalRequestControllerHandler.java:68)
docker-compose-apicurio-studio-ui-1    |        at org.keycloak.keycloak-undertow-adapter@9.0.3//org.keycloak.adapters.undertow.ServletPreAuthActionsHandler.handleRequest(ServletPreAuthActionsHandler.java:69)
docker-compose-apicurio-studio-ui-1    |        at io.undertow.core@2.1.3.Final//io.undertow.server.handlers.PredicateHandler.handleRequest(PredicateHandler.java:43)
docker-compose-apicurio-studio-ui-1    |        at io.undertow.servlet@2.1.3.Final//io.undertow.servlet.handlers.ServletInitialHandler.handleFirstRequest(ServletInitialHandler.java:269)
docker-compose-apicurio-studio-ui-1    |        at io.undertow.servlet@2.1.3.Final//io.undertow.servlet.handlers.ServletInitialHandler.access$100(ServletInitialHandler.java:78)
docker-compose-apicurio-studio-ui-1    |        at io.undertow.servlet@2.1.3.Final//io.undertow.servlet.handlers.ServletInitialHandler$2.call(ServletInitialHandler.java:133)
docker-compose-apicurio-studio-ui-1    |        at io.undertow.servlet@2.1.3.Final//io.undertow.servlet.handlers.ServletInitialHandler$2.call(ServletInitialHandler.java:130)
docker-compose-apicurio-studio-ui-1    |        at io.undertow.servlet@2.1.3.Final//io.undertow.servlet.core.ServletRequestContextThreadSetupAction$1.call(ServletRequestContextThreadSetupAction.java:48)
docker-compose-apicurio-studio-ui-1    |        at io.undertow.servlet@2.1.3.Final//io.undertow.servlet.core.ContextClassLoaderSetupAction$1.call(ContextClassLoaderSetupAction.java:43)
docker-compose-apicurio-studio-ui-1    |        at org.wildfly.extension.undertow@18.0.1.Final//org.wildfly.extension.undertow.security.SecurityContextThreadSetupAction.lambda$create$0(SecurityContextThreadSetupAction.java:105)
docker-compose-apicurio-studio-ui-1    |        at org.wildfly.extension.undertow@18.0.1.Final//org.wildfly.extension.undertow.deployment.UndertowDeploymentInfoService$UndertowThreadSetupAction.lambda$create$0(UndertowDeploymentInfoService.java:1504)
docker-compose-apicurio-studio-ui-1    |        at org.wildfly.extension.undertow@18.0.1.Final//org.wildfly.extension.undertow.deployment.UndertowDeploymentInfoService$UndertowThreadSetupAction.lambda$create$0(UndertowDeploymentInfoService.java:1504)
docker-compose-apicurio-studio-ui-1    |        at org.wildfly.extension.undertow@18.0.1.Final//org.wildfly.extension.undertow.deployment.UndertowDeploymentInfoService$UndertowThreadSetupAction.lambda$create$0(UndertowDeploymentInfoService.java:1504)
docker-compose-apicurio-studio-ui-1    |        at org.wildfly.swarm.keycloak:deployment@2.7.0.Final//org.wildfly.swarm.keycloak.deployment.KeycloakThreadSetupHandler.lambda$create$0(KeycloakThreadSetupHandler.java:35)
docker-compose-apicurio-studio-ui-1    |        at io.undertow.servlet@2.1.3.Final//io.undertow.servlet.handlers.ServletInitialHandler.dispatchRequest(ServletInitialHandler.java:249)
docker-compose-apicurio-studio-ui-1    |        at io.undertow.servlet@2.1.3.Final//io.undertow.servlet.handlers.ServletInitialHandler.access$000(ServletInitialHandler.java:78)
docker-compose-apicurio-studio-ui-1    |        at io.undertow.servlet@2.1.3.Final//io.undertow.servlet.handlers.ServletInitialHandler$1.handleRequest(ServletInitialHandler.java:99)
docker-compose-apicurio-studio-ui-1    |        at io.undertow.core@2.1.3.Final//io.undertow.server.Connectors.executeRootHandler(Connectors.java:370)
docker-compose-apicurio-studio-ui-1    |        at io.undertow.core@2.1.3.Final//io.undertow.server.HttpServerExchange$1.run(HttpServerExchange.java:830)
docker-compose-apicurio-studio-ui-1    |        at org.jboss.threads@2.3.3.Final//org.jboss.threads.ContextClassLoaderSavingRunnable.run(ContextClassLoaderSavingRunnable.java:35)
docker-compose-apicurio-studio-ui-1    |        at org.jboss.threads@2.3.3.Final//org.jboss.threads.EnhancedQueueExecutor.safeRun(EnhancedQueueExecutor.java:1982)
docker-compose-apicurio-studio-ui-1    |        at org.jboss.threads@2.3.3.Final//org.jboss.threads.EnhancedQueueExecutor$ThreadBody.doRunTask(EnhancedQueueExecutor.java:1486)
docker-compose-apicurio-studio-ui-1    |        at org.jboss.threads@2.3.3.Final//org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1377)
docker-compose-apicurio-studio-ui-1    |        at java.base/java.lang.Thread.run(Thread.java:829)
```

**Comment by EricWittmann** [comment]
@carlesarnal or @andreaTP - any bandwidth to take a look at this?

**Comment by andreaTP** [comment]
Hi @joyearnaud and sorry for the late reply!
I just tested the [quarkus distro docker-compose](https://github.com/Apicurio/apicurio-studio/tree/master/distro/quarkus/docker-compose) on my machine(a Mac) and everything works as expected.

Reading through your report I see that you are trying to use `127.0.0.1` as IP address, which is [not supported](https://github.com/Apicurio/apicurio-studio/tree/master/distro/quarkus/docker-compose#script-based-setup):

> Note: make sure you use the external IP address of your host here. `localhost` and `127.0.0.1` will not work.

can you try using an external IP address?

**Comment by andreaTP** [comment]
@joyearnaud have you been able to test the suggestion above?

I tentatively close this issue, feel free to re-open it or open a new one if you have any additional context that is not covered here.
