### ISSUE TITLE
Login exception

### ISSUE THREAD

**Issue by schtrym** [Apicurio/apicurio-studio#288]
I get an error after login screen.

Here is the stacktrace :

```
09:28:48,018 ERROR [org.keycloak.adapters.OAuthRequestAuthenticator] (default task-12) failed to turn code into token: java.net.ConnectException: Connection tim
ed out: connect
        at java.net.TwoStacksPlainSocketImpl.socketConnect(Native Method)
        at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:350)
        at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:206)
        at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:188)
```

I'm behind an entreprise proxy so I bet on a proxy configuration problem... But I don't know how to set up an httpproxy that can be used by keycloak client adapter.

I tried to add this in my `standalone-apicurio.xml` file
```
		<property name="http.proxyHost" value="localhost"/>
		<property name="http.proxyPort" value="3129"/>
		<property name="https.proxyHost" value="localhost"/>
		<property name="https.proxyPort" value="3129"/>
    </system-properties>
```

and to add 
```
set "JAVA_OPTS=%JAVA_OPTS% -Dhttp.proxyHost=localhost -Dhttp.proxyPort=3129 -Dhttps.proxyHost=localhost -Dhttps.proxyPort=3129" 
``` 

in the standalone.conf.bat

without success.

Any idea?

**Comment by EricWittmann** [comment]
I'm assuming you downloaded the quickstart and are hitting this problem?

**Comment by schtrym** [comment]
yes

**Comment by schtrym** [comment]
I got the following exception :

```
15:00:27,301 DEBUG [org.jboss.as.config] (MSC service thread 1-7) VM Arguments: -Dprogram.name=standalone.bat -Xms64M -Xmx512M -XX:MetaspaceSize=96M -XX:MaxMeta
spaceSize=256m -Djava.net.preferIPv4Stack=true -Djboss.modules.system.pkgs=org.jboss.byteman -Dhttp.proxyHost=localhost -Dhttp.proxyPort=3129 -Dhttps.proxyHost=
localhost -Dhttps.proxyPort=3129 -Dorg.jboss.boot.log.file=C:\dev\java\apicurio-studio-0.2.7.Final\standalone\log\server.log -Dlogging.configuration=file:C:\dev
\java\apicurio-studio-0.2.7.Final\standalone\configuration/logging.properties
15:00:28,134 ERROR [org.jboss.as.server] (Controller Boot Thread) WFLYSRV0055: Caught exception during boot: org.jboss.as.controller.persistence.ConfigurationPe
rsistenceException: WFLYCTL0085: Failed to parse configuration
        at org.jboss.as.controller.persistence.XmlConfigurationPersister.load(XmlConfigurationPersister.java:131)
        at org.jboss.as.server.ServerService.boot(ServerService.java:357)
        at org.jboss.as.controller.AbstractControllerService$1.run(AbstractControllerService.java:299)
        at java.lang.Thread.run(Thread.java:745)
Caused by: javax.xml.stream.XMLStreamException: Unknown secure-deployment tag proxy-url
        at org.keycloak.subsystem.adapter.extension.KeycloakSubsystemParser.readDeployment(KeycloakSubsystemParser.java:112)
        at org.keycloak.subsystem.adapter.extension.KeycloakSubsystemParser.readElement(KeycloakSubsystemParser.java:63)
        at org.keycloak.subsystem.adapter.extension.KeycloakSubsystemParser.readElement(KeycloakSubsystemParser.java:46)
        at org.jboss.staxmapper.XMLMapperImpl.processNested(XMLMapperImpl.java:110)
        at org.jboss.staxmapper.XMLExtendedStreamReaderImpl.handleAny(XMLExtendedStreamReaderImpl.java:69)
        at org.jboss.as.server.parsing.StandaloneXml_4.parseServerProfile(StandaloneXml_4.java:546)
        at org.jboss.as.server.parsing.StandaloneXml_4.readServerElement(StandaloneXml_4.java:242)
        at org.jboss.as.server.parsing.StandaloneXml_4.readElement(StandaloneXml_4.java:141)
        at org.jboss.as.server.parsing.StandaloneXml.readElement(StandaloneXml.java:103)
        at org.jboss.as.server.parsing.StandaloneXml.readElement(StandaloneXml.java:49)
        at org.jboss.staxmapper.XMLMapperImpl.processNested(XMLMapperImpl.java:110)
        at org.jboss.staxmapper.XMLMapperImpl.parseDocument(XMLMapperImpl.java:69)
        at org.jboss.as.controller.persistence.XmlConfigurationPersister.load(XmlConfigurationPersister.java:123)
        ... 3 more
```

**Comment by EricWittmann** [comment]
Darn! I'll have to ping the keycloak guys and see how to support a proxy in the keycloak client adapter.  I'll report back when I find something.

**Comment by EricWittmann** [comment]
It turns out that the `proxy-url` option is only available when configuring the app using *keycloak.json*.  There is an issue reported for this already:

https://issues.jboss.org/browse/KEYCLOAK-4662?_sscc=t

As the issue has been open for more than a year, I think the more prudent choice here is for me to switch to using *keycloak.json* in Apicurio.  :)

I'll try to do this asap, although I'll be travelling for conferences over the next couple of weeks.  Perhaps I can get it done this week though.  We'll see!

**Comment by schtrym** [comment]
Thanks for the feedback. 

The problem with the keycloak.json is that we have to "open" the war file to change it... Hope it will remain usable for apicurio users.

**Comment by EricWittmann** [comment]
I believe that the keycloak.json file allows (at least) environment variable substitutions.  I know this works when running in Wildfly Swarm, because I already do it here:

https://github.com/Apicurio/apicurio-studio/blob/master/platforms/swarm/ui/src/main/webapp/WEB-INF/keycloak.json

Not sure if it allows system property replacement as well (I would prefer that).  If variable substitution is NOT supported when running in Wildfly then I won't switch - because I agree that portability of the deployment binary (the WARs) is more important.

**Comment by schtrym** [comment]
OK. I wait for your feeback for the keycloak.json switch.

Thanks

**Comment by EricWittmann** [comment]
Sorry for the delay on this - I've been at a couple of conferences that are getting in the way of making progress.  This is still on my radar though.

**Comment by EricWittmann** [comment]
Update:  initial conversion from `standalone.xml` to `keycloak.json` looks good.  I've set up the `keycloak.json` file so that it can be configured via system properties.  That way the KC details can be configured either on the command line when starting up or (more likely) by setting system properties in the `standalone.xml` file.

I have a few more details to iron out but this is looking promising.

**Comment by EricWittmann** [comment]
Use system property `apicurio.kc.auth.proxyUrl` now to set the proxy url.  Otherwise everything will continue to act as per normal.

This change will be included in the next release, but you can test it now if you want by doing a local build using maven and getting the quickstart ZIP from:

`apicurio/apicurio-studio/distro/quickstart/target/apicurio-studio-0.2.11-SNAPSHOT-quickstart.zip`

I would definitely appreciate it (if possible) if you could give that a try!

**Comment by schtrym** [comment]
Sorry For the delay..

I just give it a try and it works like a charm.

```
    <system-properties>
        <property name="apicurio.kc.auth.rootUrl" value="https://studio-auth.apicur.io/auth"/>
        <property name="apicurio.kc.auth.realm" value="apicurio-local"/>
        <property name="apicurio.hub.storage.jdbc.type" value="h2"/>
        <property name="apicurio.hub.storage.jdbc.init" value="true"/>
        <property name="apicurio.kc.auth.proxyUrl" value="http://localhost:3129"/>
    </system-properties>
```

Thanks !

When is planned the next release?

**Comment by EricWittmann** [comment]
Great! 

Hopefully this week, assuming I can finish up a few items on the todo list.

**Comment by gigaga** [comment]
Hi,

From apicurio-studio-0.2.11.Final and "apicurio.kc.auth.proxyUrl" property, I have still the issue :(

```
<property name="apicurio.kc.auth.proxyUrl" value="http://localhost:3129"/>

10:29:15,785 ERROR [org.keycloak.adapters.OAuthRequestAuthenticator] (default task-6) failed to turn code into token: java.net.ConnectException: Connection timed out: connect
```
