### ISSUE TITLE
Apicurio Studio-Quickstart Not working

### ISSUE THREAD

**Issue by ManpreetGulati** [Apicurio/apicurio-studio#314]
I am getting the following error while setting up the studio through quickstart:

```
C:\Apicurio\Quickstart\apicurio-studio-0.2.10.Final>bin\standalone.sh -c apicurio-standalone.xml
```
```
C:\Apicurio\Quickstart\apicurio-studio-0.2.10.Final>bin\standalone.bat -c apicurio-standalone.xml
Calling "C:\Apicurio\Quickstart\apicurio-studio-0.2.10.Final\bin\standalone.conf.bat"
Setting JAVA property to "C:\Program Files\Java\jdk1.8.0_171\bin\java"
===============================================================================

  JBoss Bootstrap Environment

  JBOSS_HOME: "C:\Apicurio\Quickstart\apicurio-studio-0.2.10.Final"

  JAVA: "C:\Program Files\Java\jdk1.8.0_171\bin\java"

  JAVA_OPTS: "-Dprogram.name=standalone.bat -Xms64M -Xmx512M -XX:MetaspaceSize=96M -XX:MaxMetaspaceSize=256m -Djava.net.preferIPv4S
tack=true -Djboss.modules.system.pkgs=org.jboss.byteman"

===============================================================================

11:53:47,341 INFO  [org.jboss.modules] (main) JBoss Modules version 1.5.2.Final
java.lang.IllegalStateException: WFLYCTL0214: Could not get main file: apicurio-standalone.xml. Specified files must be relative to
 the configuration dir: C:\Apicurio\Quickstart\apicurio-studio-0.2.10.Final\standalone\configuration
        at org.jboss.as.controller.persistence.ConfigurationFile.determineMainFile(ConfigurationFile.java:312)
        at org.jboss.as.controller.persistence.ConfigurationFile.<init>(ConfigurationFile.java:173)
        at org.jboss.as.server.ServerEnvironment.<init>(ServerEnvironment.java:456)
        at org.jboss.as.server.Main.determineEnvironment(Main.java:297)
        at org.jboss.as.server.Main.main(Main.java:94)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.jboss.modules.Module.run(Module.java:330)
        at org.jboss.modules.Main.main(Main.java:505)
11:53:47,945 FATAL [org.jboss.as.server] (main) WFLYSRV0239: Aborting with exit code 1
Press any key to continue . . .
```

It doesnt seem to be an environment issue. Running "bin\standalone.sh -c apicurio-standalone.xml" inside apicurio-studio-0.2.10.Final folder just fails without any logs. 

By running "bin\standalone.bat -c apicurio-standalone.xml" inside apicurio-studio-0.2.10.Final I got the above mentioned error.

**Comment by EricWittmann** [comment]
The configuration file is named `standalone-apicurio.xml` rather than `apicurio-standalone.xml`.  I checked the docs and it seems to be correct there, but it might have been wrong in an earlier version.   Apologies if that is the case.

In other words, try this:

```
C:\Apicurio\Quickstart\apicurio-studio-0.2.10.Final>bin\standalone.sh -c standalone-apicurio.xml
```

**Comment by EricWittmann** [comment]
Whoops - didn't mean to close this until I got confirmation that this was the problem.  :)
