### ISSUE TITLE
Unable to use my own KeyCloak v3.4.4

### ISSUE THREAD

**Issue by Devin-Grant** [Apicurio/apicurio-studio#342]
The steps in your documentation are out-dated.  I've tried to use the simple Apicurio realm file, but the login screen throws a 400 error (Bad Request) after I register and login.

KeyCloak v3.4.4
22:10:57,975 ERROR [org.keycloak.adapters.OAuthRequestAuthenticator] (default task-11) failed to turn code into token: java.net.ConnectException: Connection refused (Connection refused)
	at java.net.PlainSocketImpl.socketConnect(Native Method)
	at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:350)
	at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:206)
	at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:188)
	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
	at java.net.Socket.connect(Socket.java:589)
...
22:11:07,859 WARN  [org.keycloak.adapters.OAuthRequestAuthenticator] (default task-12) No state cookie

Note: using the default "https://studio-auth.apicur.io/auth" works.

**Comment by EricWittmann** [comment]
What version of Keycloak are you using?

**Comment by EricWittmann** [comment]
Nevermind, you put it right there in the issue title!  :)

**Comment by EricWittmann** [comment]
I just tried the **Setting up Keycloak for use with Apicurio** instructions in the Apicurio documentation, and you are right - the instructions are out of date.  However, the process is even easier now (which is nice).  I'll update the instructions (which only involves removing a step).

**Comment by EricWittmann** [comment]
I've also had some requests to document configuring Keycloak so that Account Linking works.  I'll do that today as well. :)

**Comment by Devin-Grant** [comment]
Are you able to use Docker to run KeyCloak, Postgres, and Apicurio?

docker network create apicurio-network 

docker container run -d \
    --name apicurio-postgres \
    --network apicurio-network \
    -p 5432:5432 \
    -e "POSTGRES_DB=apicurio" \
    -e "POSTGRES_USER=root" \
    -e "POSTGRES_PASSWORD=root" \
    postgres:9.6.3

    docker run --name keycloak \
        -p 8888:8080 \
        -e DB_VENDOR=postgres \
        -e DB_ADDR=keycloak-postgres \
        -e DB_USER=root \
        -e DB_PASSWORD=root \
        -e KEYCLOAK_USER=root \
        -e KEYCLOAK_PASSWORD=root \
        --net apicurio-network \
        jboss/keycloak:3.4.3.Final

docker run --rm -it \
    --name apicurio \
    -p 8080:8080 \
    --network apicurio-network \
    apicurio/apicurio-studio

Btw, any plans to support KeyCloak v4.x.x?

**Comment by Devin-Grant** [comment]
Here my Docker file to build Apicurio...
FROM centos:7
RUN yum install -y \
    java-1.8.0-openjdk-headless \
    unzip \
    && yum clean all

WORKDIR /opt/apicurio-studio

ENV RELEASE_VERSION 0.2.12
ENV RELEASE_PATH https://github.com/Apicurio/apicurio-studio/releases/download/v$RELEASE_VERSION.Final/apicurio-studio-$RELEASE_VERSION.Final-quickstart.zip

ADD $RELEASE_PATH /opt/apicurio-studio

RUN groupadd -r apicurio -g 1001 \
    && useradd -u 1001 -r -g apicurio -d /opt/apicurio-studio/ -s /sbin/nologin -c "Docker image user" apicurio \
    && chown -R apicurio:apicurio /opt/apicurio-studio/

USER 1001
RUN unzip apicurio-studio-${RELEASE_VERSION}.Final-quickstart.zip; \
    rm apicurio-studio-${RELEASE_VERSION}.Final-quickstart.zip; \
    mv -v apicurio-studio-${RELEASE_VERSION}.Final/* ./; \
    rm -r apicurio-studio-${RELEASE_VERSION}.Final/; \
    find /opt/ -name '*'; \
    chmod 755 ./bin/standalone.sh;

COPY ./standalone-apicurio.xml ./standalone/configuration/
COPY ./postgresql-9.4-1202.jdbc42.jar ./standalone/deployments/

EXPOSE 8080

ENTRYPOINT ["./bin/standalone.sh"]
CMD ["-c", "standalone-apicurio.xml", "-b", "0.0.0.0"]

**Comment by EricWittmann** [comment]
I am testing Keycloak 4 right now (that's actually the version I used to check the documentation) and it seems to work fine.  I haven't configured account linking yet (that takes some time because there are a bunch of steps in both Keycloak **and** in e.g. GitHub) but am working on that now.

The one thing that will definitely not work for KC 4 is the Apicurio login theme.  I'll update that once I confirm everything else is working.

I haven't been testing with docker.  I've just been running Keycloak and Apicurio on the same local machine using the Wildfly port offset feature.  I think running in docker might introduce a new challenge with regard to routing.  I'm not enough of a docker expert (or even user, tbh) to know for sure.  But once I'm done documenting account linking I'll fire up my centos box and attempt your docker approach and we'll see how it goes.

Question: how are you updating `standalone-apicurio.xml` to point to the docker keycloak instance?  I assume it's the `COPY ./standalone-apicurio.xml ./standalone/configuration/` line in the Dockerfile?  You have a locally modified `standalone-apicurio.xml` file in the same location as this Dockerfile?

**Comment by Devin-Grant** [comment]
That is correct, I am manually modifying the `standalone-apicurio.xml` which resides in the same directory as the docker file.

Here is an example of how I am building the container...

docker rmi -f base/apicurio-studio 2> /dev/null
docker build -t="apicurio/apicurio-studio" --file apicurio.dockerfile  --rm .

**Comment by EricWittmann** [comment]
OK cool thanks.  Will try to look into this today.

**Comment by EricWittmann** [comment]
OK everything seems to work with KC 4.1.0.  Here is the (in progress) updated documentation:

https://apicurio-studio.readme.io/docs/setting-up-keycloak-for-use-with-apicurio

I'm going to work on your docker stuff a bit and see what sorts of problems I run into there.  I do think we can probably improve the docker experience by using ENV properties in the Dockerfile rather than copying in a locally edited standalone.xml file - but we'll see!

**Comment by EricWittmann** [comment]
OK @Devin-Grant - I immediately see the big problem with this single-host docker approach.  The issue is that the final step of authentication is for the application (apicurio in this case) to validate the auth token.  To do this, the app (apicurio) needs to make an HTTP call directly to Keycloak.  As I understand it, login goes like this:

1) Browser attempts to access Apicurio.  Keycloak client adapter (running in Apicurio) redirects to Keycloak
2) Browser loads the Keycloak login page
3) User logs in using the login form
4) Keycloak authenticates the user and redirects the browser back to Apicurio
5) Browser attempts to access Apicurio again, this time with an auth token
6) Apicurio (server) validates the token by making an HTTP call to Keycloak
7) Apicurio is loaded in the browser - success!

Everything is likely working for you except step (6) because the Apicurio server can't make a successful HTTP call to the Keycloak server (they are running in different docker images).

So that's the routing problem that must be solved.  Even with both docker images on the same docker network, I don't think Apicurio can invoke Keycloak directly.  Perhaps you can confirm.

See this stackoverflow question:

https://stackoverflow.com/questions/45263225/keycloak-authorizations-in-docker-network-bridge-mode-how-to-access-localhost

At this point I'm out of my depth with respect to docker.

Thoughts?  I could easily be wrong. :)

**Comment by Devin-Grant** [comment]
I will investigate this issue further.

Thanks!

**Comment by EricWittmann** [comment]
I think if you're using e.g. Kubernetes/OpenShift then maybe this problem is more manageable.  But I'm speaking outside my area of expertise. :)

Let me know if there's something I can chagne/improve/add to help with this.  Happy to do so.

**Comment by Devin-Grant** [comment]
Is there a way to disable authentication?

**Comment by Devin-Grant** [comment]
No, I haven't found a solution to Keycloak + docker yet, still working on it.

**Comment by Devin-Grant** [comment]
The reason why I ask is that we are going to use our own authentication through AWS where I am planning to host Apicurio using ECS Fargate.

**Comment by Devin-Grant** [comment]
btw, I am getting following error when using https://studio-auth.apicur.io/auth...

We're sorry...
Invalid parameter: redirect_uri
« Back to Application

**Comment by EricWittmann** [comment]
Yeah I was trying to pull another community user into the discussion (Dan Mikita) with that comment above ("did you ever solve...").  Dan and his team were working with Keycloak and Apicurio using containers and I'm wondering if they ever got that working and can give us some guidance. :)

As for authentication through AWS - I've not done that before, and any attempt to replace Keycloak with some other authentication scheme will require some code changes to Apicurio.  That said, I'm not at all against that - just be aware that there's no way to simply drop in a different Auth mechanism/impl at this time.

I'm happy to assist with that effort by providing pointers to relevant locations with the Apicurio codebase if you wish to take on this task!

**Comment by Devin-Grant** [comment]
I am unable to get it working with KeyCloak v4.1.0 and Apicurio v0.2.12.final outside a Docker container when following your steps 

see the KeyCloak [error.log](https://github.com/Apicurio/apicurio-studio/files/2247315/error.log)

**Comment by Devin-Grant** [comment]
Btw, I can reproduce this issue in a clean macOS virtual machine (VMware Fusion).

**Comment by EricWittmann** [comment]
I've updated the documentation with this tidbit.  Apologies for the inconvenience.

**Comment by Devin-Grant** [comment]
Ah, finally it's working...Thanks!

I am now going to look into the Docker container networking.

**Comment by EricWittmann** [comment]
I'd be super excited if you found a solution to that!  Best of luck. 👍
