### ISSUE TITLE
Issue with Account Linking.

### ISSUE THREAD

**Issue by SarvaniVarma** [Apicurio/apicurio-studio#358]
Not able to link Github and GitLab accounts.
Followed this link:
https://apicurio-studio.readme.io/docs/setting-up-keycloak-for-use-with-apicurio
When tried to link with Github, I get the following :
![accountlink](https://user-images.githubusercontent.com/41433069/43260537-72b36476-90f7-11e8-932b-dfaceecbc41a.png)

When clicked back to accounts page, It is still initiating the account:
![acclink](https://user-images.githubusercontent.com/41433069/43260594-9382f932-90f7-11e8-818c-cf5fcd67bc6a.png)

Server Logs:

```
16:54:18,360 DEBUG [io.apicurio.hub.api.rest.impl.AccountsResource] (default task-1) Creating a linked GitHub account for user mehboob
16:54:18,360 DEBUG [io.apicurio.hub.core.storage.jdbc.JdbcStorage] (default task-1) Inserting a Linked Account GitHub for mehboob
16:54:18,361 DEBUG [io.apicurio.hub.api.rest.impl.AccountsResource] (default task-1) Linked Account created in DB.
16:54:18,361 DEBUG [io.apicurio.studio.shared.config.Configuration] (default task-1) Config Property: APICURIO_KC_AUTH_URL/apicurio.kc.auth.rootUrl = http://localhost:8080/auth
16:54:18,361 DEBUG [io.apicurio.studio.shared.config.Configuration] (default task-1) Config Property: APICURIO_KC_AUTH_REALM/apicurio.kc.auth.realm = apicurio
16:54:18,361 DEBUG [io.apicurio.hub.api.security.KeycloakLinkedAccountsProvider] (default task-1) Account Link URL: http://localhot:8080/auth/realms/apicurio/broker/github/link?nonce=9d385265-e583-460b-aadd-e8e372a8b52f&hash=rZATmiO5Ugrk4lpoO6xgxOjeLfYUi9WZq9pek_h0K8U&client_id=apicurio-studio&redirect_uri=http%3A%2F%2F10.175.129.125%3A8080%2Fstudio%2Fsettings%2Faccounts%2FGitHub%2Fcreated
16:54:18,361 DEBUG [io.apicurio.hub.api.rest.impl.AccountsResource] (default task-1) Sending browser redirect URL: http://localhost:8080/auth/realms/apicurio/broker/github/link?nonce=9d385265-e583-460b-aadd-e8e372a8b52f&hash=rZATmiO5Ugrk4lpoO6xgxOjeLfYUi9WZq9pek_h0K8U&client_id=apicurio-studio&redirect_uri=http%3A%2F%2F10.175.129.125%3A8080%2Fstudio%2Fsettings%2Faccounts%2FGitHub%2Fcreated
16:54:47,178 DEBUG [io.apicurio.studio.shared.config.Configuration] (default task-7) Config Property: APICURIO_UI_HUB_API_URL/apicurio-ui.hub-api.url = null
16:54:47,178 DEBUG [io.apicurio.studio.shared.config.Configuration] (default task-7) Config Property: APICURIO_UI_EDITING_URL/apicurio-ui.editing.url = null
16:57:27,674 DEBUG [io.apicurio.hub.api.rest.impl.AccountsResource] (default task-16) Listing Linked Accounts for mehboob
16:57:27,675 DEBUG [io.apicurio.hub.core.storage.jdbc.JdbcStorage] (default task-16) Getting a list of all Linked Accouts for mehboob.
```

And also, I am not able to Import APIs from URL and Source Code.

**Comment by EricWittmann** [comment]
So am I right in assuming that you are running your own Keycloak server locally and have configured it according to the documentation?  And you're running Apicurio locally as well, configured to point to the local Keycloak?  Any other configuration details about your setup could be helpful.

One thing that stands out in the log above is the line starting with **Link URL:** seems to have a URL with domain **localhot** instead of **localhost**.  Perhaps re-check all your settings just to confirm there are no typos?

**Comment by EricWittmann** [comment]
You can also check the status of the **Identity Provider Link** for your user in the Keycloak console.  Login to Keycloak, then choose **Users** under "Manage" on the left-hand navigation.  Then use the search to lookup your user (or click *View All Users* if you don't have many).  Once you find your user, click on it and choose the **Identity Provider Links** tab.  If there is a link for GitHub you could try deleting it and trying the entire process over again.

**Comment by EricWittmann** [comment]
My other question would be:  what errors do you see when you try to Import your API?

**Comment by SarvaniVarma** [comment]
I have linked it with github, but now I am not able to publish to Github:
When I publish the apis I won't get any organisations in github account 

Server Logs:
17:34:27,316 DEBUG [io.apicurio.hub.api.github.GitHubSourceConnector] (default task-34) Getting organizations for current user.
17:34:27,316 DEBUG [io.apicurio.studio.shared.config.Configuration] (default task-34) Config Property: APICURIO_KC_AUTH_URL/apicurio.kc.auth.rootUrl = http://10.125.194.128:8080/auth
17:34:27,317 DEBUG [io.apicurio.studio.shared.config.Configuration] (default task-34) Config Property: APICURIO_KC_AUTH_REALM/apicurio.kc.auth.realm = apicurio
17:34:27,669 ERROR [io.apicurio.hub.api.security.KeycloakLinkedAccountsProvider] (default task-34) Failed to access External IDP Access Token from Keycloak: 400 - Bad Request


I am also not able to link GtiLab account:
After clicking on authorise, the page keeps loading 
![screenshot from 2018-07-26 17-38-03](https://user-images.githubusercontent.com/41433069/43261794-93129cba-90fb-11e8-9602-a5e624858e6f.png)


Server Logs:

17:36:47,017 DEBUG [io.apicurio.hub.api.rest.impl.AccountsResource] (default task-35) Listing Linked Accounts for sarvani
17:36:47,017 DEBUG [io.apicurio.hub.core.storage.jdbc.JdbcStorage] (default task-35) Getting a list of all Linked Accouts for sarvani.
17:37:26,343 DEBUG [io.apicurio.hub.api.rest.impl.AccountsResource] (default task-37) Creating a linked GitLab account for user sarvani
17:37:26,343 DEBUG [io.apicurio.hub.core.storage.jdbc.JdbcStorage] (default task-37) Inserting a Linked Account GitLab for sarvani
17:37:26,343 DEBUG [io.apicurio.hub.api.rest.impl.AccountsResource] (default task-37) Linked Account created in DB.
17:37:26,344 DEBUG [io.apicurio.studio.shared.config.Configuration] (default task-37) Config Property: APICURIO_KC_AUTH_URL/apicurio.kc.auth.rootUrl = http:/10.125.194.128:8080/auth
17:37:26,348 DEBUG [io.apicurio.studio.shared.config.Configuration] (default task-37) Config Property: APICURIO_KC_AUTH_REALM/apicurio.kc.auth.realm = apicurio
17:37:26,348 DEBUG [io.apicurio.hub.api.security.KeycloakLinkedAccountsProvider] (default task-37) Account Link URL: http://10.125.194.128:8080/auth/realms/apicurio/broker/gitlab/link?nonce=fa3b7fe6-ad9e-4da7-8d62-1d56fe1747aa&hash=HlSLnv5v59HWFo9Kn0zHH4wumz5jsWSILITPU15451E&client_id=apicurio-studio&redirect_uri=http%3A%2F%2F10.125.176.50%3A8080%2Fstudio%2Fsettings%2Faccounts%2FGitLab%2Fcreated
17:37:26,348 DEBUG [io.apicurio.hub.api.rest.impl.AccountsResource] (default task-37) Sending browser redirect URL: http://10.125.194.128:8080/auth/realms/apicurio/broker/gitlab/link?nonce=fa3b7fe6-ad9e-4da7-8d62-1d56fe1747aa&hash=HlSLnv5v59HWFo9Kn0zHH4wumz5jsWSILITPU15451E&client_id=apicurio-studio&redirect_uri=http%3A%2F%2F10.125.176.50%3A8080%2Fstudio%2Fsettings%2Faccounts%2FGitLab%2Fcreated


For Importing from source code I get the following error:
![screenshot from 2018-07-26 17-03-32](https://user-images.githubusercontent.com/41433069/43262756-e4c745d0-90fe-11e8-8057-1e4a6cf5ff74.png)

Server log:

18:01:13,763 DEBUG [io.apicurio.hub.api.rest.impl.DesignsResource] (default task-3) Importing an API Design: https://github.com/SarvaniVarma/test/blob/master/apicurio.json
18:01:13,763 DEBUG [io.apicurio.hub.api.github.GitHubSourceConnector] (default task-3) Validating the existence of resource https://github.com/SarvaniVarma/test/blob/master/apicurio.json
18:01:13,764 DEBUG [io.apicurio.studio.shared.config.Configuration] (default task-3) Config Property: APICURIO_KC_AUTH_URL/apicurio.kc.auth.rootUrl = http://10.129.211.129:8080/auth
18:01:13,765 DEBUG [io.apicurio.studio.shared.config.Configuration] (default task-3) Config Property: APICURIO_KC_AUTH_REALM/apicurio.kc.auth.realm = apicurio
18:01:14,118 ERROR [io.apicurio.hub.api.security.KeycloakLinkedAccountsProvider] (default task-3) Failed to access External IDP Access Token from Keycloak: 403 - Forbidden

**Comment by EricWittmann** [comment]
Can you copy/paste the entire contents of that **Server Error Details** (stack trace) from that error page (your screenshot above)?  That should hopefully have something helpful in it.

**Comment by SarvaniVarma** [comment]
Server Error Details:

io.apicurio.hub.core.exceptions.ServerError: Unexpected server error
	at io.apicurio.hub.api.rest.impl.DesignsResource.importDesignFromSource(DesignsResource.java:223)
	at io.apicurio.hub.api.rest.impl.DesignsResource.importDesign(DesignsResource.java:174)
	at io.apicurio.hub.api.rest.impl.DesignsResource$Proxy$_$$_WeldClientProxy.importDesign(Unknown Source)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.jboss.resteasy.core.MethodInjectorImpl.invoke(MethodInjectorImpl.java:139)
	at org.jboss.resteasy.core.ResourceMethodInvoker.invokeOnTarget(ResourceMethodInvoker.java:295)
	at org.jboss.resteasy.core.ResourceMethodInvoker.invoke(ResourceMethodInvoker.java:249)
	at org.jboss.resteasy.core.ResourceMethodInvoker.invoke(ResourceMethodInvoker.java:236)
	at org.jboss.resteasy.core.SynchronousDispatcher.invoke(SynchronousDispatcher.java:402)
	at org.jboss.resteasy.core.SynchronousDispatcher.invoke(SynchronousDispatcher.java:209)
	at org.jboss.resteasy.plugins.server.servlet.ServletContainerDispatcher.service(ServletContainerDispatcher.java:221)
	at org.jboss.resteasy.plugins.server.servlet.HttpServletDispatcher.service(HttpServletDispatcher.java:56)
	at org.jboss.resteasy.plugins.server.servlet.HttpServletDispatcher.service(HttpServletDispatcher.java:51)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:790)
	at io.undertow.servlet.handlers.ServletHandler.handleRequest(ServletHandler.java:85)
	at io.undertow.servlet.handlers.FilterHandler$FilterChainImpl.doFilter(FilterHandler.java:129)
	at io.apicurio.hub.api.security.KeycloakAuthenticationFilter.doFilter(KeycloakAuthenticationFilter.java:72)
	at io.undertow.servlet.core.ManagedFilter.doFilter(ManagedFilter.java:61)
	at io.undertow.servlet.handlers.FilterHandler$FilterChainImpl.doFilter(FilterHandler.java:131)
	at io.apicurio.hub.api.filters.DisableCachingFilter.doFilter(DisableCachingFilter.java:66)
	at io.undertow.servlet.core.ManagedFilter.doFilter(ManagedFilter.java:61)
	at io.undertow.servlet.handlers.FilterHandler$FilterChainImpl.doFilter(FilterHandler.java:131)
	at io.apicurio.hub.api.filters.CorsFilter.doFilter(CorsFilter.java:64)
	at io.undertow.servlet.core.ManagedFilter.doFilter(ManagedFilter.java:61)
	at io.undertow.servlet.handlers.FilterHandler$FilterChainImpl.doFilter(FilterHandler.java:131)
	at io.undertow.servlet.handlers.FilterHandler.handleRequest(FilterHandler.java:84)
	at io.undertow.servlet.handlers.security.ServletSecurityRoleHandler.handleRequest(ServletSecurityRoleHandler.java:62)
	at io.undertow.servlet.handlers.ServletDispatchingHandler.handleRequest(ServletDispatchingHandler.java:36)
	at org.wildfly.extension.undertow.security.SecurityContextAssociationHandler.handleRequest(SecurityContextAssociationHandler.java:78)
	at io.undertow.server.handlers.PredicateHandler.handleRequest(PredicateHandler.java:43)
	at org.keycloak.adapters.undertow.UndertowAuthenticatedActionsHandler.handleRequest(UndertowAuthenticatedActionsHandler.java:66)
	at io.undertow.servlet.handlers.security.SSLInformationAssociationHandler.handleRequest(SSLInformationAssociationHandler.java:131)
	at io.undertow.servlet.handlers.security.ServletAuthenticationCallHandler.handleRequest(ServletAuthenticationCallHandler.java:57)
	at io.undertow.server.handlers.DisableCacheHandler.handleRequest(DisableCacheHandler.java:33)
	at io.undertow.server.handlers.PredicateHandler.handleRequest(PredicateHandler.java:43)
	at io.undertow.security.handlers.AuthenticationConstraintHandler.handleRequest(AuthenticationConstraintHandler.java:53)
	at io.undertow.security.handlers.AbstractConfidentialityHandler.handleRequest(AbstractConfidentialityHandler.java:46)
	at io.undertow.servlet.handlers.security.ServletConfidentialityConstraintHandler.handleRequest(ServletConfidentialityConstraintHandler.java:64)
	at io.undertow.servlet.handlers.security.ServletSecurityConstraintHandler.handleRequest(ServletSecurityConstraintHandler.java:59)
	at io.undertow.security.handlers.AuthenticationMechanismsHandler.handleRequest(AuthenticationMechanismsHandler.java:60)
	at io.undertow.servlet.handlers.security.CachedAuthenticatedSessionHandler.handleRequest(CachedAuthenticatedSessionHandler.java:77)
	at io.undertow.security.handlers.NotificationReceiverHandler.handleRequest(NotificationReceiverHandler.java:50)
	at io.undertow.security.handlers.AbstractSecurityContextAssociationHandler.handleRequest(AbstractSecurityContextAssociationHandler.java:43)
	at io.undertow.server.handlers.PredicateHandler.handleRequest(PredicateHandler.java:43)
	at org.wildfly.extension.undertow.security.jacc.JACCContextIdHandler.handleRequest(JACCContextIdHandler.java:61)
	at io.undertow.server.handlers.PredicateHandler.handleRequest(PredicateHandler.java:43)
	at org.keycloak.adapters.undertow.ServletPreAuthActionsHandler.handleRequest(ServletPreAuthActionsHandler.java:69)
	at io.undertow.server.handlers.PredicateHandler.handleRequest(PredicateHandler.java:43)
	at io.undertow.servlet.handlers.ServletInitialHandler.handleFirstRequest(ServletInitialHandler.java:292)
	at io.undertow.servlet.handlers.ServletInitialHandler.access$100(ServletInitialHandler.java:81)
	at io.undertow.servlet.handlers.ServletInitialHandler$2.call(ServletInitialHandler.java:138)
	at io.undertow.servlet.handlers.ServletInitialHandler$2.call(ServletInitialHandler.java:135)
	at io.undertow.servlet.core.ServletRequestContextThreadSetupAction$1.call(ServletRequestContextThreadSetupAction.java:48)
	at io.undertow.servlet.core.ContextClassLoaderSetupAction$1.call(ContextClassLoaderSetupAction.java:43)
	at io.undertow.servlet.api.LegacyThreadSetupActionWrapper$1.call(LegacyThreadSetupActionWrapper.java:44)
	at io.undertow.servlet.api.LegacyThreadSetupActionWrapper$1.call(LegacyThreadSetupActionWrapper.java:44)
	at io.undertow.servlet.api.LegacyThreadSetupActionWrapper$1.call(LegacyThreadSetupActionWrapper.java:44)
	at io.undertow.servlet.api.LegacyThreadSetupActionWrapper$1.call(LegacyThreadSetupActionWrapper.java:44)
	at io.undertow.servlet.api.LegacyThreadSetupActionWrapper$1.call(LegacyThreadSetupActionWrapper.java:44)
	at io.undertow.servlet.handlers.ServletInitialHandler.dispatchRequest(ServletInitialHandler.java:272)
	at io.undertow.servlet.handlers.ServletInitialHandler.access$000(ServletInitialHandler.java:81)
	at io.undertow.servlet.handlers.ServletInitialHandler$1.handleRequest(ServletInitialHandler.java:104)
	at io.undertow.server.Connectors.executeRootHandler(Connectors.java:202)
	at io.undertow.server.HttpServerExchange$1.run(HttpServerExchange.java:805)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: io.apicurio.hub.api.connectors.SourceConnectorException: Error checking that a GitHub resource exists.
	at io.apicurio.hub.api.github.GitHubSourceConnector.validateResourceExists(GitHubSourceConnector.java:143)
	at io.apicurio.hub.api.github.GitHubSourceConnector$Proxy$_$$_WeldClientProxy.validateResourceExists(Unknown Source)
	at io.apicurio.hub.api.rest.impl.DesignsResource.importDesignFromSource(DesignsResource.java:191)
	... 69 more
Caused by: io.apicurio.hub.api.connectors.SourceConnectorException: Error getting Github resource content.
	at io.apicurio.hub.api.github.GitHubSourceConnector.getResourceContent(GitHubSourceConnector.java:183)
	at io.apicurio.hub.api.github.GitHubSourceConnector.validateResourceExists(GitHubSourceConnector.java:131)
	... 71 more
Caused by: com.mashape.unirest.http.exceptions.UnirestException: java.net.UnknownHostException: api.github.com
	at com.mashape.unirest.http.HttpClientHelper.request(HttpClientHelper.java:143)
	at com.mashape.unirest.request.BaseRequest.asObject(BaseRequest.java:80)
	at io.apicurio.hub.api.github.GitHubSourceConnector.getResourceContent(GitHubSourceConnector.java:167)
	... 72 more
Caused by: java.net.UnknownHostException: api.github.com
	at java.net.InetAddress.getAllByName0(InetAddress.java:1280)
	at java.net.InetAddress.getAllByName(InetAddress.java:1192)
	at java.net.InetAddress.getAllByName(InetAddress.java:1126)
	at org.apache.http.impl.conn.SystemDefaultDnsResolver.resolve(SystemDefaultDnsResolver.java:45)
	at org.apache.http.impl.conn.DefaultHttpClientConnectionOperator.connect(DefaultHttpClientConnectionOperator.java:112)
	at org.apache.http.impl.conn.PoolingHttpClientConnectionManager.connect(PoolingHttpClientConnectionManager.java:359)
	at org.apache.http.impl.execchain.MainClientExec.establishRoute(MainClientExec.java:381)
	at org.apache.http.impl.execchain.MainClientExec.execute(MainClientExec.java:237)
	at org.apache.http.impl.execchain.ProtocolExec.execute(ProtocolExec.java:185)
	at org.apache.http.impl.execchain.RetryExec.execute(RetryExec.java:89)
	at org.apache.http.impl.execchain.RedirectExec.execute(RedirectExec.java:111)
	at org.apache.http.impl.client.InternalHttpClient.doExecute(InternalHttpClient.java:185)
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:83)
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:108)
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:56)
	at com.mashape.unirest.http.HttpClientHelper.request(HttpClientHelper.java:138)
	... 74 more

**Comment by EricWittmann** [comment]
OK, well, the stack trace seems to indicate that your server cannot resolve the GitHub domain:

`java.net.UnknownHostException: api.github.com`

Does that make sense for your environment?

**Comment by gigaga** [comment]
After that, add the following lines in standalone-apicurio.xml
```
<system-properties>
    <property name="http.proxyHost" value="My proxy Host here"/>
    <property name="http.proxyPort" value="My proxy Port here"/>
    <property name="https.proxyHost" value="My proxy Host here"/>
    <property name="https.proxyPort" value="My proxy Port here"/>
</system-properties>
```

**Comment by SarvaniVarma** [comment]
Okay, I will try it.

**Comment by EricWittmann** [comment]
Any luck getting past this problem?
