### ISSUE TITLE
gitlab issue

### ISSUE THREAD

**Issue by SarvaniVarma** [Apicurio/apicurio-studio#391]
I have changed the code in GitLabSourceConnector.java file to redirect to our local gitlab, I have changed the following line  
private static final String GITLAB_API_ENDPOINT = "https://gitlab.com" to 
private static final String GITLAB_API_ENDPOINT = "http://<IP>"
but it is still getting redirected to https://gitlab.com, could you please help.
Where else should the changes be made to redirect to our local gitlab?

**Comment by EricWittmann** [comment]
There is an existing issue for this here:

https://github.com/Apicurio/apicurio-studio/issues/206

Getting a local GitLab (or GitHub/Bitbucket) working with Apicurio requires two things:

1) Update the GL api url in Apicurio (you've done this)
2) Update the Identity Provider in your local Keycloak server to use your local GitLab installation for auth rather than the online one

Let me know if that's not enough to go on and I can try to explain more thoroughly.  :)  Also have a look at the referenced issue above for the info in there.

**Comment by SarvaniVarma** [comment]
I have updated the Identity provider in my local keycloak server also but still it is getting redirected to gitlab.com.

**Comment by EricWittmann** [comment]
Can you provide more information on this?  

* What action do you take in Apicurio that redirects to gitlab.com?
* Can you take a screenshot of your Identity Provider configuration (in keycloak)?

Please note that I have not tried any of this myself, but I'll try to help you figure it out as best I can.  The biggest question mark is probably how to configure a custom identity provider in Keycloak that will work with a local GitLab installation.  I assume that this will require using a user-defined OpenID Connect identity provider - you will not be able to use Keycloak's built-in gitlab provider.

![image](https://user-images.githubusercontent.com/1890703/43889627-05205558-9bc5-11e8-926e-6ce8e681b15d.png)

**Comment by SarvaniVarma** [comment]
Okay, I thought gitlab in social is also for local gitlab and In apicurio,I have changed this variable value to out local gitlab IP.
private static final String GITLAB_API_ENDPOINT="<http://10.125.128.92>"

**Comment by EricWittmann** [comment]
If you use the GitLab provider in social then it will try to use gitlab.com.  The URL for gitlab.com is presumably built into that provider.  So to use a local GL you'll need to create a user defined provider so that you can provide the relevant local OAuth URLs.  Note that I have no idea what the auth and token URLs need to be when using a local GitLab installation.  You'll need to find some GitLab documentation about that.

**Comment by EricWittmann** [comment]
Any progress on this?

**Comment by SarvaniVarma** [comment]
I have created a user-defined openid connect identity provider in keycloak, now when I link the accounts, it is redirecting to local gitlab server but the accounts are not getting linked, and also when linked with official gitlab it asked for authorisation permission to access the gitlab account, when linked with local keycloak it didn't ask for any permissions, prompted for username/password when provided, logon to the local gitlab account. In apicurio account linking page I see that the linking is initiated.
![image](https://user-images.githubusercontent.com/41433069/44663298-c3cc5a80-aa2d-11e8-8be0-98e35e46a0ee.png)

![image](https://user-images.githubusercontent.com/41433069/44663547-861c0180-aa2e-11e8-939c-60e0c39c13b0.png)


Here is the log of Apicurio:
[apicurio-1-6trpf.log](https://github.com/Apicurio/apicurio-studio/files/2324096/apicurio-1-6trpf.log)

Could you help me out.

**Comment by EricWittmann** [comment]
I've never tried this myself, so I can probably be of limited help.  However, looking at your Keycloak configuration, I **suspect** the Auth and Token URLs you are providing are not correct.

Again, I haven't tried this myself, but the URLs that Keycloak uses for the built-in GitLab support are:

```
AUTH_URL = "https://gitlab.com/oauth/authorize";
TOKEN_URL = "https://gitlab.com/oauth/token";
```

I found this information in the Keycloak codebase here:

https://github.com/keycloak/keycloak/blob/master/services/src/main/java/org/keycloak/social/gitlab/GitLabIdentityProvider.java#L48-L49

Note that Apicurio is delegating to Keycloak for this account linking feature, so aside from the URL in the Apicurio SourceConnector, all config and customization work will presumably need to be done in Keycloak.

I would try updating your local keycloak gitlab identity provider config to use the following:

```
Auth URL:  http://gittest-gittest.haproxy.project.matrix.com/oauth/authorize
Token URL:  http://gittest-gittest.haproxy.project.matrix.com/oauth/token
```

See if that makes a difference.

Another option you can take is to provide your own custom GitLab identity provider in Keycloak.  What I mean by this is you can create your own Java class (use the official Keycloak impl as a guide) that implements OIDC but uses your local GitLab installation rather than the gitlab.com one.  This could probably just be a copy/paste of the existing implementation with different URLs.  You'd need to create a custom java project, create the right classes, then build and deploy the result to your Keycloak server.

**Comment by SarvaniVarma** [comment]
I have updated local gitlab identity provider config as:
Auth URL:  http://gittest-gittest.haproxy.project.matrix.com/oauth/authorize
Token URL:  http://gittest-gittest.haproxy.project.matrix.com/oauth/token
Now when I try to link account asked for authorize permission, but when I click on Authorize I get the following error:
![image](https://user-images.githubusercontent.com/41433069/44706003-de4e1480-aabd-11e8-8e21-d83815f19643.png)

I have checked the keycloak codebase: 
https://github.com/keycloak/keycloak/blob/master/services/src/main/java/org/keycloak/social/gitlab/GitLabIdentityProvider.java#L48-L49 
and noticed that userinfo URL also has to be provided, I have updated the 
UserInfo Url in keycloak local gitlab config to http://gittest-gittest.haproxy.project.matrix.com/api/v4/user and tried but it throws the same error.

**Comment by EricWittmann** [comment]
OK that seems like progress.  The stack trace you posted indicates that a database constraint violation occurred, and it implies it's because of a duplicate model.  You could try enabling DEBUG in the keycloak server to see if that spits out more  useful information.  

You could also try logging in to Apicurio with a different user and then try account linking again with that user.  Perhaps you already performed account linking using the default GitLab identity provider in Keycloak and now are trying to use the same alias (and are thus running afoul of a primary key violation in the Keycloak DB).

I'm going to try installing GitLab locally (using their all-in-one docker image) to see if I can test this out myself.

**Comment by SarvaniVarma** [comment]
When I tried with another user, didn't prompt for any authorise permissions, directly the accounts were linked. When I unlink it and try to link it again, I get the same error as mentioned in my previous comment.

**Comment by EricWittmann** [comment]
OK but is it true that account linking was actually **successful** with that other user?  Once linked with that other user did you try publishing an API in Apicurio?  If so, did it work??

I have gitlab-ce installed locally but haven't yet had a chance to install Keycloak and configure it for use with my local gitlab install.  I'll try to do that soon.

**Comment by SarvaniVarma** [comment]
I tried to publish, Gitlab groups are not getting fetched, I get this error in logs:
 
![image](https://user-images.githubusercontent.com/41433069/44791099-83501680-abbe-11e8-8095-c566a3776e23.png)

**Comment by EricWittmann** [comment]
OK I'll be looking into this today and will let you know what I find.

**Comment by EricWittmann** [comment]
I spent some time this week installing gitlab-ce and keycloak locally.  Those two applications, along with Apicurio, were enough to let me test whether Apicurio could integrate with a local GitLab installation.  I'm happy to report that my testing has been successful!  

I have been able to configure Keycloak to use my local GitLab installation for authentication and account linking.  I have been able to successfully link an account in Apicurio.  Once my account was linked, I was able to successfully publish an API from Apicurio into GitLab.

I will take some time later today to document this process.  However, as predicted it did require a small change to Apicurio (making the GitLab API endpoint configurable).  So interested users will need to either build their own Apicurio from master or else wait for the next version (0.2.15.Final) to be released.

Note @SarvaniVarma - you did indeed find a bug where deleting/canceling a linked account will put Apicurio and Keycloak into a state where that user cannot re-create the link.  I've [written that bug up separately](https://github.com/Apicurio/apicurio-studio/issues/407) and will address is asap.

**Comment by EricWittmann** [comment]
I have closed this issue because the only required change to **Apicurio** has now been made.  Namely the API URL for GitHub, GitLab, and Bitbucket are now configurable.  So if you're using a local installation of any of these systems, you can point Apicurio to it.  

Actually get everything working together requires configuration in Keycloak and GitLab/GitHub as well.  This may be non-obvious and so should be documented as an article in the list of Apicurio documentation.  That task will be tracked separately here:

https://github.com/Apicurio/apicurio-studio/issues/408

**Comment by EricWittmann** [comment]
By the way, @SarvaniVarma - there is a workaround for the issue you discovered with deleting/canceling the account link.  You can log into the Keycloak console and search for the broken user in the **Manage->Users** section.  Find the user, click on them, and then go to the **Identity Provider Links** tab.  From there you can remove the GitLab link, which will allow you to re-recreate it via Apicurio without running into that error.

![image](https://user-images.githubusercontent.com/1890703/44810727-9ce26580-aba0-11e8-8ed3-1d1fd3332368.png)

**Comment by SarvaniVarma** [comment]
When I click on "link" in  account no authorise permissions were asked for Gitlab account so I was not able to publish to local gitlab, as mention in my previous account, how can I solve that error, when can I know the exact process to link Apicurio to local Gitlab.

**Comment by EricWittmann** [comment]
I've done my best to set up these environments on my end so that I could test them out - and everything worked like a charm for me.  You should now have access to the documentation I wrote based on my experience setting it all up:

https://apicurio-studio.readme.io/v0.2.15/docs/using-a-local-installation-of-gitlab

(sorry, the link wasn't "public" before - but it is now so you should be able to access it)

Note that I tested all of this with the latest RC version of **gitlab-ce** using their Docker image.  I also used **Keycloak 4.3.0.Final** and the latest master version of **Apicurio** (which includes the ability to customize the GitLab URL).

If you are using different versions of these products let me know and I might be able to find some time to try them out (let me know what versions of gitlab, Keycloak, Keycloak-adapter, and Apicurio you're using)...

**Comment by EricWittmann** [comment]
OK - I can try a quick test with Keycloak 3.4.3 - but you might consider upgrading KC to 4.3.0.  I recall you had some issues with it, perhaps due to your deployment environment, but it would definitely be better if you can get it working. :)

I'll let you know how I make out with KC 3.4.3.

**Comment by SarvaniVarma** [comment]
We cannot upgrade KC to 4.3.0 as all our tools are integrated with KC 3.4.3 and also I was facing forbidden issue in our environment  with KC 4.3.0 version , Once I will try the process given here https://apicurio-studio.readme.io/v0.2.15/docs/using-a-local-installation-of-gitlab and check if the error still exists.

**Comment by EricWittmann** [comment]
Alright I just downloaded and installed and configured Keycloak 3.4.3, following my own documented instructions (and I built and installed a fresh copy of Apiucrio:master) and everything worked as expected.  I was able to perform account linking with my local GitLab.  And once that was done I was able to publish an API to that GitLab instance using Apicurio's **Publish** action.

If you continue to have difficulty after following my documentation, then you'll need to post all of your settings:

* Export your realm settings to file and post them here
* Post your Apicurio `standalone.xml` file
* Post any startup flags you're using when starting Apicurio
* Screen-cap your GitLab **Application** settings (located at `/profile/applications` in GitLab)

**Comment by SarvaniVarma** [comment]
After following the process I got the same error again,
Here are the realm settings, standalone-apicurio.xml filr and Gitlab Application settings
[apicurio-screenshots.zip](https://github.com/Apicurio/apicurio-studio/files/2344164/apicurio-screenshots.zip)

**Comment by EricWittmann** [comment]
All of your configuration looks OK to me.  When I tested this I used HTTP as well, so I don't think that's a problem.

Can you please do the following?

1. Reset your keycloak user (delete the gitlab identity provider link in the *Users* UI)
2. Create the Account Link
3. Try to publish an API to GitLab
4. Attach the full `server.log` from both Apicurio and Keycloak

**Comment by EricWittmann** [comment]
Note also that I did all my testing on a local machine **without** using OpenShift.  So that obviously adds some complexity for you.  Perhaps there's an OpenShift routing issue...

**Comment by SarvaniVarma** [comment]
[apicurio-screenshot.zip](https://github.com/Apicurio/apicurio-studio/files/2348884/apicurio-screenshot.zip)

Only gitlab image is on openshift, I am running Apicurio master on local machine and keycloak 3.4.3 Final as docker image on linux machine. I have observed that I get 403 forbidden error whenever I don't revoke the application in gitlab, after revoke it asked for authorize, later I get 400 bad request error. I have attached all the files in the zip.

**Comment by EricWittmann** [comment]
OK well the most obvious problem I see in the log files is this error in the **Keycloak** log:

```
13:07:51,822 ERROR [org.keycloak.broker.oidc.AbstractOAuth2IdentityProvider] (default task-26) Failed to make identity provider oauth callback: java.net.UnknownHostException: gitlab-apicurio-gitlab.haproxy.project.matrix.com: Name or service not known
	at java.net.Inet4AddressImpl.lookupAllHostAddr(Native Method)
	at java.net.InetAddress$2.lookupAllHostAddr(InetAddress.java:928)
	at java.net.InetAddress.getAddressesFromNameService(InetAddress.java:1323)
	at java.net.InetAddress.getAllByName0(InetAddress.java:1276)
	at java.net.InetAddress.getAllByName(InetAddress.java:1192)
	at java.net.InetAddress.getAllByName(InetAddress.java:1126)
	at org.apache.http.impl.conn.SystemDefaultDnsResolver.resolve(SystemDefaultDnsResolver.java:45)
	at org.apache.http.impl.conn.DefaultHttpClientConnectionOperator.connect(DefaultHttpClientConnectionOperator.java:111)
	at org.apache.http.impl.conn.PoolingHttpClientConnectionManager.connect(PoolingHttpClientConnectionManager.java:353)
	at org.apache.http.impl.execchain.MainClientExec.establishRoute(MainClientExec.java:380)
	at org.apache.http.impl.execchain.MainClientExec.execute(MainClientExec.java:236)
	at org.apache.http.impl.execchain.ProtocolExec.execute(ProtocolExec.java:184)
	at org.apache.http.impl.execchain.RetryExec.execute(RetryExec.java:88)
	at org.apache.http.impl.execchain.RedirectExec.execute(RedirectExec.java:110)
	at org.apache.http.impl.client.InternalHttpClient.doExecute(InternalHttpClient.java:184)
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:82)
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:107)
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:55)
	at org.keycloak.broker.provider.util.SimpleHttp.makeRequest(SimpleHttp.java:185)
	at org.keycloak.broker.provider.util.SimpleHttp.asResponse(SimpleHttp.java:154)
	at org.keycloak.broker.provider.util.SimpleHttp.asString(SimpleHttp.java:146)
	at org.keycloak.broker.oidc.AbstractOAuth2IdentityProvider$Endpoint.authResponse(AbstractOAuth2IdentityProvider.java:397)
```

This implies that the Keycloak server is unable to access the GitLab server because it couldn't resolve the hostname to an IP address.  Is that possible?

**Comment by EricWittmann** [comment]
OK that is helpful information.  It seems that you do not have the **broker** "read-token" role set as a default role in Keycloak.  The `read-token` role is what grants the ability to retrieve an token for a linked account.  Without this, Keycloak will not give Apicurio access to the user's identity provider (account link) stored token.  The result is that Apicurio is unable to make an authenticated call to GitLab.

Here are some screenshots of the setting in Keycloak:

![image](https://user-images.githubusercontent.com/1890703/45041056-69d32280-b035-11e8-971b-b539731cb526.png)
In this screenshot, you can see how to set the `read-token` role from **broker** as a default role assigned to new users.

![image](https://user-images.githubusercontent.com/1890703/45041188-ae5ebe00-b035-11e8-8338-b2681136f9d7.png)
In this screenshot, you can see that my user has the role assigned.  You can check your user in Keycloak's UI and see if it has this role assigned.

Not sure how you configured Keycloak, but if you had used the Apicurio `realm.json` file then this should have been configured for you automatically:

https://github.com/Apicurio/apicurio-studio/blob/master/distro/openshift/auth/realm.json#L724-L726

**Comment by SarvaniVarma** [comment]
This solved the problem, but now I have new error. when I click on publish I get this error:
![image](https://user-images.githubusercontent.com/41433069/45078520-e3d6da80-b10d-11e8-8684-b98f9c021f5c.png)




io.apicurio.hub.core.exceptions.ServerError: Unexpected server error
	at io.apicurio.hub.api.rest.impl.DesignsResource.publishApi(DesignsResource.java:760)
	at io.apicurio.hub.api.rest.impl.DesignsResource$Proxy$_$$_WeldClientProxy.publishApi(Unknown Source)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.jboss.resteasy.core.MethodInjectorImpl.invoke(MethodInjectorImpl.java:139)
	at org.jboss.resteasy.core.ResourceMethodInvoker.invokeOnTarget(ResourceMethodInvoker.java:295)
	at org.jboss.resteasy.core.ResourceMethodInvoker.invoke(ResourceMethodInvoker.java:249)
	at org.jboss.resteasy.core.ResourceMethodInvoker.invoke(ResourceMethodInvoker.java:236)
	at org.jboss.resteasy.core.SynchronousDispatcher.invoke(SynchronousDispatcher.java:402)
	at org.jboss.resteasy.core.SynchronousDispatcher.invoke(SynchronousDispatcher.java:209)
	at org.jboss.resteasy.plugins.server.servlet.ServletContainerDispatcher.service(ServletContainerDispatcher.java:221)
	at org.jboss.resteasy.plugins.server.servlet.HttpServletDispatcher.service(HttpServletDispatcher.java:56)
	at org.jboss.resteasy.plugins.server.servlet.HttpServletDispatcher.service(HttpServletDispatcher.java:51)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:790)
	at io.undertow.servlet.handlers.ServletHandler.handleRequest(ServletHandler.java:85)
	at io.undertow.servlet.handlers.FilterHandler$FilterChainImpl.doFilter(FilterHandler.java:129)
	at io.apicurio.hub.api.security.KeycloakAuthenticationFilter.doFilter(KeycloakAuthenticationFilter.java:72)
	at io.undertow.servlet.core.ManagedFilter.doFilter(ManagedFilter.java:61)
	at io.undertow.servlet.handlers.FilterHandler$FilterChainImpl.doFilter(FilterHandler.java:131)
	at io.apicurio.hub.api.filters.DisableCachingFilter.doFilter(DisableCachingFilter.java:66)
	at io.undertow.servlet.core.ManagedFilter.doFilter(ManagedFilter.java:61)
	at io.undertow.servlet.handlers.FilterHandler$FilterChainImpl.doFilter(FilterHandler.java:131)
	at io.apicurio.hub.api.filters.CorsFilter.doFilter(CorsFilter.java:64)
	at io.undertow.servlet.core.ManagedFilter.doFilter(ManagedFilter.java:61)
	at io.undertow.servlet.handlers.FilterHandler$FilterChainImpl.doFilter(FilterHandler.java:131)
	at io.undertow.servlet.handlers.FilterHandler.handleRequest(FilterHandler.java:84)
	at io.undertow.servlet.handlers.security.ServletSecurityRoleHandler.handleRequest(ServletSecurityRoleHandler.java:62)
	at io.undertow.servlet.handlers.ServletDispatchingHandler.handleRequest(ServletDispatchingHandler.java:36)
	at org.wildfly.extension.undertow.security.SecurityContextAssociationHandler.handleRequest(SecurityContextAssociationHandler.java:78)
	at io.undertow.server.handlers.PredicateHandler.handleRequest(PredicateHandler.java:43)
	at org.keycloak.adapters.undertow.UndertowAuthenticatedActionsHandler.handleRequest(UndertowAuthenticatedActionsHandler.java:66)
	at io.undertow.servlet.handlers.security.SSLInformationAssociationHandler.handleRequest(SSLInformationAssociationHandler.java:131)
	at io.undertow.servlet.handlers.security.ServletAuthenticationCallHandler.handleRequest(ServletAuthenticationCallHandler.java:57)
	at io.undertow.server.handlers.DisableCacheHandler.handleRequest(DisableCacheHandler.java:33)
	at io.undertow.server.handlers.PredicateHandler.handleRequest(PredicateHandler.java:43)
	at io.undertow.security.handlers.AuthenticationConstraintHandler.handleRequest(AuthenticationConstraintHandler.java:53)
	at io.undertow.security.handlers.AbstractConfidentialityHandler.handleRequest(AbstractConfidentialityHandler.java:46)
	at io.undertow.servlet.handlers.security.ServletConfidentialityConstraintHandler.handleRequest(ServletConfidentialityConstraintHandler.java:64)
	at io.undertow.servlet.handlers.security.ServletSecurityConstraintHandler.handleRequest(ServletSecurityConstraintHandler.java:59)
	at io.undertow.security.handlers.AuthenticationMechanismsHandler.handleRequest(AuthenticationMechanismsHandler.java:60)
	at io.undertow.servlet.handlers.security.CachedAuthenticatedSessionHandler.handleRequest(CachedAuthenticatedSessionHandler.java:77)
	at io.undertow.security.handlers.NotificationReceiverHandler.handleRequest(NotificationReceiverHandler.java:50)
	at io.undertow.security.handlers.AbstractSecurityContextAssociationHandler.handleRequest(AbstractSecurityContextAssociationHandler.java:43)
	at io.undertow.server.handlers.PredicateHandler.handleRequest(PredicateHandler.java:43)
	at org.wildfly.extension.undertow.security.jacc.JACCContextIdHandler.handleRequest(JACCContextIdHandler.java:61)
	at io.undertow.server.handlers.PredicateHandler.handleRequest(PredicateHandler.java:43)
	at org.keycloak.adapters.undertow.ServletPreAuthActionsHandler.handleRequest(ServletPreAuthActionsHandler.java:69)
	at io.undertow.server.handlers.PredicateHandler.handleRequest(PredicateHandler.java:43)
	at io.undertow.servlet.handlers.ServletInitialHandler.handleFirstRequest(ServletInitialHandler.java:292)
	at io.undertow.servlet.handlers.ServletInitialHandler.access$100(ServletInitialHandler.java:81)
	at io.undertow.servlet.handlers.ServletInitialHandler$2.call(ServletInitialHandler.java:138)
	at io.undertow.servlet.handlers.ServletInitialHandler$2.call(ServletInitialHandler.java:135)
	at io.undertow.servlet.core.ServletRequestContextThreadSetupAction$1.call(ServletRequestContextThreadSetupAction.java:48)
	at io.undertow.servlet.core.ContextClassLoaderSetupAction$1.call(ContextClassLoaderSetupAction.java:43)
	at io.undertow.servlet.api.LegacyThreadSetupActionWrapper$1.call(LegacyThreadSetupActionWrapper.java:44)
	at io.undertow.servlet.api.LegacyThreadSetupActionWrapper$1.call(LegacyThreadSetupActionWrapper.java:44)
	at io.undertow.servlet.api.LegacyThreadSetupActionWrapper$1.call(LegacyThreadSetupActionWrapper.java:44)
	at io.undertow.servlet.api.LegacyThreadSetupActionWrapper$1.call(LegacyThreadSetupActionWrapper.java:44)
	at io.undertow.servlet.api.LegacyThreadSetupActionWrapper$1.call(LegacyThreadSetupActionWrapper.java:44)
	at io.undertow.servlet.handlers.ServletInitialHandler.dispatchRequest(ServletInitialHandler.java:272)
	at io.undertow.servlet.handlers.ServletInitialHandler.access$000(ServletInitialHandler.java:81)
	at io.undertow.servlet.handlers.ServletInitialHandler$1.handleRequest(ServletInitialHandler.java:104)
	at io.undertow.server.Connectors.executeRootHandler(Connectors.java:202)
	at io.undertow.server.HttpServerExchange$1.run(HttpServerExchange.java:805)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: io.apicurio.hub.api.connectors.SourceConnectorException: Unexpected response from GitLab: HTTP/1.0 503 Service Unavailable
	at io.apicurio.hub.api.gitlab.GitLabSourceConnector.getResourceContentFromGitLab(GitLabSourceConnector.java:537)
	at io.apicurio.hub.api.gitlab.GitLabSourceConnector.getResourceContent(GitLabSourceConnector.java:193)
	at io.apicurio.hub.api.gitlab.GitLabSourceConnector$Proxy$_$$_WeldClientProxy.getResourceContent(Unknown Source)
	at io.apicurio.hub.api.rest.impl.DesignsResource.publishApi(DesignsResource.java:744)
	... 68 more

**Comment by EricWittmann** [comment]
The relevant part of that error stack trace is:

`Unexpected response from GitLab: HTTP/1.0 503 Service Unavailable`

Are you sure that GitLab was available when you tried to publish?  If you try again do you get the same error?  I was definitely successful when I published an API to my local GitLab instance.  Any HTTP error that Apicurio might receive from GitLab would definitely indicate a problem with GL.

**Comment by SarvaniVarma** [comment]
Yeah Gitlab was up and running, In Apicurio log there was no http error, In the UI I found this error,
![image](https://user-images.githubusercontent.com/41433069/45093236-6de66980-b135-11e8-9783-bb0f776d8e6d.png)

Apicurio could fetch groups,project and branch from the gitlab but when I publish its throws an error, it could not publish to gitlab.

**Comment by EricWittmann** [comment]
Right, the Apicurio log doesn't show the error because it is being passed back to the client (the browser).  The stack trace that you copy/pasted into the previous post showed the root cause of the error, which was a 503 response from GitLab.  Here is the line of code that caused the failure:

https://github.com/Apicurio/apicurio-studio/blob/master/back-end/hub-api/src/main/java/io/apicurio/hub/api/gitlab/GitLabSourceConnector.java#L537

I do not know why GitLab is responding with a 503 error for you.  I think you'll have to do some debugging or add some `System.out.println` statements if you want to get more information.  Or perhaps there is a log in the GitLab server that has something interesting.  

What version of GitLab are you running?  Perhaps the GL API has changed?

**Comment by SarvaniVarma** [comment]
I have tried cloning a project from gitlab using git clone command, here also it throwed  503 http error, GitLab is of latest version. I will debut the error in GitLab, may be the problem is with the deployment.

**Comment by EricWittmann** [comment]
OK well I have a few suggestions.  

Try to use Postman or Curl or some other REST client to test whether the API call succeeds (the API call that is failing in Apicurio).  The API call that is failing is this one:

`/api/v4/projects/:id/repository/files/:path?ref=:branch`

Documentation for that API can be found here:

https://docs.gitlab.com/ee/api/repository_files.html#get-file-from-repository

In order to test with e.g. Postman you'll need to create a **Personal Access Token** in GitLab so you can make authenticated API calls.  Do that here:

`http://GITLAB_DOMAIN/profile/personal_access_tokens`

**Comment by SarvaniVarma** [comment]
It was a proxy issue, I added no proxy for local GitLab in standalone.xml file. 
when I added this line  
<property name="http.nonProxyHosts" value="<gitlab-url"/>
under system-properties in standalone.xml file http 503 error is resolved. Now I have successfully published in gitlab :)

**Comment by EricWittmann** [comment]
Great news!
