### ISSUE TITLE
Error fetching groups from gitlab when publishing API

### ISSUE THREAD

**Issue by snowlock650** [Apicurio/apicurio-studio#616]
apicurio version: 0.2.20.Final
keycloak version: 4.1.0.Final
GitLab version: 10.3.0

Currently I have set up the apicurio to connect to the local gitlab and keycloak instance following the instructions from the documentation. All was fine until I tried to publish a sample api to gitlab, I couldn't select any groups and projects, they all showed "no matching options". 

The apicurio and keycloak log didn't show any error. The browser did show that the accessing 
https://<redacted>/api-hub/accounts/GitLab/groups  resulted in ServerError. It is worth noting that initially it was showing "forbidden" after checking the keycloak permission with a similar thread (
#529 ), with nothing changed, the error became "Bad Request."  

Any idea or suggestions on how to fix this issue? 

 
The browser side trace is as follows:
```
io.apicurio.hub.core.exceptions.ServerError: Unexpected server error
	at io.apicurio.hub.api.rest.impl.AccountsResource.getGroups(AccountsResource.java:278)
	at io.apicurio.hub.api.rest.impl.AccountsResource$Proxy$_$$_WeldClientProxy.getGroups(Unknown Source)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.jboss.resteasy.core.MethodInjectorImpl.invoke(MethodInjectorImpl.java:139)
	at org.jboss.resteasy.core.ResourceMethodInvoker.invokeOnTarget(ResourceMethodInvoker.java:295)
	at org.jboss.resteasy.core.ResourceMethodInvoker.invoke(ResourceMethodInvoker.java:249)
	at org.jboss.resteasy.core.ResourceMethodInvoker.invoke(ResourceMethodInvoker.java:236)
	at org.jboss.resteasy.core.SynchronousDispatcher.invoke(SynchronousDispatcher.java:402)
	at org.jboss.resteasy.core.SynchronousDispatcher.invoke(SynchronousDispatcher.java:209)
	at org.jboss.resteasy.plugins.server.servlet.ServletContainerDispatcher.service(ServletContainerDispatcher.java:221)
	at org.jboss.resteasy.plugins.server.servlet.HttpServletDispatcher.service(HttpServletDispatcher.java:56)
	at org.jboss.resteasy.plugins.server.servlet.HttpServletDispatcher.service(HttpServletDispatcher.java:51)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:790)
	at io.undertow.servlet.handlers.ServletHandler.handleRequest(ServletHandler.java:85)
	at io.undertow.servlet.handlers.FilterHandler$FilterChainImpl.doFilter(FilterHandler.java:129)
	at io.apicurio.hub.api.security.KeycloakAuthenticationFilter.doFilter(KeycloakAuthenticationFilter.java:72)
	at io.undertow.servlet.core.ManagedFilter.doFilter(ManagedFilter.java:61)
	at io.undertow.servlet.handlers.FilterHandler$FilterChainImpl.doFilter(FilterHandler.java:131)
	at io.apicurio.hub.api.filters.DisableCachingFilter.doFilter(DisableCachingFilter.java:66)
	at io.undertow.servlet.core.ManagedFilter.doFilter(ManagedFilter.java:61)
	at io.undertow.servlet.handlers.FilterHandler$FilterChainImpl.doFilter(FilterHandler.java:131)
	at io.apicurio.hub.api.filters.CorsFilter.doFilter(CorsFilter.java:64)
	at io.undertow.servlet.core.ManagedFilter.doFilter(ManagedFilter.java:61)
	at io.undertow.servlet.handlers.FilterHandler$FilterChainImpl.doFilter(FilterHandler.java:131)
	at io.undertow.servlet.handlers.FilterHandler.handleRequest(FilterHandler.java:84)
	at io.undertow.servlet.handlers.security.ServletSecurityRoleHandler.handleRequest(ServletSecurityRoleHandler.java:62)
	at io.undertow.servlet.handlers.ServletDispatchingHandler.handleRequest(ServletDispatchingHandler.java:36)
	at org.wildfly.extension.undertow.security.SecurityContextAssociationHandler.handleRequest(SecurityContextAssociationHandler.java:78)
	at io.undertow.server.handlers.PredicateHandler.handleRequest(PredicateHandler.java:43)
	at org.keycloak.adapters.undertow.UndertowAuthenticatedActionsHandler.handleRequest(UndertowAuthenticatedActionsHandler.java:66)
	at io.undertow.servlet.handlers.security.SSLInformationAssociationHandler.handleRequest(SSLInformationAssociationHandler.java:131)
	at io.undertow.servlet.handlers.security.ServletAuthenticationCallHandler.handleRequest(ServletAuthenticationCallHandler.java:57)
	at io.undertow.server.handlers.DisableCacheHandler.handleRequest(DisableCacheHandler.java:33)
	at io.undertow.server.handlers.PredicateHandler.handleRequest(PredicateHandler.java:43)
	at io.undertow.security.handlers.AuthenticationConstraintHandler.handleRequest(AuthenticationConstraintHandler.java:53)
	at io.undertow.security.handlers.AbstractConfidentialityHandler.handleRequest(AbstractConfidentialityHandler.java:46)
	at io.undertow.servlet.handlers.security.ServletConfidentialityConstraintHandler.handleRequest(ServletConfidentialityConstraintHandler.java:64)
	at io.undertow.servlet.handlers.security.ServletSecurityConstraintHandler.handleRequest(ServletSecurityConstraintHandler.java:59)
	at io.undertow.security.handlers.AuthenticationMechanismsHandler.handleRequest(AuthenticationMechanismsHandler.java:60)
	at io.undertow.servlet.handlers.security.CachedAuthenticatedSessionHandler.handleRequest(CachedAuthenticatedSessionHandler.java:77)
	at io.undertow.security.handlers.NotificationReceiverHandler.handleRequest(NotificationReceiverHandler.java:50)
	at io.undertow.security.handlers.AbstractSecurityContextAssociationHandler.handleRequest(AbstractSecurityContextAssociationHandler.java:43)
	at io.undertow.server.handlers.PredicateHandler.handleRequest(PredicateHandler.java:43)
	at org.wildfly.extension.undertow.security.jacc.JACCContextIdHandler.handleRequest(JACCContextIdHandler.java:61)
	at io.undertow.server.handlers.PredicateHandler.handleRequest(PredicateHandler.java:43)
	at org.keycloak.adapters.undertow.ServletPreAuthActionsHandler.handleRequest(ServletPreAuthActionsHandler.java:69)
	at io.undertow.server.handlers.PredicateHandler.handleRequest(PredicateHandler.java:43)
	at io.undertow.servlet.handlers.ServletInitialHandler.handleFirstRequest(ServletInitialHandler.java:292)
	at io.undertow.servlet.handlers.ServletInitialHandler.access$100(ServletInitialHandler.java:81)
	at io.undertow.servlet.handlers.ServletInitialHandler$2.call(ServletInitialHandler.java:138)
	at io.undertow.servlet.handlers.ServletInitialHandler$2.call(ServletInitialHandler.java:135)
	at io.undertow.servlet.core.ServletRequestContextThreadSetupAction$1.call(ServletRequestContextThreadSetupAction.java:48)
	at io.undertow.servlet.core.ContextClassLoaderSetupAction$1.call(ContextClassLoaderSetupAction.java:43)
	at io.undertow.servlet.api.LegacyThreadSetupActionWrapper$1.call(LegacyThreadSetupActionWrapper.java:44)
	at io.undertow.servlet.api.LegacyThreadSetupActionWrapper$1.call(LegacyThreadSetupActionWrapper.java:44)
	at io.undertow.servlet.api.LegacyThreadSetupActionWrapper$1.call(LegacyThreadSetupActionWrapper.java:44)
	at io.undertow.servlet.api.LegacyThreadSetupActionWrapper$1.call(LegacyThreadSetupActionWrapper.java:44)
	at io.undertow.servlet.api.LegacyThreadSetupActionWrapper$1.call(LegacyThreadSetupActionWrapper.java:44)
	at io.undertow.servlet.handlers.ServletInitialHandler.dispatchRequest(ServletInitialHandler.java:272)
	at io.undertow.servlet.handlers.ServletInitialHandler.access$000(ServletInitialHandler.java:81)
	at io.undertow.servlet.handlers.ServletInitialHandler$1.handleRequest(ServletInitialHandler.java:104)
	at io.undertow.server.Connectors.executeRootHandler(Connectors.java:202)
	at io.undertow.server.HttpServerExchange$1.run(HttpServerExchange.java:805)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: io.apicurio.hub.api.connectors.SourceConnectorException: Error getting GitLab groups: Bad Request
	at io.apicurio.hub.api.gitlab.GitLabSourceConnector.addGroups(GitLabSourceConnector.java:346)
	at io.apicurio.hub.api.gitlab.GitLabSourceConnector.getAllGroups(GitLabSourceConnector.java:316)
	at io.apicurio.hub.api.gitlab.GitLabSourceConnector.getGroups(GitLabSourceConnector.java:295)
	at io.apicurio.hub.api.gitlab.GitLabSourceConnector$Proxy$_$$_WeldClientProxy.getGroups(Unknown Source)
	at io.apicurio.hub.api.rest.impl.AccountsResource.getGroups(AccountsResource.java:276)
	... 68 more
```

**Comment by EricWittmann** [comment]
The error of `Bad request` suggests that perhaps the local GitLab URL you've configured in Apicurio may not be correct.  Here is how you can check.  Somehow you have configured the GitLab API by either modifying the `standalone.xml` file or by passing it on the command line like this:

`-Dapicurio.hub.gitlab.api=https://gitlab.example.com`

Whatever URL you're using there will be used as the base for all API calls from Apicurio to GitLab.  In the case of getting the list of Groups the user belongs to, the API endpoint is `/api/v4/user`.  So if you used the above base GitLab URL that will result in this:

`https://gitlab.example.com/api/v4/user`

So then you could try making a direct call to the above endpoint yourself (e.g. via curl) to see what you get.

If all of that works/seems OK, then we'll have to think of something else to narrow down the issue.

**Comment by snowlock650** [comment]
The gitlab base URL was configured via -D command line flag,  I double checked the flag and the value is correct. Since I was able to login/authenticate via gitlab as well as linking gitlab account, I assume the gitlab base url is set correctly. 

And the the formed URL 
https://<domain>/api/v4/user 
returns the result correctly. 

I will try to see if it is possible to capture the actual http request URL to see if it reveals more information. Any suggestions?

**Comment by EricWittmann** [comment]
I have two suggestions that **might** be quick and helpful.  :)

The first would be to set up a logging TCP proxy and point Apicurio to that instead of your local GitLab.  I know the Eclipse IDE has something built-in.  Or perhaps use something like this:  https://github.com/alexbirkett/tcp-logging-proxy

Another option that might work is a network interface sniffer like wireshark.  If you're using `https` that might not work and you might need to go the proxy route.

If you're willing to build Apicurio locally to debug the problem, you'll want to look here:

https://github.com/Apicurio/apicurio-studio/blob/master/back-end/hub-api/src/main/java/io/apicurio/hub/api/gitlab/GitLabSourceConnector.java#L262-L301

Add any logging information you think would be useful and then rebuild.  A full `mvn clearn install` will result in the following file being created:

`distro/quickstart/target/apicurio-studio-0.2.21-SNAPSHOT-quickstart.zip`

**Comment by EricWittmann** [comment]
Oh - one thing to note is that the URL to GitLab that you configure via the `-Dapicurio.hub.gitlab.api` system property is actually independent of the account linking process.  So it actually **is possible** to have the OAuth/Account Linking stuff set up properly but still not properly connect to GitLab.

**Comment by snowlock650** [comment]
I have managed to find out the actual requesting URL, and response: 

https://gitlab.dataenlighten.com/api/v4/groups?all_available=false&order_by=name&owned=false&page=2&per_page=20&sort=asc&statistics=false?all_available=false 

The response is 400 with the following body: 
{"error":"statistics is invalid"}

The error message is a bit misleading because the actual cause is that the fragment is malformed with two "?".  

The first paged was fetched successfully with the subsequent page erring because some query terms were appended again.

**Comment by EricWittmann** [comment]
OK I'm having a look at this in the code right now.

**Comment by EricWittmann** [comment]
Thanks @snowlock650 for tracking down the source of the error.  I've found the problem in the `GitLabSourceConnector` and will fix it today.  Appreciate your effort on this!

**Comment by EricWittmann** [comment]
Fixed and will be working in the next release (or update and rebuild `master` if you're running Apicurio locally).
