### ISSUE TITLE
Error when importing huge yml/json (larger than 65KB)  with a MySQL database: Data too long for column 'data' at row 1

### ISSUE THREAD

**Issue by Nicnl** [Apicurio/apicurio-studio#683]
Hello,

I tried importing a huge json api file (332Ko)  
The operation failed with the following error:

```
org.jdbi.v3.core.statement.UnableToExecuteStatementException:
com.mysql.jdbc.MysqlDataTruncation: Data truncation: Data too long for column 'data' at row 1
[
  statement:"INSERT INTO api_content (design_id, type, data, created_by, created_on) VALUES (?, ?, ?, ?, ?)",
  rewritten:"INSERT INTO api_content (design_id, type, data, created_by, created_on) VALUES (?, ?, ?, ?, ?)",
  parsed:"ParsedSql{sql='INSERT INTO api_content (design_id, type, data, created_by, created_on) VALUES (?, ?, ?, ?, ?)',
  parameters=ParsedParameters{positional=true, parameterNames=[?, ?, ?, ?, ?]}}",
  arguments:{positional:{0:5,1:1,2:<stream object cannot be read for toString() calls>,3:n.lim@pyres.com,4:Mon Mar 11 11:38:40 UTC 2019},
  named:{},
  finder:[]}
]
```

I've quickly looked into it  
Here is the structure of the `api_content` table:  
```
mysql> DESCRIBE api_content;
+------------+--------------+------+-----+---------+----------------+
| Field      | Type         | Null | Key | Default | Extra          |
+------------+--------------+------+-----+---------+----------------+
| design_id  | bigint(20)   | NO   | MUL | NULL    |                |
| version    | bigint(20)   | NO   | PRI | NULL    | auto_increment |
| type       | tinyint(4)   | NO   | MUL | NULL    |                |
| data       | text         | NO   |     | NULL    |                |
| created_by | varchar(255) | NO   | MUL | NULL    |                |
| created_on | datetime     | NO   | MUL | NULL    |                |
| reverted   | tinyint(4)   | NO   | MUL | 0       |                |
| modifed_on | datetime     | YES  |     | NULL    |                |
+------------+--------------+------+-----+---------+----------------+
```

The field `data` is a `TEXT`  
It turns out that `TEXT` fields are limited to 64KB, which is very small

Luckily it's very easy to fix  
Changing it to `MEDIUMTEXT` (16MB) fixes the issue, and I was able to import the api spec successfully

```
mysql> ALTER TABLE api_content MODIFY data MEDIUMTEXT;
Query OK, 25 rows affected (0.68 sec)
Records: 25  Duplicates: 0  Warnings: 0

mysql> DESCRIBE api_content;
+------------+--------------+------+-----+---------+----------------+
| Field      | Type         | Null | Key | Default | Extra          |
+------------+--------------+------+-----+---------+----------------+
| design_id  | bigint(20)   | NO   | MUL | NULL    |                |
| version    | bigint(20)   | NO   | PRI | NULL    | auto_increment |
| type       | tinyint(4)   | NO   | MUL | NULL    |                |
| data       | mediumtext   | YES  |     | NULL    |                |
| created_by | varchar(255) | NO   | MUL | NULL    |                |
| created_on | datetime     | NO   | MUL | NULL    |                |
| reverted   | tinyint(4)   | NO   | MUL | 0       |                |
| modifed_on | datetime     | YES  |     | NULL    |                |
+------------+--------------+------+-----+---------+----------------+
8 rows in set (0.00 sec)
```

**Comment by Nicnl** [comment]
More informations concerning the error:

### Screenshot

![image](https://user-images.githubusercontent.com/1387951/54122763-44690c00-43fe-11e9-857a-b0d08b3790ba.png)

### Stacktrace from the browser

```
io.apicurio.hub.core.exceptions.ServerError: Unexpected server error
	at io.apicurio.hub.api.rest.impl.DesignsResource.importDesignFromData(DesignsResource.java:292)
	at io.apicurio.hub.api.rest.impl.DesignsResource.importDesign(DesignsResource.java:172)
	at io.apicurio.hub.api.rest.impl.DesignsResource$Proxy$_$$_WeldClientProxy.importDesign(Unknown Source)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.jboss.resteasy.core.MethodInjectorImpl.invoke(MethodInjectorImpl.java:139)
	at org.jboss.resteasy.core.ResourceMethodInvoker.internalInvokeOnTarget(ResourceMethodInvoker.java:509)
	at org.jboss.resteasy.core.ResourceMethodInvoker.invokeOnTargetAfterFilter(ResourceMethodInvoker.java:399)
	at org.jboss.resteasy.core.ResourceMethodInvoker.lambda$invokeOnTarget$0(ResourceMethodInvoker.java:363)
	at org.jboss.resteasy.core.interception.PreMatchContainerRequestContext.filter(PreMatchContainerRequestContext.java:355)
	at org.jboss.resteasy.core.ResourceMethodInvoker.invokeOnTarget(ResourceMethodInvoker.java:365)
	at org.jboss.resteasy.core.ResourceMethodInvoker.invoke(ResourceMethodInvoker.java:337)
	at org.jboss.resteasy.core.ResourceMethodInvoker.invoke(ResourceMethodInvoker.java:310)
	at org.jboss.resteasy.core.SynchronousDispatcher.invoke(SynchronousDispatcher.java:439)
	at org.jboss.resteasy.core.SynchronousDispatcher.lambda$invoke$4(SynchronousDispatcher.java:229)
	at org.jboss.resteasy.core.SynchronousDispatcher.lambda$preprocess$0(SynchronousDispatcher.java:135)
	at org.jboss.resteasy.core.interception.PreMatchContainerRequestContext.filter(PreMatchContainerRequestContext.java:355)
	at org.jboss.resteasy.core.SynchronousDispatcher.preprocess(SynchronousDispatcher.java:138)
	at org.jboss.resteasy.core.SynchronousDispatcher.invoke(SynchronousDispatcher.java:215)
	at org.jboss.resteasy.plugins.server.servlet.ServletContainerDispatcher.service(ServletContainerDispatcher.java:227)
	at org.jboss.resteasy.plugins.server.servlet.HttpServletDispatcher.service(HttpServletDispatcher.java:56)
	at org.jboss.resteasy.plugins.server.servlet.HttpServletDispatcher.service(HttpServletDispatcher.java:51)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:791)
	at io.undertow.servlet.handlers.ServletHandler.handleRequest(ServletHandler.java:74)
	at io.undertow.servlet.handlers.FilterHandler$FilterChainImpl.doFilter(FilterHandler.java:129)
	at io.apicurio.hub.api.security.KeycloakAuthenticationFilter.doFilter(KeycloakAuthenticationFilter.java:72)
	at io.undertow.servlet.core.ManagedFilter.doFilter(ManagedFilter.java:61)
	at io.undertow.servlet.handlers.FilterHandler$FilterChainImpl.doFilter(FilterHandler.java:131)
	at io.apicurio.hub.api.filters.DisableCachingFilter.doFilter(DisableCachingFilter.java:66)
	at io.undertow.servlet.core.ManagedFilter.doFilter(ManagedFilter.java:61)
	at io.undertow.servlet.handlers.FilterHandler$FilterChainImpl.doFilter(FilterHandler.java:131)
	at io.apicurio.hub.api.filters.CorsFilter.doFilter(CorsFilter.java:64)
	at io.undertow.servlet.core.ManagedFilter.doFilter(ManagedFilter.java:61)
	at io.undertow.servlet.handlers.FilterHandler$FilterChainImpl.doFilter(FilterHandler.java:131)
	at io.undertow.servlet.handlers.FilterHandler.handleRequest(FilterHandler.java:84)
	at io.undertow.servlet.handlers.security.ServletSecurityRoleHandler.handleRequest(ServletSecurityRoleHandler.java:62)
	at io.undertow.servlet.handlers.ServletChain$1.handleRequest(ServletChain.java:68)
	at io.undertow.servlet.handlers.ServletDispatchingHandler.handleRequest(ServletDispatchingHandler.java:36)
	at org.wildfly.extension.undertow.security.SecurityContextAssociationHandler.handleRequest(SecurityContextAssociationHandler.java:78)
	at io.undertow.server.handlers.PredicateHandler.handleRequest(PredicateHandler.java:43)
	at org.keycloak.adapters.undertow.UndertowAuthenticatedActionsHandler.handleRequest(UndertowAuthenticatedActionsHandler.java:66)
	at org.wildfly.swarm.keycloak.deployment.SecurityContextServletExtension.lambda$null$0(SecurityContextServletExtension.java:40)
	at org.wildfly.swarm.generated.FaviconErrorHandler.handleRequest(FaviconErrorHandler.java:61)
	at io.undertow.server.handlers.PathHandler.handleRequest(PathHandler.java:94)
	at io.undertow.servlet.handlers.security.SSLInformationAssociationHandler.handleRequest(SSLInformationAssociationHandler.java:132)
	at io.undertow.servlet.handlers.security.ServletAuthenticationCallHandler.handleRequest(ServletAuthenticationCallHandler.java:57)
	at io.undertow.server.handlers.DisableCacheHandler.handleRequest(DisableCacheHandler.java:33)
	at io.undertow.server.handlers.PredicateHandler.handleRequest(PredicateHandler.java:43)
	at io.undertow.security.handlers.AuthenticationConstraintHandler.handleRequest(AuthenticationConstraintHandler.java:53)
	at io.undertow.security.handlers.AbstractConfidentialityHandler.handleRequest(AbstractConfidentialityHandler.java:46)
	at io.undertow.servlet.handlers.security.ServletConfidentialityConstraintHandler.handleRequest(ServletConfidentialityConstraintHandler.java:64)
	at io.undertow.servlet.handlers.security.ServletSecurityConstraintHandler.handleRequest(ServletSecurityConstraintHandler.java:59)
	at io.undertow.security.handlers.AuthenticationMechanismsHandler.handleRequest(AuthenticationMechanismsHandler.java:60)
	at io.undertow.servlet.handlers.security.CachedAuthenticatedSessionHandler.handleRequest(CachedAuthenticatedSessionHandler.java:77)
	at io.undertow.security.handlers.NotificationReceiverHandler.handleRequest(NotificationReceiverHandler.java:50)
	at io.undertow.security.handlers.AbstractSecurityContextAssociationHandler.handleRequest(AbstractSecurityContextAssociationHandler.java:43)
	at io.undertow.server.handlers.PredicateHandler.handleRequest(PredicateHandler.java:43)
	at org.wildfly.extension.undertow.security.jacc.JACCContextIdHandler.handleRequest(JACCContextIdHandler.java:61)
	at io.undertow.server.handlers.PredicateHandler.handleRequest(PredicateHandler.java:43)
	at org.wildfly.extension.undertow.deployment.GlobalRequestControllerHandler.handleRequest(GlobalRequestControllerHandler.java:68)
	at org.keycloak.adapters.undertow.ServletPreAuthActionsHandler.handleRequest(ServletPreAuthActionsHandler.java:69)
	at io.undertow.server.handlers.PredicateHandler.handleRequest(PredicateHandler.java:43)
	at io.undertow.servlet.handlers.ServletInitialHandler.handleFirstRequest(ServletInitialHandler.java:292)
	at io.undertow.servlet.handlers.ServletInitialHandler.access$100(ServletInitialHandler.java:81)
	at io.undertow.servlet.handlers.ServletInitialHandler$2.call(ServletInitialHandler.java:138)
	at io.undertow.servlet.handlers.ServletInitialHandler$2.call(ServletInitialHandler.java:135)
	at io.undertow.servlet.core.ServletRequestContextThreadSetupAction$1.call(ServletRequestContextThreadSetupAction.java:48)
	at io.undertow.servlet.core.ContextClassLoaderSetupAction$1.call(ContextClassLoaderSetupAction.java:43)
	at org.wildfly.extension.undertow.security.SecurityContextThreadSetupAction.lambda$create$0(SecurityContextThreadSetupAction.java:105)
	at org.wildfly.extension.undertow.deployment.UndertowDeploymentInfoService$UndertowThreadSetupAction.lambda$create$0(UndertowDeploymentInfoService.java:1502)
	at org.wildfly.extension.undertow.deployment.UndertowDeploymentInfoService$UndertowThreadSetupAction.lambda$create$0(UndertowDeploymentInfoService.java:1502)
	at org.wildfly.extension.undertow.deployment.UndertowDeploymentInfoService$UndertowThreadSetupAction.lambda$create$0(UndertowDeploymentInfoService.java:1502)
	at org.wildfly.extension.undertow.deployment.UndertowDeploymentInfoService$UndertowThreadSetupAction.lambda$create$0(UndertowDeploymentInfoService.java:1502)
	at org.wildfly.swarm.keycloak.deployment.KeycloakThreadSetupHandler.lambda$create$0(KeycloakThreadSetupHandler.java:35)
	at io.undertow.servlet.handlers.ServletInitialHandler.dispatchRequest(ServletInitialHandler.java:272)
	at io.undertow.servlet.handlers.ServletInitialHandler.access$000(ServletInitialHandler.java:81)
	at io.undertow.servlet.handlers.ServletInitialHandler$1.handleRequest(ServletInitialHandler.java:104)
	at io.undertow.server.Connectors.executeRootHandler(Connectors.java:360)
	at io.undertow.server.HttpServerExchange$1.run(HttpServerExchange.java:830)
	at org.jboss.threads.ContextClassLoaderSavingRunnable.run(ContextClassLoaderSavingRunnable.java:35)
	at org.jboss.threads.EnhancedQueueExecutor.safeRun(EnhancedQueueExecutor.java:1985)
	at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.doRunTask(EnhancedQueueExecutor.java:1487)
	at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1378)
	at java.lang.Thread.run(Thread.java:748)
Caused by: io.apicurio.hub.core.exceptions.ServerError: Unexpected server error
	at io.apicurio.hub.api.rest.impl.DesignsResource.importDesignFromData(DesignsResource.java:280)
	... 85 more
Caused by: io.apicurio.hub.core.storage.StorageException: Error inserting API design.
	at io.apicurio.hub.core.storage.jdbc.JdbcStorage.createApiDesign(JdbcStorage.java:741)
	at io.apicurio.hub.core.storage.jdbc.JdbcStorage$Proxy$_$$_WeldClientProxy.createApiDesign(Unknown Source)
	at io.apicurio.hub.api.rest.impl.DesignsResource.importDesignFromData(DesignsResource.java:277)
	... 85 more
Caused by: org.jdbi.v3.core.statement.UnableToExecuteStatementException: com.mysql.jdbc.MysqlDataTruncation: Data truncation: Data too long for column 'data' at row 1 [statement:"INSERT INTO api_content (design_id, type, data, created_by, created_on) VALUES (?, ?, ?, ?, ?)", rewritten:"INSERT INTO api_content (design_id, type, data, created_by, created_on) VALUES (?, ?, ?, ?, ?)", parsed:"ParsedSql{sql='INSERT INTO api_content (design_id, type, data, created_by, created_on) VALUES (?, ?, ?, ?, ?)', parameters=ParsedParameters{positional=true, parameterNames=[?, ?, ?, ?, ?]}}", arguments:{positional:{0:8,1:0,2:<stream object cannot be read for toString() calls>,3:n.lim@pyres.com,4:Mon Mar 11 11:59:18 UTC 2019}, named:{}, finder:[]}]
	at org.jdbi.v3.core.statement.SqlStatement.internalExecute(SqlStatement.java:1568)
	at org.jdbi.v3.core.result.ResultProducers.lambda$returningUpdateCount$0(ResultProducers.java:48)
	at org.jdbi.v3.core.statement.Update.execute(Update.java:53)
	at org.jdbi.v3.core.statement.Update.execute(Update.java:41)
	at io.apicurio.hub.core.storage.jdbc.JdbcStorage.lambda$createApiDesign$26(JdbcStorage.java:736)
	at org.jdbi.v3.core.Jdbi.withHandle(Jdbi.java:330)
	at io.apicurio.hub.core.storage.jdbc.JdbcStorage.createApiDesign(JdbcStorage.java:703)
	... 87 more
Caused by: com.mysql.jdbc.MysqlDataTruncation: Data truncation: Data too long for column 'data' at row 1
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3976)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3914)
	at com.mysql.jdbc.MysqlIO.sendCommand(MysqlIO.java:2530)
	at com.mysql.jdbc.MysqlIO.sqlQueryDirect(MysqlIO.java:2683)
	at com.mysql.jdbc.ConnectionImpl.execSQL(ConnectionImpl.java:2495)
	at com.mysql.jdbc.PreparedStatement.executeInternal(PreparedStatement.java:1903)
	at com.mysql.jdbc.PreparedStatement.execute(PreparedStatement.java:1242)
	at org.jboss.jca.adapters.jdbc.WrappedPreparedStatement.execute(WrappedPreparedStatement.java:442)
	at org.jdbi.v3.core.statement.SqlLoggerUtil.wrap(SqlLoggerUtil.java:31)
	at org.jdbi.v3.core.statement.SqlStatement.internalExecute(SqlStatement.java:1560)
	... 93 more
```

### Stacktrace from the docker container

```
apicurio-studio-ws_1     | 2019-03-11 11:38:40,308 ERROR [io.apicurio.hub.core.editing.ops.processors.CommandProcessor] (default task-2) Error storing the command 1552304319522.: io.apicurio.hub.core.storage.StorageException: Error adding content entry for API design.
apicurio-studio-ws_1     | 	at io.apicurio.hub.core.storage.jdbc.JdbcStorage.addContent(JdbcStorage.java:556)
apicurio-studio-ws_1     | 	at io.apicurio.hub.core.storage.jdbc.JdbcStorage$Proxy$_$$_WeldClientProxy.addContent(Unknown Source)
apicurio-studio-ws_1     | 	at io.apicurio.hub.core.editing.ops.processors.CommandProcessor.process(CommandProcessor.java:67)
apicurio-studio-ws_1     | 	at io.apicurio.hub.core.editing.ops.processors.OperationProcessorDispatcher.process(OperationProcessorDispatcher.java:78)
apicurio-studio-ws_1     | 	at io.apicurio.hub.core.editing.ops.processors.OperationProcessorDispatcher$Proxy$_$$_WeldClientProxy.process(Unknown Source)
apicurio-studio-ws_1     | 	at io.apicurio.hub.editing.EditApiDesignEndpoint.onMessage(EditApiDesignEndpoint.java:181)
apicurio-studio-ws_1     | 	at sun.reflect.GeneratedMethodAccessor5.invoke(Unknown Source)
apicurio-studio-ws_1     | 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
apicurio-studio-ws_1     | 	at java.lang.reflect.Method.invoke(Method.java:498)
apicurio-studio-ws_1     | 	at io.undertow.websockets.jsr.annotated.BoundMethod.invoke(BoundMethod.java:87)
apicurio-studio-ws_1     | 	at io.undertow.websockets.jsr.annotated.AnnotatedEndpoint$2.onMessage(AnnotatedEndpoint.java:142)
apicurio-studio-ws_1     | 	at io.undertow.websockets.jsr.FrameHandler$7.run(FrameHandler.java:284)
apicurio-studio-ws_1     | 	at io.undertow.websockets.jsr.ServerWebSocketContainer$1.call(ServerWebSocketContainer.java:169)
apicurio-studio-ws_1     | 	at io.undertow.websockets.jsr.ServerWebSocketContainer$1.call(ServerWebSocketContainer.java:166)
apicurio-studio-ws_1     | 	at io.undertow.servlet.core.ContextClassLoaderSetupAction$1.call(ContextClassLoaderSetupAction.java:43)
apicurio-studio-ws_1     | 	at org.wildfly.extension.undertow.security.SecurityContextThreadSetupAction.lambda$create$0(SecurityContextThreadSetupAction.java:105)
apicurio-studio-ws_1     | 	at org.wildfly.extension.undertow.deployment.UndertowDeploymentInfoService$UndertowThreadSetupAction.lambda$create$0(UndertowDeploymentInfoService.java:1502)
apicurio-studio-ws_1     | 	at org.wildfly.extension.undertow.deployment.UndertowDeploymentInfoService$UndertowThreadSetupAction.lambda$create$0(UndertowDeploymentInfoService.java:1502)
apicurio-studio-ws_1     | 	at org.wildfly.extension.undertow.deployment.UndertowDeploymentInfoService$UndertowThreadSetupAction.lambda$create$0(UndertowDeploymentInfoService.java:1502)
apicurio-studio-ws_1     | 	at org.wildfly.extension.undertow.deployment.UndertowDeploymentInfoService$UndertowThreadSetupAction.lambda$create$0(UndertowDeploymentInfoService.java:1502)
apicurio-studio-ws_1     | 	at io.undertow.websockets.jsr.ServerWebSocketContainer.invokeEndpointMethod(ServerWebSocketContainer.java:603)
apicurio-studio-ws_1     | 	at io.undertow.websockets.jsr.ServerWebSocketContainer$6.run(ServerWebSocketContainer.java:589)
apicurio-studio-ws_1     | 	at io.undertow.websockets.jsr.OrderedExecutor$ExecutorTask.run(OrderedExecutor.java:67)
apicurio-studio-ws_1     | 	at org.jboss.threads.ContextClassLoaderSavingRunnable.run(ContextClassLoaderSavingRunnable.java:35)
apicurio-studio-ws_1     | 	at org.jboss.threads.EnhancedQueueExecutor.safeRun(EnhancedQueueExecutor.java:1985)
apicurio-studio-ws_1     | 	at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.doRunTask(EnhancedQueueExecutor.java:1487)
apicurio-studio-ws_1     | 	at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1378)
apicurio-studio-ws_1     | 	at java.lang.Thread.run(Thread.java:748)
apicurio-studio-ws_1     | Caused by: org.jdbi.v3.core.statement.UnableToExecuteStatementException: com.mysql.jdbc.MysqlDataTruncation: Data truncation: Data too long for column 'data' at row 1 [statement:"INSERT INTO api_content (design_id, type, data, created_by, created_on) VALUES (?, ?, ?, ?, ?)", rewritten:"INSERT INTO api_content (design_id, type, data, created_by, created_on) VALUES (?, ?, ?, ?, ?)", parsed:"ParsedSql{sql='INSERT INTO api_content (design_id, type, data, created_by, created_on) VALUES (?, ?, ?, ?, ?)', parameters=ParsedParameters{positional=true, parameterNames=[?, ?, ?, ?, ?]}}", arguments:{positional:{0:5,1:1,2:<stream object cannot be read for toString() calls>,3:n.lim@pyres.com,4:Mon Mar 11 11:38:40 UTC 2019}, named:{}, finder:[]}]
apicurio-studio-ws_1     | 	at org.jdbi.v3.core.statement.SqlStatement.internalExecute(SqlStatement.java:1568)
apicurio-studio-ws_1     | 	at org.jdbi.v3.core.result.ResultProducers.lambda$getGeneratedKeys$4(ResultProducers.java:108)
apicurio-studio-ws_1     | 	at org.jdbi.v3.core.result.ResultIterable.lambda$of$0(ResultIterable.java:53)
apicurio-studio-ws_1     | 	at org.jdbi.v3.core.result.ResultIterable.findOnly(ResultIterable.java:97)
apicurio-studio-ws_1     | 	at io.apicurio.hub.core.storage.jdbc.JdbcStorage.lambda$addContent$19(JdbcStorage.java:552)
apicurio-studio-ws_1     | 	at org.jdbi.v3.core.Jdbi.withHandle(Jdbi.java:330)
apicurio-studio-ws_1     | 	at io.apicurio.hub.core.storage.jdbc.JdbcStorage.addContent(JdbcStorage.java:540)
apicurio-studio-ws_1     | 	... 27 more
apicurio-studio-ws_1     | Caused by: com.mysql.jdbc.MysqlDataTruncation: Data truncation: Data too long for column 'data' at row 1
apicurio-studio-ws_1     | 	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3976)
apicurio-studio-ws_1     | 	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3914)
apicurio-studio-ws_1     | 	at com.mysql.jdbc.MysqlIO.sendCommand(MysqlIO.java:2530)
apicurio-studio-ws_1     | 	at com.mysql.jdbc.MysqlIO.sqlQueryDirect(MysqlIO.java:2683)
apicurio-studio-ws_1     | 	at com.mysql.jdbc.ConnectionImpl.execSQL(ConnectionImpl.java:2495)
apicurio-studio-ws_1     | 	at com.mysql.jdbc.PreparedStatement.executeInternal(PreparedStatement.java:1903)
apicurio-studio-ws_1     | 	at com.mysql.jdbc.PreparedStatement.execute(PreparedStatement.java:1242)
apicurio-studio-ws_1     | 	at org.jboss.jca.adapters.jdbc.WrappedPreparedStatement.execute(WrappedPreparedStatement.java:442)
apicurio-studio-ws_1     | 	at org.jdbi.v3.core.statement.SqlLoggerUtil.wrap(SqlLoggerUtil.java:31)
apicurio-studio-ws_1     | 	at org.jdbi.v3.core.statement.SqlStatement.internalExecute(SqlStatement.java:1560)
apicurio-studio-ws_1     | 	... 33 more
```

### Containers versions used

- `percona:5.7`
- `jboss/keycloak:4.8.3.Final`
- `apicurio/apicurio-studio-api:0.2.23.Final`
- `apicurio/apicurio-studio-ws:0.2.23.Final`
- `apicurio/apicurio-studio-ui:0.2.23.Final`

**Comment by EricWittmann** [comment]
Well, first let me say - great bug report!  Couldn't have been more thorough - and included the solution.  I will update the appropriate DDLs in Apicurio for MySQL. 

I didn't know about this restriction for MySQL.  I've checked the docs for postgres and h2 and fortunately those databases do not share the MySQL storage restrictions for TEXT/CLOB columns.  So the fix is easy enough. :)

Thanks!

**Comment by Nicnl** [comment]
Heh, on my end I didn't know that postgres did not have this limitation

From what you said, you're able to set a specific field type for mysql only?  
That's very reassuring, I feared that you would have to chose one or the other.

Concerning the field type, there's two choices  
I tested MEDIUMTEXT that at 16MB max, but there's also LONGTEXT that's at 4GB.

I have no idea if openapi docs larger than 16MB are a thing or not and if LONGTEXT would be required.

**Comment by EricWittmann** [comment]
Yes there are different DDLs for each of the supported databases, fortunately.  So I'm switching MySQL to use `MEDIUMTEXT` and leaving the others as they are.  I did consider `LONGTEXT` but it seems like overkill.  I'll wait for someone else to run into the 16MB limitation and complain about it and then deal with it then. :)  I'm guessing it won't happen - although I suppose if someone is programmatically generating OpenAPI documents it might be possible....

**Comment by Nicnl** [comment]
You sir are an absolute madman  
I've never seen in my life such a nice response and fast bug fix  

Kudos
