### ISSUE TITLE
Error: DOMException: Failed to construct 'WebSocket': The URL's scheme must be either 'ws' or 'wss'. 'http' is not allowed.

### ISSUE THREAD

**Issue by dbtech** [Apicurio/apicurio-studio#891]
I have a Quickstart installation on an external server "apicurio.example.com" (anonymized). I use an apache proxy server to access the site (both http). I can create an API but can not edit. Javascript reports an error (below). What configuration item might be missing / incorrect?
--------
```
[ApisPageComponent] loadAsyncPageData
[ApisService] Getting all APIs
[ApisService] Fetching API list: http://apicurio.example.com/api-hub/designs
[ApiDetailPageComponent] Loading async page data
[ApisService] Getting an API Design: http://apicurio.example.com/api-hub/designs/1
[ApisService] Getting contributors: http://apicurio.example.com/api-hub/designs/1/contributors
[ApisService] Getting all activity for API 1
[ApisService] Fetching API design activity: http://apicurio.example.com/api-hub/designs/1/activity?end=10
[ApisService] Getting collaborators for API Design 1
[ApisService] Fetching collaborator list: http://apicurio.example.com/api-hub/designs/1/collaborators
[ApiDetailPageComponent] Contributors data loaded: {totalEdits: 1, contributors: Array(1)}
[ApiDetailPageComponent] Activity data loaded
[ValidationService] Getting all validation profiles
[ValidationService] Fetching validation profiles: http://apicurio.example.com/api-hub/validationProfiles
[ApiEditorPageComponent] Loading async page data
[ApisService] Getting an API Design: http://apicurio.example.com/api-hub/designs/1
[ApisService] Editing API Design: http://apicurio.example.com/api-hub/designs/1/session
[ApisService] Editing Session UUID: a88b9d13-fb2b-43e5-aaec-31fecb1df0a7
[ApisService] Content Version: 1
[ApiEditorPageComponent] Definition loaded.  Opening editing session.
[ApisService] Opening editing session on URL: http://apicurio.example.com/api-editing/designs/1?uuid=a88b9d13-fb2b-43e5-aaec-31fecb1df0a7&user=email%40example.com&secret=eyJhbGciOiJSUzI1NiIsInR5cCIgOiAiSldUIiwia2lkIiA6ICJYUEFkZElNQ21P
[ApiEditorPageComponent] **Error editing API design.** (anonymous)
    **Error: DOMException: Failed to construct 'WebSocket': The URL's scheme must be either 'ws' or 'wss'. 'http' is not allowed.**
    at t.openEditingSession (http://apicurio.example.com/studio/main.d73499da517a45f6f776.js:1:2954806)
    at http://apicurio.example.com/studio/main.d73499da517a45f6f776.js:1:4400322
    at e.invoke (http://apicurio.example.com/studio/polyfills.9c67d1be23abf75fea1a.js:1:7375)
    at Object.onInvoke (http://apicurio.example.com/studio/main.d73499da517a45f6f776.js:1:1918717)
    at e.invoke (http://apicurio.example.com/studio/polyfills.9c67d1be23abf75fea1a.js:1:7315)
    at t.run (http://apicurio.example.com/studio/polyfills.9c67d1be23abf75fea1a.js:1:2578)
    at http://apicurio.example.com/studio/polyfills.9c67d1be23abf75fea1a.js:1:14042
    at e.invokeTask (http://apicurio.example.com/studio/polyfills.9c67d1be23abf75fea1a.js:1:8059)
    at Object.onInvokeTask (http://apicurio.example.com/studio/main.d73499da517a45f6f776.js:1:1918629)
    at e.invokeTask (http://apicurio.example.com/studio/polyfills.9c67d1be23abf75fea1a.js:1:7980)
```

**Comment by EricWittmann** [comment]
The Apicurio editor uses a websocket to communicate with the server.  The address of the websocket is determined via some configuration provided to the UI via a specific endpoint.  For example, if you go here you'll see the config info:

https://studio.apicur.io/config.js

The above endpoint (for me) would return this:

```javascript
var ApicurioStudioConfig = {
  "mode" : "prod",
  "auth" : {
    "type" : "token",
    "token" : "--TOKEN--",
    "tokenRefreshPeriod" : 266,
    "logoutUrl" : "/logout"
  },
  "apis" : {
    "type" : "hub",
    "hubUrl" : "https://studio-api.apicur.io",
    "editingUrl" : "wss://studio-ws.apicur.io"
  },
  "user" : {
    "login" : "eric.wittmann@gmail.com",
    "id" : 0,
    "name" : "Eric Wittmann",
    "email" : "eric.wittmann@gmail.com"
  },
  "ui" : { },
  "features" : {
    "microcks" : false,
    "shareWithEveryone" : false
  }
};
```

Note that the value of the `editingUrl` property is **wss://studio-ws.apicur.io**.

Somehow yours is configured to be an **http** url rather than a **ws** or **wss** protocol.

**Comment by dbtech** [comment]
Thank you! That has the hint I needed. In addition, I have also understood that the whole protocol stack must be configured uniformly either with or without ssl. That is important for configuring the proxy.

**Comment by EricWittmann** [comment]
Glad to help!

**Comment by VIjayHP** [comment]
Hi Eric
    I am trying to deploy Apicurio using docker images on openshift and all 4 components are deployed successfully . But when i am trying to click on edit API after importing API definition (json file ) i am getting "Unexpected Error on Page()"  and when i checked the console logs i see below error.
**Error**: DOMException: Failed to construct 'WebSocket': The URL's scheme must be either 'ws' or 'wss'. 'https' is not allowed
In the environment variable i am passing https route url for APICURIO_UI_EDITING_URL . 
Kindly let me know what can be done here as Routes in Openshift supports on 80 and 443 ports?  Thanks!

**Comment by EricWittmann** [comment]
Try changing the value in that `APICURIO_UI_EDITING_URL` ENV var you are supplying from `https` to `wss`.  Websocket connections still go over port 80/443 so your routes should be fine.
